// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Team
{
    public static class GetTeams
    {
        /// <summary>
        /// Use this data source to retrieve teams of an organization. You can find out more about teams in the Buildkite
        /// [documentation](https://buildkite.com/docs/platform/team-management).
        /// </summary>
        public static Task<GetTeamsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTeamsResult>("buildkite:Team/getTeams:getTeams", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve teams of an organization. You can find out more about teams in the Buildkite
        /// [documentation](https://buildkite.com/docs/platform/team-management).
        /// </summary>
        public static Output<GetTeamsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTeamsResult>("buildkite:Team/getTeams:getTeams", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve teams of an organization. You can find out more about teams in the Buildkite
        /// [documentation](https://buildkite.com/docs/platform/team-management).
        /// </summary>
        public static Output<GetTeamsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTeamsResult>("buildkite:Team/getTeams:getTeams", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetTeamsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetTeamsTeamResult> Teams;

        [OutputConstructor]
        private GetTeamsResult(
            string id,

            ImmutableArray<Outputs.GetTeamsTeamResult> teams)
        {
            Id = id;
            Teams = teams;
        }
    }
}
