// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Cluster
{
    public static class GetCluster
    {
        /// <summary>
        /// Use this data source to retrieve a cluster by name. You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/clusters/overview).
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumi.Buildkite;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Buildkite.Cluster.GetCluster.Invoke(new()
        ///     {
        ///         Name = "default",
        ///     });
        /// 
        ///     // Assign a pipeline to that cluster
        ///     var terraform_provider_buildkite = new Buildkite.Pipeline.Pipeline("terraform-provider-buildkite", new()
        ///     {
        ///         Repository = "git@github.com:buildkite/terraform-provider-buildkite.git",
        ///         ClusterId = @default.Apply(@default =&gt; @default.Apply(getClusterResult =&gt; getClusterResult.Id)),
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetClusterResult> InvokeAsync(GetClusterArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetClusterResult>("buildkite:Cluster/getCluster:getCluster", args ?? new GetClusterArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve a cluster by name. You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/clusters/overview).
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumi.Buildkite;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Buildkite.Cluster.GetCluster.Invoke(new()
        ///     {
        ///         Name = "default",
        ///     });
        /// 
        ///     // Assign a pipeline to that cluster
        ///     var terraform_provider_buildkite = new Buildkite.Pipeline.Pipeline("terraform-provider-buildkite", new()
        ///     {
        ///         Repository = "git@github.com:buildkite/terraform-provider-buildkite.git",
        ///         ClusterId = @default.Apply(@default =&gt; @default.Apply(getClusterResult =&gt; getClusterResult.Id)),
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetClusterResult> Invoke(GetClusterInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetClusterResult>("buildkite:Cluster/getCluster:getCluster", args ?? new GetClusterInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetClusterArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the cluster to retrieve.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetClusterArgs()
        {
        }
        public static new GetClusterArgs Empty => new GetClusterArgs();
    }

    public sealed class GetClusterInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the cluster to retrieve.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetClusterInvokeArgs()
        {
        }
        public static new GetClusterInvokeArgs Empty => new GetClusterInvokeArgs();
    }


    [OutputType]
    public sealed class GetClusterResult
    {
        /// <summary>
        /// The color of the cluster.
        /// </summary>
        public readonly string Color;
        /// <summary>
        /// The description of the cluster.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The emoji of the cluster.
        /// </summary>
        public readonly string Emoji;
        /// <summary>
        /// The GraphQL ID of the cluster.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the cluster to retrieve.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The UUID of the cluster
        /// </summary>
        public readonly string Uuid;

        [OutputConstructor]
        private GetClusterResult(
            string color,

            string description,

            string emoji,

            string id,

            string name,

            string uuid)
        {
            Color = color;
            Description = description;
            Emoji = emoji;
            Id = id;
            Name = name;
            Uuid = uuid;
        }
    }
}
