# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetTeamsTeamResult',
]

@pulumi.output_type
class GetTeamsTeamResult(dict):
    def __init__(__self__, *,
                 default_member_role: _builtins.str,
                 description: _builtins.str,
                 id: _builtins.str,
                 is_default_team: _builtins.bool,
                 members_can_create_pipelines: _builtins.bool,
                 members_can_create_registries: _builtins.bool,
                 members_can_create_suites: _builtins.bool,
                 members_can_destroy_packages: _builtins.bool,
                 members_can_destroy_registries: _builtins.bool,
                 name: _builtins.str,
                 privacy: _builtins.str,
                 slug: _builtins.str,
                 uuid: _builtins.str):
        """
        :param _builtins.str default_member_role: The default member role for new team members.
        :param _builtins.str description: The description of the team.
        :param _builtins.str id: The GraphQL ID of the team.
        :param _builtins.bool is_default_team: Whether this is the default team for the organization.
        :param _builtins.bool members_can_create_pipelines: Whether team members can create pipelines.
        :param _builtins.bool members_can_create_registries: Whether team members can create registries.
        :param _builtins.bool members_can_create_suites: Whether team members can create test suites.
        :param _builtins.bool members_can_destroy_packages: Whether team members can destroy packages.
        :param _builtins.bool members_can_destroy_registries: Whether team members can destroy registries.
        :param _builtins.str name: The name of the team.
        :param _builtins.str privacy: The privacy setting of the team.
        :param _builtins.str slug: The slug of the team.
        :param _builtins.str uuid: The UUID of the team.
        """
        pulumi.set(__self__, "default_member_role", default_member_role)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "is_default_team", is_default_team)
        pulumi.set(__self__, "members_can_create_pipelines", members_can_create_pipelines)
        pulumi.set(__self__, "members_can_create_registries", members_can_create_registries)
        pulumi.set(__self__, "members_can_create_suites", members_can_create_suites)
        pulumi.set(__self__, "members_can_destroy_packages", members_can_destroy_packages)
        pulumi.set(__self__, "members_can_destroy_registries", members_can_destroy_registries)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "privacy", privacy)
        pulumi.set(__self__, "slug", slug)
        pulumi.set(__self__, "uuid", uuid)

    @_builtins.property
    @pulumi.getter(name="defaultMemberRole")
    def default_member_role(self) -> _builtins.str:
        """
        The default member role for new team members.
        """
        return pulumi.get(self, "default_member_role")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The description of the team.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The GraphQL ID of the team.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="isDefaultTeam")
    def is_default_team(self) -> _builtins.bool:
        """
        Whether this is the default team for the organization.
        """
        return pulumi.get(self, "is_default_team")

    @_builtins.property
    @pulumi.getter(name="membersCanCreatePipelines")
    def members_can_create_pipelines(self) -> _builtins.bool:
        """
        Whether team members can create pipelines.
        """
        return pulumi.get(self, "members_can_create_pipelines")

    @_builtins.property
    @pulumi.getter(name="membersCanCreateRegistries")
    def members_can_create_registries(self) -> _builtins.bool:
        """
        Whether team members can create registries.
        """
        return pulumi.get(self, "members_can_create_registries")

    @_builtins.property
    @pulumi.getter(name="membersCanCreateSuites")
    def members_can_create_suites(self) -> _builtins.bool:
        """
        Whether team members can create test suites.
        """
        return pulumi.get(self, "members_can_create_suites")

    @_builtins.property
    @pulumi.getter(name="membersCanDestroyPackages")
    def members_can_destroy_packages(self) -> _builtins.bool:
        """
        Whether team members can destroy packages.
        """
        return pulumi.get(self, "members_can_destroy_packages")

    @_builtins.property
    @pulumi.getter(name="membersCanDestroyRegistries")
    def members_can_destroy_registries(self) -> _builtins.bool:
        """
        Whether team members can destroy registries.
        """
        return pulumi.get(self, "members_can_destroy_registries")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the team.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def privacy(self) -> _builtins.str:
        """
        The privacy setting of the team.
        """
        return pulumi.get(self, "privacy")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> _builtins.str:
        """
        The slug of the team.
        """
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> _builtins.str:
        """
        The UUID of the team.
        """
        return pulumi.get(self, "uuid")


