// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A team member resource allows for the management of team membership for existing organization users.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as buildkite from "@pulumiverse/buildkite";
 *
 * const everyone = new buildkite.team.Team("everyone", {
 *     privacy: "VISIBLE",
 *     defaultTeam: false,
 *     defaultMemberRole: "MEMBER",
 * });
 * const aSmith = new buildkite.team.Member("aSmith", {
 *     teamId: everyone.id,
 *     userId: "VGVhbU1lbWJlci0tLTVlZDEyMmY2LTM2NjQtNDI1MS04YzMwLTc4NjRiMDdiZDQ4Zg==",
 *     role: "MEMBER",
 * });
 * ```
 *
 * ## Import
 *
 * import a team member resource using the GraphQL ID
 *
 * # 
 *
 *  you can use this query to find the ID:
 *
 *  query getTeamMemberId {
 *
 *  organization(slug: "ORGANIZATION_SLUG") {
 *
 *  teams(first: 2, search: "TEAM_SEARCH_TERM") {
 *
 *  edges {
 *
 *  node {
 *
 *  members(first: 2, search: "TEAM_MEMBER_SEARCH_TERM") {
 *
 *  edges {
 *
 *  node {
 *
 *  id
 *
 *  }
 *
 *  }
 *
 *  }
 *
 *  }
 *
 *  }
 *
 *  }
 *
 *  }
 *
 *  }
 *
 * ```sh
 * $ pulumi import buildkite:Team/member:Member a_smith VGVhbU1lbWJlci0tLTVlZDEyMmY2LTM2NjQtNDI1MS04YzMwLTc4NjRiMDdiZDQ4Zg==
 * ```
 */
export class Member extends pulumi.CustomResource {
    /**
     * Get an existing Member resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MemberState, opts?: pulumi.CustomResourceOptions): Member {
        return new Member(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:Team/member:Member';

    /**
     * Returns true if the given object is an instance of Member.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Member {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Member.__pulumiType;
    }

    /**
     * The role for the user. Either `MEMBER` or `MAINTAINER`.
     */
    public readonly role!: pulumi.Output<string>;
    /**
     * The GraphQL ID of the team.
     */
    public readonly teamId!: pulumi.Output<string>;
    /**
     * The GraphQL ID of the user.
     */
    public readonly userId!: pulumi.Output<string>;
    /**
     * The UUID of the team membership.
     */
    public /*out*/ readonly uuid!: pulumi.Output<string>;

    /**
     * Create a Member resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MemberArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MemberArgs | MemberState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MemberState | undefined;
            resourceInputs["role"] = state ? state.role : undefined;
            resourceInputs["teamId"] = state ? state.teamId : undefined;
            resourceInputs["userId"] = state ? state.userId : undefined;
            resourceInputs["uuid"] = state ? state.uuid : undefined;
        } else {
            const args = argsOrState as MemberArgs | undefined;
            if ((!args || args.role === undefined) && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            if ((!args || args.teamId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'teamId'");
            }
            if ((!args || args.userId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            resourceInputs["role"] = args ? args.role : undefined;
            resourceInputs["teamId"] = args ? args.teamId : undefined;
            resourceInputs["userId"] = args ? args.userId : undefined;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Member.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Member resources.
 */
export interface MemberState {
    /**
     * The role for the user. Either `MEMBER` or `MAINTAINER`.
     */
    role?: pulumi.Input<string>;
    /**
     * The GraphQL ID of the team.
     */
    teamId?: pulumi.Input<string>;
    /**
     * The GraphQL ID of the user.
     */
    userId?: pulumi.Input<string>;
    /**
     * The UUID of the team membership.
     */
    uuid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Member resource.
 */
export interface MemberArgs {
    /**
     * The role for the user. Either `MEMBER` or `MAINTAINER`.
     */
    role: pulumi.Input<string>;
    /**
     * The GraphQL ID of the team.
     */
    teamId: pulumi.Input<string>;
    /**
     * The GraphQL ID of the user.
     */
    userId: pulumi.Input<string>;
}
