// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Agent;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.buildkite.Agent.AgentTokenArgs;
import com.pulumiverse.buildkite.Agent.inputs.AgentTokenState;
import com.pulumiverse.buildkite.Utilities;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource allows you to create and manage non-clustered agent tokens.
 * You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/agent/v3/tokens).
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.buildkite.Agent.AgentToken;
 * import com.pulumi.buildkite.Agent.AgentTokenArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // create a default token
 *         var default_ = new AgentToken("default", AgentTokenArgs.builder()
 *             .description("Default token")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 */
@ResourceType(type="buildkite:Agent/agentToken:AgentToken")
public class AgentToken extends com.pulumi.resources.CustomResource {
    /**
     * The description of the agent token. Used to help identify its use.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description of the agent token. Used to help identify its use.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The token value used by an agent to register with the API.
     * 
     */
    @Export(name="token", refs={String.class}, tree="[0]")
    private Output<String> token;

    /**
     * @return The token value used by an agent to register with the API.
     * 
     */
    public Output<String> token() {
        return this.token;
    }
    /**
     * The UUID of the agent token.
     * 
     */
    @Export(name="uuid", refs={String.class}, tree="[0]")
    private Output<String> uuid;

    /**
     * @return The UUID of the agent token.
     * 
     */
    public Output<String> uuid() {
        return this.uuid;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AgentToken(java.lang.String name) {
        this(name, AgentTokenArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AgentToken(java.lang.String name, @Nullable AgentTokenArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AgentToken(java.lang.String name, @Nullable AgentTokenArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("buildkite:Agent/agentToken:AgentToken", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private AgentToken(java.lang.String name, Output<java.lang.String> id, @Nullable AgentTokenState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("buildkite:Agent/agentToken:AgentToken", name, state, makeResourceOptions(options, id), false);
    }

    private static AgentTokenArgs makeArgs(@Nullable AgentTokenArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AgentTokenArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse/pulumi-buildkite")
            .additionalSecretOutputs(List.of(
                "token"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AgentToken get(java.lang.String name, Output<java.lang.String> id, @Nullable AgentTokenState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AgentToken(name, id, state, options);
    }
}
