// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Cluster.Outputs
{

    [OutputType]
    public sealed class ClusterQueueHostedAgents
    {
        /// <summary>
        /// The instance shape to use for the Hosted Agent cluster queue. This can be a MacOS instance shape or a Linux instance shape.
        /// Valid values are:
        /// - MACOS_ARM64_M4_6X28
        /// - MACOS_ARM64_M4_12X56
        /// - LINUX_AMD64_2X4
        /// - LINUX_AMD64_4X16
        /// - LINUX_AMD64_8X32
        /// - LINUX_AMD64_16X64
        /// - LINUX_ARM64_2X4
        /// - LINUX_ARM64_4X16
        /// - LINUX_ARM64_8X32
        /// - LINUX_ARM64_16X64
        /// </summary>
        public readonly string InstanceShape;
        public readonly Outputs.ClusterQueueHostedAgentsLinux? Linux;
        public readonly Outputs.ClusterQueueHostedAgentsMac? Mac;

        [OutputConstructor]
        private ClusterQueueHostedAgents(
            string instanceShape,

            Outputs.ClusterQueueHostedAgentsLinux? linux,

            Outputs.ClusterQueueHostedAgentsMac? mac)
        {
            InstanceShape = instanceShape;
            Linux = linux;
            Mac = mac;
        }
    }
}
