// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Cluster.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterDefaultQueueState extends com.pulumi.resources.ResourceArgs {

    public static final ClusterDefaultQueueState Empty = new ClusterDefaultQueueState();

    /**
     * The GraphQL ID of the cluster to which to add a default queue.
     * 
     */
    @Import(name="clusterId")
    private @Nullable Output<String> clusterId;

    /**
     * @return The GraphQL ID of the cluster to which to add a default queue.
     * 
     */
    public Optional<Output<String>> clusterId() {
        return Optional.ofNullable(this.clusterId);
    }

    /**
     * The Key for the cluster queue; its unique identifier
     * 
     */
    @Import(name="key")
    private @Nullable Output<String> key;

    /**
     * @return The Key for the cluster queue; its unique identifier
     * 
     */
    public Optional<Output<String>> key() {
        return Optional.ofNullable(this.key);
    }

    /**
     * The GraphQL ID of the cluster queue to set as default on the cluster.
     * 
     */
    @Import(name="queueId")
    private @Nullable Output<String> queueId;

    /**
     * @return The GraphQL ID of the cluster queue to set as default on the cluster.
     * 
     */
    public Optional<Output<String>> queueId() {
        return Optional.ofNullable(this.queueId);
    }

    /**
     * The UUID of the cluster.
     * 
     */
    @Import(name="uuid")
    private @Nullable Output<String> uuid;

    /**
     * @return The UUID of the cluster.
     * 
     */
    public Optional<Output<String>> uuid() {
        return Optional.ofNullable(this.uuid);
    }

    private ClusterDefaultQueueState() {}

    private ClusterDefaultQueueState(ClusterDefaultQueueState $) {
        this.clusterId = $.clusterId;
        this.key = $.key;
        this.queueId = $.queueId;
        this.uuid = $.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterDefaultQueueState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterDefaultQueueState $;

        public Builder() {
            $ = new ClusterDefaultQueueState();
        }

        public Builder(ClusterDefaultQueueState defaults) {
            $ = new ClusterDefaultQueueState(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterId The GraphQL ID of the cluster to which to add a default queue.
         * 
         * @return builder
         * 
         */
        public Builder clusterId(@Nullable Output<String> clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        /**
         * @param clusterId The GraphQL ID of the cluster to which to add a default queue.
         * 
         * @return builder
         * 
         */
        public Builder clusterId(String clusterId) {
            return clusterId(Output.of(clusterId));
        }

        /**
         * @param key The Key for the cluster queue; its unique identifier
         * 
         * @return builder
         * 
         */
        public Builder key(@Nullable Output<String> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key The Key for the cluster queue; its unique identifier
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            return key(Output.of(key));
        }

        /**
         * @param queueId The GraphQL ID of the cluster queue to set as default on the cluster.
         * 
         * @return builder
         * 
         */
        public Builder queueId(@Nullable Output<String> queueId) {
            $.queueId = queueId;
            return this;
        }

        /**
         * @param queueId The GraphQL ID of the cluster queue to set as default on the cluster.
         * 
         * @return builder
         * 
         */
        public Builder queueId(String queueId) {
            return queueId(Output.of(queueId));
        }

        /**
         * @param uuid The UUID of the cluster.
         * 
         * @return builder
         * 
         */
        public Builder uuid(@Nullable Output<String> uuid) {
            $.uuid = uuid;
            return this;
        }

        /**
         * @param uuid The UUID of the cluster.
         * 
         * @return builder
         * 
         */
        public Builder uuid(String uuid) {
            return uuid(Output.of(uuid));
        }

        public ClusterDefaultQueueState build() {
            return $;
        }
    }

}
