# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .agent_token import *
from .get_meta import *
from .get_pipeline import *
from .get_team import *
from .pipeline import *
from .pipeline_schedule import *
from .provider import *
from .team import *
from .team_member import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_buildkite.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_buildkite.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "buildkite",
  "mod": "index/agentToken",
  "fqn": "pulumi_buildkite",
  "classes": {
   "buildkite:index/agentToken:AgentToken": "AgentToken"
  }
 },
 {
  "pkg": "buildkite",
  "mod": "index/pipeline",
  "fqn": "pulumi_buildkite",
  "classes": {
   "buildkite:index/pipeline:Pipeline": "Pipeline"
  }
 },
 {
  "pkg": "buildkite",
  "mod": "index/pipelineSchedule",
  "fqn": "pulumi_buildkite",
  "classes": {
   "buildkite:index/pipelineSchedule:PipelineSchedule": "PipelineSchedule"
  }
 },
 {
  "pkg": "buildkite",
  "mod": "index/team",
  "fqn": "pulumi_buildkite",
  "classes": {
   "buildkite:index/team:Team": "Team"
  }
 },
 {
  "pkg": "buildkite",
  "mod": "index/teamMember",
  "fqn": "pulumi_buildkite",
  "classes": {
   "buildkite:index/teamMember:TeamMember": "TeamMember"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "buildkite",
  "token": "pulumi:providers:buildkite",
  "fqn": "pulumi_buildkite",
  "class": "Provider"
 }
]
"""
)
