name: Download SDK asset
description: Restores the SDK asset for a language.

inputs:
  language:
    required: true
    description: One of nodejs, python, dotnet, go, java

runs:
  using: "composite"
  steps:
    - name: Download ${{ inputs.language }} SDK
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
      with:
        name: ${{ inputs.language }}-sdk.tar.gz
        path: ${{ github.workspace}}/sdk/
    - name: Uncompress SDK folder
      shell: bash
      run: tar -zxf ${{ github.workspace }}/sdk/${{ inputs.language }}.tar.gz -C ${{ github.workspace }}/sdk/${{ inputs.language }}
