// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A Cluster Secret is an encrypted key-value pair that can be accessed by agents within a cluster.
 * Secrets are encrypted and can only be accessed by agents that match the access policy.
 *
 * **Note:** Secret values are write-only in the Buildkite API and cannot be retrieved after they are set.
 * Exactly one of value or valueWo must be configured. The value attribute is stored in
 * Terraform state so Terraform can detect changes. Use valueWo with valueWoVersion
 * to pass a secret value without storing it in pulumi preview or state artifacts.
 *
 * ## Import
 *
 * Using `pulumi import`, import resources using the `id`. For example:
 * Import a cluster secret using {cluster_id}/{secret_id}
 *
 * You can find the clusterId under cluster settings in the UI
 * and find the secretId from the secrets list using the
 * REST API response from:
 * GET /v2/organizations/{org_slug}/clusters/{cluster_id}/secrets
 *
 * ```sh
 * $ pulumi import buildkite:Cluster/clusterSecret:ClusterSecret example 01234567-89ab-cdef-0123-456789abcdef/fedcba98-7654-3210-fedc-ba9876543210
 * ```
 *
 * Because Buildkite does not return secret values after they are set, imported secrets cannot populate `value` or `valueWoVersion` in Terraform state. Configure either `value` or `valueWo` before the next plan. When using `valueWo`, the first apply after import will re-send the configured secret value because `valueWoVersion` changes from no state value to the configured value.
 */
export class ClusterSecret extends pulumi.CustomResource {
    /**
     * Get an existing ClusterSecret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterSecretState, opts?: pulumi.CustomResourceOptions): ClusterSecret {
        return new ClusterSecret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:Cluster/clusterSecret:ClusterSecret';

    /**
     * Returns true if the given object is an instance of ClusterSecret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterSecret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterSecret.__pulumiType;
    }

    /**
     * The UUID of the cluster this secret belongs to.
     */
    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * The time when the secret was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * A description of what this secret is for.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters. Must not start with `buildkite` or `bk` (case-insensitive) as these prefixes are reserved.
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * YAML access policy defining which pipelines and branches can access this secret.
     */
    declare public readonly policy: pulumi.Output<string | undefined>;
    /**
     * The time when the secret was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * The secret value. Must be less than 8KB. Exactly one of `value` or `valueWo` must be configured. This value is stored in Terraform state; use `valueWo` with `valueWoVersion` to avoid storing secret values in state.
     */
    declare public readonly value: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only secret value. Must be less than 8KB. Exactly one of `value` or `valueWo` must be configured. This value is not stored in Terraform plan or state artifacts. Pair with `valueWoVersion` to trigger secret value updates.
     */
    declare public readonly valueWo: pulumi.Output<string | undefined>;
    /**
     * Non-empty, non-secret version identifier for `valueWo`. Required when `valueWo` is configured. Change this value when the write-only secret value changes, for example by using an external secret manager version ID.
     */
    declare public readonly valueWoVersion: pulumi.Output<string | undefined>;

    /**
     * Create a ClusterSecret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterSecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterSecretArgs | ClusterSecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClusterSecretState | undefined;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["key"] = state?.key;
            resourceInputs["policy"] = state?.policy;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["value"] = state?.value;
            resourceInputs["valueWo"] = state?.valueWo;
            resourceInputs["valueWoVersion"] = state?.valueWoVersion;
        } else {
            const args = argsOrState as ClusterSecretArgs | undefined;
            if (args?.clusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["description"] = args?.description;
            resourceInputs["key"] = args?.key;
            resourceInputs["policy"] = args?.policy;
            resourceInputs["value"] = args?.value ? pulumi.secret(args.value) : undefined;
            resourceInputs["valueWo"] = args?.valueWo ? pulumi.secret(args.valueWo) : undefined;
            resourceInputs["valueWoVersion"] = args?.valueWoVersion;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["value", "valueWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ClusterSecret.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ClusterSecret resources.
 */
export interface ClusterSecretState {
    /**
     * The UUID of the cluster this secret belongs to.
     */
    clusterId?: pulumi.Input<string>;
    /**
     * The time when the secret was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * A description of what this secret is for.
     */
    description?: pulumi.Input<string>;
    /**
     * The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters. Must not start with `buildkite` or `bk` (case-insensitive) as these prefixes are reserved.
     */
    key?: pulumi.Input<string>;
    /**
     * YAML access policy defining which pipelines and branches can access this secret.
     */
    policy?: pulumi.Input<string>;
    /**
     * The time when the secret was last updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * The secret value. Must be less than 8KB. Exactly one of `value` or `valueWo` must be configured. This value is stored in Terraform state; use `valueWo` with `valueWoVersion` to avoid storing secret values in state.
     */
    value?: pulumi.Input<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only secret value. Must be less than 8KB. Exactly one of `value` or `valueWo` must be configured. This value is not stored in Terraform plan or state artifacts. Pair with `valueWoVersion` to trigger secret value updates.
     */
    valueWo?: pulumi.Input<string>;
    /**
     * Non-empty, non-secret version identifier for `valueWo`. Required when `valueWo` is configured. Change this value when the write-only secret value changes, for example by using an external secret manager version ID.
     */
    valueWoVersion?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ClusterSecret resource.
 */
export interface ClusterSecretArgs {
    /**
     * The UUID of the cluster this secret belongs to.
     */
    clusterId: pulumi.Input<string>;
    /**
     * A description of what this secret is for.
     */
    description?: pulumi.Input<string>;
    /**
     * The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters. Must not start with `buildkite` or `bk` (case-insensitive) as these prefixes are reserved.
     */
    key: pulumi.Input<string>;
    /**
     * YAML access policy defining which pipelines and branches can access this secret.
     */
    policy?: pulumi.Input<string>;
    /**
     * The secret value. Must be less than 8KB. Exactly one of `value` or `valueWo` must be configured. This value is stored in Terraform state; use `valueWo` with `valueWoVersion` to avoid storing secret values in state.
     */
    value?: pulumi.Input<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only secret value. Must be less than 8KB. Exactly one of `value` or `valueWo` must be configured. This value is not stored in Terraform plan or state artifacts. Pair with `valueWoVersion` to trigger secret value updates.
     */
    valueWo?: pulumi.Input<string>;
    /**
     * Non-empty, non-secret version identifier for `valueWo`. Required when `valueWo` is configured. Change this value when the write-only secret value changes, for example by using an external secret manager version ID.
     */
    valueWoVersion?: pulumi.Input<string>;
}
