// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * This resource allows you to manage cluster maintainers in Buildkite. Maintainers can be either users or teams
 * that have permission to manage a specific cluster. Find out more information in our
 * [documentation](https://buildkite.com/docs/clusters/manage-clusters).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as buildkite from "@pulumiverse/buildkite";
 *
 * // Add a user as a cluster maintainer
 * const userMaintainer = new buildkite.cluster.ClusterMaintainer("user_maintainer", {
 *     clusterUuid: primary.uuid,
 *     userUuid: "01234567-89ab-cdef-0123-456789abcdef",
 * });
 * // Add a team as a cluster maintainer
 * const teamMaintainer = new buildkite.cluster.ClusterMaintainer("team_maintainer", {
 *     clusterUuid: primary.uuid,
 *     teamUuid: "01234567-89ab-cdef-0123-456789abcdef",
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import resources using the `id`. For example:
 *
 * Import a cluster maintainer using {cluster_uuid}/{permission_uuid}
 *
 * You can find the cluster_uuid and the permission_uuid
 *
 * from the maintainers list using the cluster data source or REST
 *
 * API response from:
 *
 * GET /v2/organizations/{org_slug}/clusters/{cluster_uuid}/maintainers
 *
 * ```sh
 * $ pulumi import buildkite:Cluster/clusterMaintainer:ClusterMaintainer user_maintainer 01234567-89ab-cdef-0123-456789abcdef/977b68d3-f8fe-4784-8d43-5bc857e10541
 * ```
 */
export class ClusterMaintainer extends pulumi.CustomResource {
    /**
     * Get an existing ClusterMaintainer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterMaintainerState, opts?: pulumi.CustomResourceOptions): ClusterMaintainer {
        return new ClusterMaintainer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:Cluster/clusterMaintainer:ClusterMaintainer';

    /**
     * Returns true if the given object is an instance of ClusterMaintainer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterMaintainer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterMaintainer.__pulumiType;
    }

    /**
     * The email of the actor (only for users).
     */
    declare public /*out*/ readonly actorEmail: pulumi.Output<string>;
    /**
     * The name of the actor.
     */
    declare public /*out*/ readonly actorName: pulumi.Output<string>;
    /**
     * The slug of the actor (only for teams).
     */
    declare public /*out*/ readonly actorSlug: pulumi.Output<string>;
    /**
     * The type of the actor (user or team).
     */
    declare public /*out*/ readonly actorType: pulumi.Output<string>;
    /**
     * The UUID of the actor (user or team) that is the maintainer.
     */
    declare public /*out*/ readonly actorUuid: pulumi.Output<string>;
    /**
     * The UUID of the cluster.
     */
    declare public readonly clusterUuid: pulumi.Output<string>;
    /**
     * The UUID of the team to add as a maintainer. This is mutually exclusive with user*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     */
    declare public readonly teamUuid: pulumi.Output<string | undefined>;
    /**
     * The UUID of the user to add as a maintainer. This is mutually exclusive with team*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     */
    declare public readonly userUuid: pulumi.Output<string | undefined>;

    /**
     * Create a ClusterMaintainer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterMaintainerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterMaintainerArgs | ClusterMaintainerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClusterMaintainerState | undefined;
            resourceInputs["actorEmail"] = state?.actorEmail;
            resourceInputs["actorName"] = state?.actorName;
            resourceInputs["actorSlug"] = state?.actorSlug;
            resourceInputs["actorType"] = state?.actorType;
            resourceInputs["actorUuid"] = state?.actorUuid;
            resourceInputs["clusterUuid"] = state?.clusterUuid;
            resourceInputs["teamUuid"] = state?.teamUuid;
            resourceInputs["userUuid"] = state?.userUuid;
        } else {
            const args = argsOrState as ClusterMaintainerArgs | undefined;
            if (args?.clusterUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterUuid'");
            }
            resourceInputs["clusterUuid"] = args?.clusterUuid;
            resourceInputs["teamUuid"] = args?.teamUuid;
            resourceInputs["userUuid"] = args?.userUuid;
            resourceInputs["actorEmail"] = undefined /*out*/;
            resourceInputs["actorName"] = undefined /*out*/;
            resourceInputs["actorSlug"] = undefined /*out*/;
            resourceInputs["actorType"] = undefined /*out*/;
            resourceInputs["actorUuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterMaintainer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ClusterMaintainer resources.
 */
export interface ClusterMaintainerState {
    /**
     * The email of the actor (only for users).
     */
    actorEmail?: pulumi.Input<string>;
    /**
     * The name of the actor.
     */
    actorName?: pulumi.Input<string>;
    /**
     * The slug of the actor (only for teams).
     */
    actorSlug?: pulumi.Input<string>;
    /**
     * The type of the actor (user or team).
     */
    actorType?: pulumi.Input<string>;
    /**
     * The UUID of the actor (user or team) that is the maintainer.
     */
    actorUuid?: pulumi.Input<string>;
    /**
     * The UUID of the cluster.
     */
    clusterUuid?: pulumi.Input<string>;
    /**
     * The UUID of the team to add as a maintainer. This is mutually exclusive with user*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     */
    teamUuid?: pulumi.Input<string>;
    /**
     * The UUID of the user to add as a maintainer. This is mutually exclusive with team*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     */
    userUuid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ClusterMaintainer resource.
 */
export interface ClusterMaintainerArgs {
    /**
     * The UUID of the cluster.
     */
    clusterUuid: pulumi.Input<string>;
    /**
     * The UUID of the team to add as a maintainer. This is mutually exclusive with user*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     */
    teamUuid?: pulumi.Input<string>;
    /**
     * The UUID of the user to add as a maintainer. This is mutually exclusive with team*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     */
    userUuid?: pulumi.Input<string>;
}
