// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Cluster.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ClusterQueueHostedAgentsLinux {
    /**
     * @return A URL reference to a container image that will be used for jobs running within the queue. This URL is required to be publicly available, or pushed to the internal registry available within the cluster. Please note that this value is currently experimental and in preview. Please contact support{@literal @}buildkite.com to enable this functionality for your organization.
     * 
     */
    private String agentImageRef;

    private ClusterQueueHostedAgentsLinux() {}
    /**
     * @return A URL reference to a container image that will be used for jobs running within the queue. This URL is required to be publicly available, or pushed to the internal registry available within the cluster. Please note that this value is currently experimental and in preview. Please contact support{@literal @}buildkite.com to enable this functionality for your organization.
     * 
     */
    public String agentImageRef() {
        return this.agentImageRef;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterQueueHostedAgentsLinux defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String agentImageRef;
        public Builder() {}
        public Builder(ClusterQueueHostedAgentsLinux defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.agentImageRef = defaults.agentImageRef;
        }

        @CustomType.Setter
        public Builder agentImageRef(String agentImageRef) {
            if (agentImageRef == null) {
              throw new MissingRequiredPropertyException("ClusterQueueHostedAgentsLinux", "agentImageRef");
            }
            this.agentImageRef = agentImageRef;
            return this;
        }
        public ClusterQueueHostedAgentsLinux build() {
            final var _resultValue = new ClusterQueueHostedAgentsLinux();
            _resultValue.agentImageRef = agentImageRef;
            return _resultValue;
        }
    }
}
