// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Organization
{
    public static class GetPortal
    {
        /// <summary>
        /// Use this data source to retrieve a portal by slug. You can find out more about portals in the Buildkite [documentation](https://buildkite.com/docs/apis/portals).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var viewer = Buildkite.Organization.GetPortal.Invoke(new()
        ///     {
        ///         Slug = "viewer-info",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetPortalResult> InvokeAsync(GetPortalArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPortalResult>("buildkite:Organization/getPortal:getPortal", args ?? new GetPortalArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve a portal by slug. You can find out more about portals in the Buildkite [documentation](https://buildkite.com/docs/apis/portals).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var viewer = Buildkite.Organization.GetPortal.Invoke(new()
        ///     {
        ///         Slug = "viewer-info",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPortalResult> Invoke(GetPortalInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPortalResult>("buildkite:Organization/getPortal:getPortal", args ?? new GetPortalInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve a portal by slug. You can find out more about portals in the Buildkite [documentation](https://buildkite.com/docs/apis/portals).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var viewer = Buildkite.Organization.GetPortal.Invoke(new()
        ///     {
        ///         Slug = "viewer-info",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPortalResult> Invoke(GetPortalInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPortalResult>("buildkite:Organization/getPortal:getPortal", args ?? new GetPortalInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPortalArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The slug of the portal to retrieve.
        /// </summary>
        [Input("slug", required: true)]
        public string Slug { get; set; } = null!;

        public GetPortalArgs()
        {
        }
        public static new GetPortalArgs Empty => new GetPortalArgs();
    }

    public sealed class GetPortalInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The slug of the portal to retrieve.
        /// </summary>
        [Input("slug", required: true)]
        public Input<string> Slug { get; set; } = null!;

        public GetPortalInvokeArgs()
        {
        }
        public static new GetPortalInvokeArgs Empty => new GetPortalInvokeArgs();
    }


    [OutputType]
    public sealed class GetPortalResult
    {
        /// <summary>
        /// Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal.
        /// </summary>
        public readonly string AllowedIpAddresses;
        /// <summary>
        /// The time when the portal was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Information about the user who created the portal.
        /// </summary>
        public readonly Outputs.GetPortalCreatedByResult CreatedBy;
        /// <summary>
        /// The description of the portal.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the portal.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The GraphQL query that the portal executes.
        /// </summary>
        public readonly string Query;
        /// <summary>
        /// The slug of the portal to retrieve.
        /// </summary>
        public readonly string Slug;
        /// <summary>
        /// Whether users can invoke the portal.
        /// </summary>
        public readonly bool UserInvokable;
        /// <summary>
        /// The UUID of the portal.
        /// </summary>
        public readonly string Uuid;

        [OutputConstructor]
        private GetPortalResult(
            string allowedIpAddresses,

            string createdAt,

            Outputs.GetPortalCreatedByResult createdBy,

            string description,

            string id,

            string name,

            string query,

            string slug,

            bool userInvokable,

            string uuid)
        {
            AllowedIpAddresses = allowedIpAddresses;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Description = description;
            Id = id;
            Name = name;
            Query = query;
            Slug = slug;
            UserInvokable = userInvokable;
            Uuid = uuid;
        }
    }
}
