// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Organization
{
    public static class GetRule
    {
        /// <summary>
        /// &gt; Rules is a feature that is currently in development and enabled on an opt-in basis for early access. To have this enabled for your organization for utilizing this data source, please reach out to Buildkite's Support Team.
        /// 
        /// Use this data source to retrieve an organization rule by its ID.
        /// 
        /// More information on organization rules can be found in the [documentation](https://buildkite.com/docs/pipelines/rules).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Read an organization rule by its id
        ///     var dataArtifactsReadDevTest = Buildkite.Organization.GetRule.Invoke(new()
        ///     {
        ///         Id = artifactsReadDevTest.Id,
        ///     });
        /// 
        ///     // Read an organization rule by its uuid
        ///     var dataArtifactsReadTestDev = Buildkite.Organization.GetRule.Invoke(new()
        ///     {
        ///         Uuid = artifactsReadTestDev.Uuid,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetRuleResult> InvokeAsync(GetRuleArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRuleResult>("buildkite:Organization/getRule:getRule", args ?? new GetRuleArgs(), options.WithDefaults());

        /// <summary>
        /// &gt; Rules is a feature that is currently in development and enabled on an opt-in basis for early access. To have this enabled for your organization for utilizing this data source, please reach out to Buildkite's Support Team.
        /// 
        /// Use this data source to retrieve an organization rule by its ID.
        /// 
        /// More information on organization rules can be found in the [documentation](https://buildkite.com/docs/pipelines/rules).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Read an organization rule by its id
        ///     var dataArtifactsReadDevTest = Buildkite.Organization.GetRule.Invoke(new()
        ///     {
        ///         Id = artifactsReadDevTest.Id,
        ///     });
        /// 
        ///     // Read an organization rule by its uuid
        ///     var dataArtifactsReadTestDev = Buildkite.Organization.GetRule.Invoke(new()
        ///     {
        ///         Uuid = artifactsReadTestDev.Uuid,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRuleResult> Invoke(GetRuleInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRuleResult>("buildkite:Organization/getRule:getRule", args ?? new GetRuleInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// &gt; Rules is a feature that is currently in development and enabled on an opt-in basis for early access. To have this enabled for your organization for utilizing this data source, please reach out to Buildkite's Support Team.
        /// 
        /// Use this data source to retrieve an organization rule by its ID.
        /// 
        /// More information on organization rules can be found in the [documentation](https://buildkite.com/docs/pipelines/rules).
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Buildkite = Pulumiverse.Buildkite;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Read an organization rule by its id
        ///     var dataArtifactsReadDevTest = Buildkite.Organization.GetRule.Invoke(new()
        ///     {
        ///         Id = artifactsReadDevTest.Id,
        ///     });
        /// 
        ///     // Read an organization rule by its uuid
        ///     var dataArtifactsReadTestDev = Buildkite.Organization.GetRule.Invoke(new()
        ///     {
        ///         Uuid = artifactsReadTestDev.Uuid,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetRuleResult> Invoke(GetRuleInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRuleResult>("buildkite:Organization/getRule:getRule", args ?? new GetRuleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRuleArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The GraphQL ID of the organization rule.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The UUID of the organization rule.
        /// </summary>
        [Input("uuid")]
        public string? Uuid { get; set; }

        public GetRuleArgs()
        {
        }
        public static new GetRuleArgs Empty => new GetRuleArgs();
    }

    public sealed class GetRuleInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The GraphQL ID of the organization rule.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The UUID of the organization rule.
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        public GetRuleInvokeArgs()
        {
        }
        public static new GetRuleInvokeArgs Empty => new GetRuleInvokeArgs();
    }


    [OutputType]
    public sealed class GetRuleResult
    {
        /// <summary>
        /// The action defined between source and target resources.
        /// </summary>
        public readonly string Action;
        /// <summary>
        /// The description of the organization rule.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Whether this organization rule allows or denys the action to take place between source and target resources.
        /// </summary>
        public readonly string Effect;
        /// <summary>
        /// The GraphQL ID of the organization rule.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The source resource type that this organization rule allows or denies to invoke its defined action.
        /// </summary>
        public readonly string SourceType;
        /// <summary>
        /// The UUID of the resource that this organization rule allows or denies invocating its defined action.
        /// </summary>
        public readonly string SourceUuid;
        /// <summary>
        /// The target resource type that this organization rule allows or denies the source to respective action.
        /// </summary>
        public readonly string TargetType;
        /// <summary>
        /// The UUID of the target resourcee that this organization rule allows or denies invocation its respective action.
        /// </summary>
        public readonly string TargetUuid;
        /// <summary>
        /// The type of organization rule.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The UUID of the organization rule.
        /// </summary>
        public readonly string? Uuid;
        /// <summary>
        /// The JSON document that this organization rule implements.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetRuleResult(
            string action,

            string description,

            string effect,

            string? id,

            string sourceType,

            string sourceUuid,

            string targetType,

            string targetUuid,

            string type,

            string? uuid,

            string value)
        {
            Action = action;
            Description = description;
            Effect = effect;
            Id = id;
            SourceType = sourceType;
            SourceUuid = sourceUuid;
            TargetType = targetType;
            TargetUuid = targetUuid;
            Type = type;
            Uuid = uuid;
            Value = value;
        }
    }
}
