// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Organization
{
    /// <summary>
    /// &gt; Rules is a feature that is currently in development and enabled on an opt-in basis for early access. To have this enabled for your organization for utilizing this data source, please reach out to Buildkite's Support Team.
    /// 
    /// An Organization Rule allows specifying explicit rules between two Buildkite resources and the desired effect/action.
    /// 
    /// More information on organization rules can be found in the [documentation](https://buildkite.com/docs/pipelines/rules).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Buildkite = Pulumiverse.Buildkite;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Creates a TRIGGER_BUILD organization rule with required attributes
    ///     var triggerBuildTestDev = new Buildkite.Organization.Rule("trigger_build_test_dev", new()
    ///     {
    ///         Type = "pipeline.trigger_build.pipeline",
    ///         Value = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["source_pipeline"] = appDevDeploy.Uuid,
    ///             ["target_pipeline"] = appTestCi.Uuid,
    ///         }),
    ///     });
    /// 
    ///     // Creates a ARTIFACTS_READ organization rule with an optional description
    ///     var artifactsReadTestDev = new Buildkite.Organization.Rule("artifacts_read_test_dev", new()
    ///     {
    ///         Type = "pipeline.artifacts_read.pipeline",
    ///         Description = "A rule to allow artifact reads by app_test_ci to app_dev_deploy",
    ///         Value = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["source_pipeline"] = appTestCi.Uuid,
    ///             ["target_pipeline"] = appDevDeploy.Uuid,
    ///         }),
    ///     });
    /// 
    ///     // Creates a TRIGGER_BUILD organization rule with an optional description and conditions
    ///     var triggerBuildTestDevCond = new Buildkite.Organization.Rule("trigger_build_test_dev_cond", new()
    ///     {
    ///         Type = "pipeline.trigger_build.pipeline",
    ///         Description = "A rule to allow app_dev_deploy to trigger app_test_ci builds with conditions",
    ///         Value = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["source_pipeline"] = appDevDeploy.Uuid,
    ///             ["target_pipeline"] = appTestCi.Uuid,
    ///             ["conditions"] = new[]
    ///             {
    ///                 "source.build.creator.teams includes 'deploy'",
    ///                 "source.build.branch == 'main'",
    ///             },
    ///         }),
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Using `pulumi import`, import resources using the `id`. For example:
    /// 
    /// import an organization rule resource using the rules GraphQL ID
    /// 
    /// You can use this query to find the first 50 organiation rules (adjust for less or more):
    /// 
    /// query getOrganizationRules {
    /// 
    ///   organization(slug: "ORGANIZATION_SLUG") {
    /// 
    ///     rules(first: 50) {
    ///     
    ///       edges{
    ///     
    ///         node{
    ///     
    ///           id
    ///     
    ///           sourceType
    ///     
    ///           targetType
    ///     
    ///           action
    ///     
    ///         }
    ///     
    ///       }
    ///     
    ///     }
    /// 
    ///   }
    /// 
    /// }
    /// 
    /// Depending on the speciific source/target, you're also able to filter on the source/target information
    /// 
    /// query getOrganizationRules {
    /// 
    ///   organization(slug: "ORGANIZATION_SLUG") {
    /// 
    ///     rules(first: 50) {
    ///     
    ///       edges{
    ///     
    ///         node{
    ///     
    ///           id
    ///     
    ///           sourceType
    ///     
    ///           source {
    ///     
    ///             ... on Pipeline{
    ///     
    ///               uuid
    ///     
    ///               name
    ///     
    ///             }            
    ///     
    ///           }
    ///     
    ///           targetType
    ///     
    ///           target {
    ///     
    ///             ... on Pipeline{
    ///     
    ///               uuid
    ///     
    ///               name
    ///     
    ///             }            
    ///     
    ///           }
    ///     
    ///           action
    ///     
    ///         }
    ///     
    ///       }
    ///     
    ///     }
    /// 
    ///   }
    /// 
    /// }
    /// 
    /// ```sh
    /// $ pulumi import buildkite:Organization/rule:Rule artifact_read UnVsZS0tLTAxOTE5NmU2LWNiNjctNzZiZi1iYzAyLTVhYzFiNzhhMWMyOA==
    /// ```
    /// </summary>
    [BuildkiteResourceType("buildkite:Organization/rule:Rule")]
    public partial class Rule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The action defined between source and target resources.
        /// </summary>
        [Output("action")]
        public Output<string> Action { get; private set; } = null!;

        /// <summary>
        /// The description of the organization rule.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Whether this organization rule allows or denies the action to take place between source and target resources.
        /// </summary>
        [Output("effect")]
        public Output<string> Effect { get; private set; } = null!;

        /// <summary>
        /// The source resource type that this organization rule allows or denies to invoke its defined action.
        /// </summary>
        [Output("sourceType")]
        public Output<string> SourceType { get; private set; } = null!;

        /// <summary>
        /// The UUID of the resource that this organization rule allows or denies invocating its defined action.
        /// </summary>
        [Output("sourceUuid")]
        public Output<string> SourceUuid { get; private set; } = null!;

        /// <summary>
        /// The target resource type that this organization rule allows or denies the source to respective action.
        /// </summary>
        [Output("targetType")]
        public Output<string> TargetType { get; private set; } = null!;

        /// <summary>
        /// The UUID of the target resource that this organization rule allows or denies invocation its respective action.
        /// </summary>
        [Output("targetUuid")]
        public Output<string> TargetUuid { get; private set; } = null!;

        /// <summary>
        /// The type of organization rule.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// The UUID of the organization rule.
        /// </summary>
        [Output("uuid")]
        public Output<string> Uuid { get; private set; } = null!;

        /// <summary>
        /// The JSON document that this organization rule implements.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a Rule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Rule(string name, RuleArgs args, CustomResourceOptions? options = null)
            : base("buildkite:Organization/rule:Rule", name, args ?? new RuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Rule(string name, Input<string> id, RuleState? state = null, CustomResourceOptions? options = null)
            : base("buildkite:Organization/rule:Rule", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-buildkite",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Rule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Rule Get(string name, Input<string> id, RuleState? state = null, CustomResourceOptions? options = null)
        {
            return new Rule(name, id, state, options);
        }
    }

    public sealed class RuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the organization rule.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The type of organization rule.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// The JSON document that this organization rule implements.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public RuleArgs()
        {
        }
        public static new RuleArgs Empty => new RuleArgs();
    }

    public sealed class RuleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The action defined between source and target resources.
        /// </summary>
        [Input("action")]
        public Input<string>? Action { get; set; }

        /// <summary>
        /// The description of the organization rule.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether this organization rule allows or denies the action to take place between source and target resources.
        /// </summary>
        [Input("effect")]
        public Input<string>? Effect { get; set; }

        /// <summary>
        /// The source resource type that this organization rule allows or denies to invoke its defined action.
        /// </summary>
        [Input("sourceType")]
        public Input<string>? SourceType { get; set; }

        /// <summary>
        /// The UUID of the resource that this organization rule allows or denies invocating its defined action.
        /// </summary>
        [Input("sourceUuid")]
        public Input<string>? SourceUuid { get; set; }

        /// <summary>
        /// The target resource type that this organization rule allows or denies the source to respective action.
        /// </summary>
        [Input("targetType")]
        public Input<string>? TargetType { get; set; }

        /// <summary>
        /// The UUID of the target resource that this organization rule allows or denies invocation its respective action.
        /// </summary>
        [Input("targetUuid")]
        public Input<string>? TargetUuid { get; set; }

        /// <summary>
        /// The type of organization rule.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// The UUID of the organization rule.
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        /// <summary>
        /// The JSON document that this organization rule implements.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public RuleState()
        {
        }
        public static new RuleState Empty => new RuleState();
    }
}
