// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Cluster;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.resources.InvokeArgs;
import com.pulumiverse.buildkite.Cluster.inputs.GetClusterArgs;
import com.pulumiverse.buildkite.Cluster.inputs.GetClusterPlainArgs;
import com.pulumiverse.buildkite.Cluster.outputs.GetClusterResult;
import com.pulumiverse.buildkite.Cluster.outputs.GetClustersResult;
import com.pulumiverse.buildkite.Utilities;
import java.util.concurrent.CompletableFuture;

public final class ClusterFunctions {
    /**
     * Use this data source to retrieve a cluster by name. You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/clusters/overview).
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.buildkite.Cluster.ClusterFunctions;
     * import com.pulumi.buildkite.Cluster.inputs.GetClusterArgs;
     * import com.pulumi.buildkite.Pipeline.Pipeline;
     * import com.pulumi.buildkite.Pipeline.PipelineArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App }{{@code
     *     public static void main(String[] args) }{{@code
     *         Pulumi.run(App::stack);
     *     }}{@code
     * 
     *     public static void stack(Context ctx) }{{@code
     *         // Find the "default" cluster
     *         final var default = ClusterFunctions.getCluster(GetClusterArgs.builder()
     *             .name("default")
     *             .build());
     * 
     *         // Assign a pipeline to that cluster
     *         var terraform_provider_buildkite = new Pipeline("terraform-provider-buildkite", PipelineArgs.builder()
     *             .name("terraform-provider-buildkite")
     *             .repository("git}{@literal @}{@code github.com:buildkite/terraform-provider-buildkite.git")
     *             .clusterId(default_.id())
     *             .build());
     * 
     *     }}{@code
     * }}{@code
     * }
     * </pre>
     * 
     */
    public static Output<GetClusterResult> getCluster(GetClusterArgs args) {
        return getCluster(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve a cluster by name. You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/clusters/overview).
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.buildkite.Cluster.ClusterFunctions;
     * import com.pulumi.buildkite.Cluster.inputs.GetClusterArgs;
     * import com.pulumi.buildkite.Pipeline.Pipeline;
     * import com.pulumi.buildkite.Pipeline.PipelineArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App }{{@code
     *     public static void main(String[] args) }{{@code
     *         Pulumi.run(App::stack);
     *     }}{@code
     * 
     *     public static void stack(Context ctx) }{{@code
     *         // Find the "default" cluster
     *         final var default = ClusterFunctions.getCluster(GetClusterArgs.builder()
     *             .name("default")
     *             .build());
     * 
     *         // Assign a pipeline to that cluster
     *         var terraform_provider_buildkite = new Pipeline("terraform-provider-buildkite", PipelineArgs.builder()
     *             .name("terraform-provider-buildkite")
     *             .repository("git}{@literal @}{@code github.com:buildkite/terraform-provider-buildkite.git")
     *             .clusterId(default_.id())
     *             .build());
     * 
     *     }}{@code
     * }}{@code
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetClusterResult> getClusterPlain(GetClusterPlainArgs args) {
        return getClusterPlain(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve a cluster by name. You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/clusters/overview).
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.buildkite.Cluster.ClusterFunctions;
     * import com.pulumi.buildkite.Cluster.inputs.GetClusterArgs;
     * import com.pulumi.buildkite.Pipeline.Pipeline;
     * import com.pulumi.buildkite.Pipeline.PipelineArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App }{{@code
     *     public static void main(String[] args) }{{@code
     *         Pulumi.run(App::stack);
     *     }}{@code
     * 
     *     public static void stack(Context ctx) }{{@code
     *         // Find the "default" cluster
     *         final var default = ClusterFunctions.getCluster(GetClusterArgs.builder()
     *             .name("default")
     *             .build());
     * 
     *         // Assign a pipeline to that cluster
     *         var terraform_provider_buildkite = new Pipeline("terraform-provider-buildkite", PipelineArgs.builder()
     *             .name("terraform-provider-buildkite")
     *             .repository("git}{@literal @}{@code github.com:buildkite/terraform-provider-buildkite.git")
     *             .clusterId(default_.id())
     *             .build());
     * 
     *     }}{@code
     * }}{@code
     * }
     * </pre>
     * 
     */
    public static Output<GetClusterResult> getCluster(GetClusterArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("buildkite:Cluster/getCluster:getCluster", TypeShape.of(GetClusterResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve a cluster by name. You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/clusters/overview).
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.buildkite.Cluster.ClusterFunctions;
     * import com.pulumi.buildkite.Cluster.inputs.GetClusterArgs;
     * import com.pulumi.buildkite.Pipeline.Pipeline;
     * import com.pulumi.buildkite.Pipeline.PipelineArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App }{{@code
     *     public static void main(String[] args) }{{@code
     *         Pulumi.run(App::stack);
     *     }}{@code
     * 
     *     public static void stack(Context ctx) }{{@code
     *         // Find the "default" cluster
     *         final var default = ClusterFunctions.getCluster(GetClusterArgs.builder()
     *             .name("default")
     *             .build());
     * 
     *         // Assign a pipeline to that cluster
     *         var terraform_provider_buildkite = new Pipeline("terraform-provider-buildkite", PipelineArgs.builder()
     *             .name("terraform-provider-buildkite")
     *             .repository("git}{@literal @}{@code github.com:buildkite/terraform-provider-buildkite.git")
     *             .clusterId(default_.id())
     *             .build());
     * 
     *     }}{@code
     * }}{@code
     * }
     * </pre>
     * 
     */
    public static Output<GetClusterResult> getCluster(GetClusterArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("buildkite:Cluster/getCluster:getCluster", TypeShape.of(GetClusterResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve a cluster by name. You can find out more about clusters in the Buildkite [documentation](https://buildkite.com/docs/clusters/overview).
     * 
     * ## Example Usage
     * 
     * <pre>
     * {@code
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.buildkite.Cluster.ClusterFunctions;
     * import com.pulumi.buildkite.Cluster.inputs.GetClusterArgs;
     * import com.pulumi.buildkite.Pipeline.Pipeline;
     * import com.pulumi.buildkite.Pipeline.PipelineArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App }{{@code
     *     public static void main(String[] args) }{{@code
     *         Pulumi.run(App::stack);
     *     }}{@code
     * 
     *     public static void stack(Context ctx) }{{@code
     *         // Find the "default" cluster
     *         final var default = ClusterFunctions.getCluster(GetClusterArgs.builder()
     *             .name("default")
     *             .build());
     * 
     *         // Assign a pipeline to that cluster
     *         var terraform_provider_buildkite = new Pipeline("terraform-provider-buildkite", PipelineArgs.builder()
     *             .name("terraform-provider-buildkite")
     *             .repository("git}{@literal @}{@code github.com:buildkite/terraform-provider-buildkite.git")
     *             .clusterId(default_.id())
     *             .build());
     * 
     *     }}{@code
     * }}{@code
     * }
     * </pre>
     * 
     */
    public static CompletableFuture<GetClusterResult> getClusterPlain(GetClusterPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("buildkite:Cluster/getCluster:getCluster", TypeShape.of(GetClusterResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve clusters of an organization. You can find out more about clusters in the Buildkite
     * [documentation](https://buildkite.com/docs/agent/v3/clusters).
     * 
     */
    public static Output<GetClustersResult> getClusters() {
        return getClusters(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve clusters of an organization. You can find out more about clusters in the Buildkite
     * [documentation](https://buildkite.com/docs/agent/v3/clusters).
     * 
     */
    public static CompletableFuture<GetClustersResult> getClustersPlain() {
        return getClustersPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve clusters of an organization. You can find out more about clusters in the Buildkite
     * [documentation](https://buildkite.com/docs/agent/v3/clusters).
     * 
     */
    public static Output<GetClustersResult> getClusters(InvokeArgs args) {
        return getClusters(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve clusters of an organization. You can find out more about clusters in the Buildkite
     * [documentation](https://buildkite.com/docs/agent/v3/clusters).
     * 
     */
    public static CompletableFuture<GetClustersResult> getClustersPlain(InvokeArgs args) {
        return getClustersPlain(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve clusters of an organization. You can find out more about clusters in the Buildkite
     * [documentation](https://buildkite.com/docs/agent/v3/clusters).
     * 
     */
    public static Output<GetClustersResult> getClusters(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("buildkite:Cluster/getClusters:getClusters", TypeShape.of(GetClustersResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve clusters of an organization. You can find out more about clusters in the Buildkite
     * [documentation](https://buildkite.com/docs/agent/v3/clusters).
     * 
     */
    public static Output<GetClustersResult> getClusters(InvokeArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("buildkite:Cluster/getClusters:getClusters", TypeShape.of(GetClustersResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve clusters of an organization. You can find out more about clusters in the Buildkite
     * [documentation](https://buildkite.com/docs/agent/v3/clusters).
     * 
     */
    public static CompletableFuture<GetClustersResult> getClustersPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("buildkite:Cluster/getClusters:getClusters", TypeShape.of(GetClustersResult.class), args, Utilities.withVersion(options));
    }
}
