// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Cluster;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.buildkite.Cluster.ClusterDefaultQueueArgs;
import com.pulumiverse.buildkite.Cluster.inputs.ClusterDefaultQueueState;
import com.pulumiverse.buildkite.Utilities;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * This resource allows you to manage a default queue for a Buildkite Cluster.
 * Find out more information in our [documentation](https://buildkite.com/docs/clusters/overview).
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.buildkite.Cluster.Cluster;
 * import com.pulumi.buildkite.Cluster.ClusterArgs;
 * import com.pulumi.buildkite.Cluster.ClusterQueue;
 * import com.pulumi.buildkite.Cluster.ClusterQueueArgs;
 * import com.pulumi.buildkite.Cluster.ClusterDefaultQueue;
 * import com.pulumi.buildkite.Cluster.ClusterDefaultQueueArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // create a cluster
 *         var primary = new Cluster("primary", ClusterArgs.builder()
 *             .name("Primary cluster")
 *             .description("Runs the monolith build and deploy")
 *             .emoji("🚀")
 *             .color("#bada55")
 *             .build());
 * 
 *         var default_ = new ClusterQueue("default", ClusterQueueArgs.builder()
 *             .clusterId(primary.id())
 *             .key("default")
 *             .build());
 * 
 *         var primaryClusterDefaultQueue = new ClusterDefaultQueue("primaryClusterDefaultQueue", ClusterDefaultQueueArgs.builder()
 *             .clusterId(primary.id())
 *             .queueId(default_.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * Using `pulumi import`, import resources using the `id`. For example:
 * import a clusters default queue resource using the GraphQL ID of the cluster itself
 * 
 * you can use this query to find the ID:
 * query getClusters {
 * organization(slug: &#34;ORGANIZATION&#34;){
 * clusters(first: 5, order:NAME) {
 * edges{
 * node {
 * id
 * name
 * }
 * }
 * }
 * }
 * }
 * 
 * ```sh
 * $ pulumi import buildkite:Cluster/clusterDefaultQueue:ClusterDefaultQueue primary Q2x1c3Rlci0tLTI3ZmFmZjA4LTA3OWEtNDk5ZC1hMmIwLTIzNmY3NWFkMWZjYg==
 * ```
 * 
 */
@ResourceType(type="buildkite:Cluster/clusterDefaultQueue:ClusterDefaultQueue")
public class ClusterDefaultQueue extends com.pulumi.resources.CustomResource {
    /**
     * The GraphQL ID of the cluster to which to add a default queue.
     * 
     */
    @Export(name="clusterId", refs={String.class}, tree="[0]")
    private Output<String> clusterId;

    /**
     * @return The GraphQL ID of the cluster to which to add a default queue.
     * 
     */
    public Output<String> clusterId() {
        return this.clusterId;
    }
    /**
     * The Key for the cluster queue; its unique identifier
     * 
     */
    @Export(name="key", refs={String.class}, tree="[0]")
    private Output<String> key;

    /**
     * @return The Key for the cluster queue; its unique identifier
     * 
     */
    public Output<String> key() {
        return this.key;
    }
    /**
     * The GraphQL ID of the cluster queue to set as default on the cluster.
     * 
     */
    @Export(name="queueId", refs={String.class}, tree="[0]")
    private Output<String> queueId;

    /**
     * @return The GraphQL ID of the cluster queue to set as default on the cluster.
     * 
     */
    public Output<String> queueId() {
        return this.queueId;
    }
    /**
     * The UUID of the cluster.
     * 
     */
    @Export(name="uuid", refs={String.class}, tree="[0]")
    private Output<String> uuid;

    /**
     * @return The UUID of the cluster.
     * 
     */
    public Output<String> uuid() {
        return this.uuid;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ClusterDefaultQueue(java.lang.String name) {
        this(name, ClusterDefaultQueueArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ClusterDefaultQueue(java.lang.String name, ClusterDefaultQueueArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ClusterDefaultQueue(java.lang.String name, ClusterDefaultQueueArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("buildkite:Cluster/clusterDefaultQueue:ClusterDefaultQueue", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ClusterDefaultQueue(java.lang.String name, Output<java.lang.String> id, @Nullable ClusterDefaultQueueState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("buildkite:Cluster/clusterDefaultQueue:ClusterDefaultQueue", name, state, makeResourceOptions(options, id), false);
    }

    private static ClusterDefaultQueueArgs makeArgs(ClusterDefaultQueueArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ClusterDefaultQueueArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse/pulumi-buildkite")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ClusterDefaultQueue get(java.lang.String name, Output<java.lang.String> id, @Nullable ClusterDefaultQueueState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ClusterDefaultQueue(name, id, state, options);
    }
}
