// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Cluster;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterMaintainerArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterMaintainerArgs Empty = new ClusterMaintainerArgs();

    /**
     * The UUID of the cluster.
     * 
     */
    @Import(name="clusterUuid", required=true)
    private Output<String> clusterUuid;

    /**
     * @return The UUID of the cluster.
     * 
     */
    public Output<String> clusterUuid() {
        return this.clusterUuid;
    }

    /**
     * The UUID of the team to add as a maintainer. This is mutually exclusive with user*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     * 
     */
    @Import(name="teamUuid")
    private @Nullable Output<String> teamUuid;

    /**
     * @return The UUID of the team to add as a maintainer. This is mutually exclusive with user*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     * 
     */
    public Optional<Output<String>> teamUuid() {
        return Optional.ofNullable(this.teamUuid);
    }

    /**
     * The UUID of the user to add as a maintainer. This is mutually exclusive with team*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     * 
     */
    @Import(name="userUuid")
    private @Nullable Output<String> userUuid;

    /**
     * @return The UUID of the user to add as a maintainer. This is mutually exclusive with team*uuid.
     * Only one of user*uuid or teamUuid can be specified.
     * 
     */
    public Optional<Output<String>> userUuid() {
        return Optional.ofNullable(this.userUuid);
    }

    private ClusterMaintainerArgs() {}

    private ClusterMaintainerArgs(ClusterMaintainerArgs $) {
        this.clusterUuid = $.clusterUuid;
        this.teamUuid = $.teamUuid;
        this.userUuid = $.userUuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterMaintainerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterMaintainerArgs $;

        public Builder() {
            $ = new ClusterMaintainerArgs();
        }

        public Builder(ClusterMaintainerArgs defaults) {
            $ = new ClusterMaintainerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterUuid The UUID of the cluster.
         * 
         * @return builder
         * 
         */
        public Builder clusterUuid(Output<String> clusterUuid) {
            $.clusterUuid = clusterUuid;
            return this;
        }

        /**
         * @param clusterUuid The UUID of the cluster.
         * 
         * @return builder
         * 
         */
        public Builder clusterUuid(String clusterUuid) {
            return clusterUuid(Output.of(clusterUuid));
        }

        /**
         * @param teamUuid The UUID of the team to add as a maintainer. This is mutually exclusive with user*uuid.
         * Only one of user*uuid or teamUuid can be specified.
         * 
         * @return builder
         * 
         */
        public Builder teamUuid(@Nullable Output<String> teamUuid) {
            $.teamUuid = teamUuid;
            return this;
        }

        /**
         * @param teamUuid The UUID of the team to add as a maintainer. This is mutually exclusive with user*uuid.
         * Only one of user*uuid or teamUuid can be specified.
         * 
         * @return builder
         * 
         */
        public Builder teamUuid(String teamUuid) {
            return teamUuid(Output.of(teamUuid));
        }

        /**
         * @param userUuid The UUID of the user to add as a maintainer. This is mutually exclusive with team*uuid.
         * Only one of user*uuid or teamUuid can be specified.
         * 
         * @return builder
         * 
         */
        public Builder userUuid(@Nullable Output<String> userUuid) {
            $.userUuid = userUuid;
            return this;
        }

        /**
         * @param userUuid The UUID of the user to add as a maintainer. This is mutually exclusive with team*uuid.
         * Only one of user*uuid or teamUuid can be specified.
         * 
         * @return builder
         * 
         */
        public Builder userUuid(String userUuid) {
            return userUuid(Output.of(userUuid));
        }

        public ClusterMaintainerArgs build() {
            if ($.clusterUuid == null) {
                throw new MissingRequiredPropertyException("ClusterMaintainerArgs", "clusterUuid");
            }
            return $;
        }
    }

}
