// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Team.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTeamsTeam {
    /**
     * @return The default member role for new team members.
     * 
     */
    private String defaultMemberRole;
    /**
     * @return The description of the team.
     * 
     */
    private String description;
    /**
     * @return The GraphQL ID of the team.
     * 
     */
    private String id;
    /**
     * @return Whether this is the default team for the organization.
     * 
     */
    private Boolean isDefaultTeam;
    /**
     * @return Whether team members can create pipelines.
     * 
     */
    private Boolean membersCanCreatePipelines;
    /**
     * @return Whether team members can create registries.
     * 
     */
    private Boolean membersCanCreateRegistries;
    /**
     * @return Whether team members can create test suites.
     * 
     */
    private Boolean membersCanCreateSuites;
    /**
     * @return Whether team members can destroy packages.
     * 
     */
    private Boolean membersCanDestroyPackages;
    /**
     * @return Whether team members can destroy registries.
     * 
     */
    private Boolean membersCanDestroyRegistries;
    /**
     * @return The name of the team.
     * 
     */
    private String name;
    /**
     * @return The privacy setting of the team.
     * 
     */
    private String privacy;
    /**
     * @return The slug of the team.
     * 
     */
    private String slug;
    /**
     * @return The UUID of the team.
     * 
     */
    private String uuid;

    private GetTeamsTeam() {}
    /**
     * @return The default member role for new team members.
     * 
     */
    public String defaultMemberRole() {
        return this.defaultMemberRole;
    }
    /**
     * @return The description of the team.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The GraphQL ID of the team.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Whether this is the default team for the organization.
     * 
     */
    public Boolean isDefaultTeam() {
        return this.isDefaultTeam;
    }
    /**
     * @return Whether team members can create pipelines.
     * 
     */
    public Boolean membersCanCreatePipelines() {
        return this.membersCanCreatePipelines;
    }
    /**
     * @return Whether team members can create registries.
     * 
     */
    public Boolean membersCanCreateRegistries() {
        return this.membersCanCreateRegistries;
    }
    /**
     * @return Whether team members can create test suites.
     * 
     */
    public Boolean membersCanCreateSuites() {
        return this.membersCanCreateSuites;
    }
    /**
     * @return Whether team members can destroy packages.
     * 
     */
    public Boolean membersCanDestroyPackages() {
        return this.membersCanDestroyPackages;
    }
    /**
     * @return Whether team members can destroy registries.
     * 
     */
    public Boolean membersCanDestroyRegistries() {
        return this.membersCanDestroyRegistries;
    }
    /**
     * @return The name of the team.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The privacy setting of the team.
     * 
     */
    public String privacy() {
        return this.privacy;
    }
    /**
     * @return The slug of the team.
     * 
     */
    public String slug() {
        return this.slug;
    }
    /**
     * @return The UUID of the team.
     * 
     */
    public String uuid() {
        return this.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTeamsTeam defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String defaultMemberRole;
        private String description;
        private String id;
        private Boolean isDefaultTeam;
        private Boolean membersCanCreatePipelines;
        private Boolean membersCanCreateRegistries;
        private Boolean membersCanCreateSuites;
        private Boolean membersCanDestroyPackages;
        private Boolean membersCanDestroyRegistries;
        private String name;
        private String privacy;
        private String slug;
        private String uuid;
        public Builder() {}
        public Builder(GetTeamsTeam defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.defaultMemberRole = defaults.defaultMemberRole;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.isDefaultTeam = defaults.isDefaultTeam;
    	      this.membersCanCreatePipelines = defaults.membersCanCreatePipelines;
    	      this.membersCanCreateRegistries = defaults.membersCanCreateRegistries;
    	      this.membersCanCreateSuites = defaults.membersCanCreateSuites;
    	      this.membersCanDestroyPackages = defaults.membersCanDestroyPackages;
    	      this.membersCanDestroyRegistries = defaults.membersCanDestroyRegistries;
    	      this.name = defaults.name;
    	      this.privacy = defaults.privacy;
    	      this.slug = defaults.slug;
    	      this.uuid = defaults.uuid;
        }

        @CustomType.Setter
        public Builder defaultMemberRole(String defaultMemberRole) {
            if (defaultMemberRole == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "defaultMemberRole");
            }
            this.defaultMemberRole = defaultMemberRole;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder isDefaultTeam(Boolean isDefaultTeam) {
            if (isDefaultTeam == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "isDefaultTeam");
            }
            this.isDefaultTeam = isDefaultTeam;
            return this;
        }
        @CustomType.Setter
        public Builder membersCanCreatePipelines(Boolean membersCanCreatePipelines) {
            if (membersCanCreatePipelines == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "membersCanCreatePipelines");
            }
            this.membersCanCreatePipelines = membersCanCreatePipelines;
            return this;
        }
        @CustomType.Setter
        public Builder membersCanCreateRegistries(Boolean membersCanCreateRegistries) {
            if (membersCanCreateRegistries == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "membersCanCreateRegistries");
            }
            this.membersCanCreateRegistries = membersCanCreateRegistries;
            return this;
        }
        @CustomType.Setter
        public Builder membersCanCreateSuites(Boolean membersCanCreateSuites) {
            if (membersCanCreateSuites == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "membersCanCreateSuites");
            }
            this.membersCanCreateSuites = membersCanCreateSuites;
            return this;
        }
        @CustomType.Setter
        public Builder membersCanDestroyPackages(Boolean membersCanDestroyPackages) {
            if (membersCanDestroyPackages == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "membersCanDestroyPackages");
            }
            this.membersCanDestroyPackages = membersCanDestroyPackages;
            return this;
        }
        @CustomType.Setter
        public Builder membersCanDestroyRegistries(Boolean membersCanDestroyRegistries) {
            if (membersCanDestroyRegistries == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "membersCanDestroyRegistries");
            }
            this.membersCanDestroyRegistries = membersCanDestroyRegistries;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder privacy(String privacy) {
            if (privacy == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "privacy");
            }
            this.privacy = privacy;
            return this;
        }
        @CustomType.Setter
        public Builder slug(String slug) {
            if (slug == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "slug");
            }
            this.slug = slug;
            return this;
        }
        @CustomType.Setter
        public Builder uuid(String uuid) {
            if (uuid == null) {
              throw new MissingRequiredPropertyException("GetTeamsTeam", "uuid");
            }
            this.uuid = uuid;
            return this;
        }
        public GetTeamsTeam build() {
            final var _resultValue = new GetTeamsTeam();
            _resultValue.defaultMemberRole = defaultMemberRole;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.isDefaultTeam = isDefaultTeam;
            _resultValue.membersCanCreatePipelines = membersCanCreatePipelines;
            _resultValue.membersCanCreateRegistries = membersCanCreateRegistries;
            _resultValue.membersCanCreateSuites = membersCanCreateSuites;
            _resultValue.membersCanDestroyPackages = membersCanDestroyPackages;
            _resultValue.membersCanDestroyRegistries = membersCanDestroyRegistries;
            _resultValue.name = name;
            _resultValue.privacy = privacy;
            _resultValue.slug = slug;
            _resultValue.uuid = uuid;
            return _resultValue;
        }
    }
}
