// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This resource allows you to create and manage pipelines for repositories.
 *
 * More information on pipelines can be found in the [documentation](https://buildkite.com/docs/pipelines).
 *
 * > **Note:** When creating a new pipeline, the Buildkite API requires at least one team to be associated with it. You must use the 'default_team_id' attribute to specify this initial team. The 'buildkite_pipeline_team' resource can then be used to manage team access for existing pipelines.
 *
 * ## Import
 *
 * Using `pulumi import`, import resources using the `id`. For example:
 *
 * import a pipeline resource using the pipelines GraphQL ID
 *
 * GraphQL ID for a pipeline can be found on its settings page
 *
 * ```sh
 * $ pulumi import buildkite:Pipeline/pipeline:Pipeline pipeline UGlwZWxpbmUtLS00MzVjYWQ1OC1lODFkLTQ1YWYtODYzNy1iMWNmODA3MDIzOGQ=
 * ```
 */
export class Pipeline extends pulumi.CustomResource {
    /**
     * Get an existing Pipeline resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PipelineState, opts?: pulumi.CustomResourceOptions): Pipeline {
        return new Pipeline(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:Pipeline/pipeline:Pipeline';

    /**
     * Returns true if the given object is an instance of Pipeline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Pipeline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Pipeline.__pulumiType;
    }

    /**
     * Whether rebuilds are allowed for this pipeline.
     */
    declare public readonly allowRebuilds: pulumi.Output<boolean>;
    /**
     * The badge URL showing build state.
     */
    declare public /*out*/ readonly badgeUrl: pulumi.Output<string>;
    /**
     * Configure the pipeline to only build on this branch conditional.
     */
    declare public readonly branchConfiguration: pulumi.Output<string | undefined>;
    /**
     * Whether to cancel builds when a new commit is pushed to a matching branch.
     */
    declare public readonly cancelIntermediateBuilds: pulumi.Output<boolean>;
    /**
     * Filter the `cancelIntermediateBuilds` setting based on this branch condition.
     */
    declare public readonly cancelIntermediateBuildsBranchFilter: pulumi.Output<string>;
    /**
     * Attach this pipeline to the given cluster GraphQL ID.
     */
    declare public readonly clusterId: pulumi.Output<string | undefined>;
    /**
     * The name of the cluster the pipeline is (optionally) attached to.
     */
    declare public /*out*/ readonly clusterName: pulumi.Output<string>;
    /**
     * A color hex code to represent this pipeline.
     */
    declare public readonly color: pulumi.Output<string | undefined>;
    /**
     * Default branch of the pipeline.
     */
    declare public readonly defaultBranch: pulumi.Output<string>;
    /**
     * The GraphQL ID of a team to initially assign to the pipeline. This is required by the Buildkite API when creating a new pipeline. The team assigned here will be given 'Manage Build and Read' access. Further team associations can be managed with the `buildkite.Pipeline.Team` resource after the pipeline is created.
     */
    declare public readonly defaultTeamId: pulumi.Output<string | undefined>;
    /**
     * Set pipeline wide timeout for command steps.
     */
    declare public readonly defaultTimeoutInMinutes: pulumi.Output<number>;
    /**
     * Description for the pipeline. Can include emoji 🙌.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * An emoji that represents this pipeline.
     */
    declare public readonly emoji: pulumi.Output<string | undefined>;
    /**
     * Set pipeline wide maximum timeout for command steps.
     */
    declare public readonly maximumTimeoutInMinutes: pulumi.Output<number>;
    /**
     * Name to give the pipeline.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The GraphQL ID of the pipeline template applied to this pipeline.
     */
    declare public readonly pipelineTemplateId: pulumi.Output<string | undefined>;
    /**
     * Control settings depending on the VCS provider used in `repository`.
     */
    declare public readonly providerSettings: pulumi.Output<outputs.Pipeline.PipelineProviderSettings | undefined>;
    /**
     * URL to the repository this pipeline is configured for.
     */
    declare public readonly repository: pulumi.Output<string>;
    /**
     * Whether to skip queued builds if a new commit is pushed to a matching branch.
     */
    declare public readonly skipIntermediateBuilds: pulumi.Output<boolean>;
    /**
     * Filter the `skipIntermediateBuilds` setting based on this branch condition.
     */
    declare public readonly skipIntermediateBuildsBranchFilter: pulumi.Output<string>;
    /**
     * A custom identifier for the pipeline. If provided, this slug will be used as the pipeline's URL path instead of automatically converting the pipeline name. If not provided, the slug will be [derived](https://buildkite.com/docs/apis/graphql/cookbooks/pipelines#create-a-pipeline-deriving-a-pipeline-slug-from-the-pipelines-name) from the pipeline `name`.
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * The YAML steps to configure for the pipeline. Can also accept the `steps` attribute from the [`buildkite.Pipeline.getSignedSteps`](https://www.terraform.io/docs/data-sources/signed_pipeline_steps) data source to enable a signed pipeline. Defaults to `buildkite-agent pipeline upload`.
     */
    declare public readonly steps: pulumi.Output<string>;
    /**
     * Tags to attribute to the pipeline. Useful for searching by in the UI.
     */
    declare public readonly tags: pulumi.Output<string[]>;
    /**
     * The UUID of the pipeline.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;
    /**
     * The webhook URL used to trigger builds from VCS providers.
     */
    declare public /*out*/ readonly webhookUrl: pulumi.Output<string>;

    /**
     * Create a Pipeline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PipelineArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PipelineArgs | PipelineState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PipelineState | undefined;
            resourceInputs["allowRebuilds"] = state?.allowRebuilds;
            resourceInputs["badgeUrl"] = state?.badgeUrl;
            resourceInputs["branchConfiguration"] = state?.branchConfiguration;
            resourceInputs["cancelIntermediateBuilds"] = state?.cancelIntermediateBuilds;
            resourceInputs["cancelIntermediateBuildsBranchFilter"] = state?.cancelIntermediateBuildsBranchFilter;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["clusterName"] = state?.clusterName;
            resourceInputs["color"] = state?.color;
            resourceInputs["defaultBranch"] = state?.defaultBranch;
            resourceInputs["defaultTeamId"] = state?.defaultTeamId;
            resourceInputs["defaultTimeoutInMinutes"] = state?.defaultTimeoutInMinutes;
            resourceInputs["description"] = state?.description;
            resourceInputs["emoji"] = state?.emoji;
            resourceInputs["maximumTimeoutInMinutes"] = state?.maximumTimeoutInMinutes;
            resourceInputs["name"] = state?.name;
            resourceInputs["pipelineTemplateId"] = state?.pipelineTemplateId;
            resourceInputs["providerSettings"] = state?.providerSettings;
            resourceInputs["repository"] = state?.repository;
            resourceInputs["skipIntermediateBuilds"] = state?.skipIntermediateBuilds;
            resourceInputs["skipIntermediateBuildsBranchFilter"] = state?.skipIntermediateBuildsBranchFilter;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["steps"] = state?.steps;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["uuid"] = state?.uuid;
            resourceInputs["webhookUrl"] = state?.webhookUrl;
        } else {
            const args = argsOrState as PipelineArgs | undefined;
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["allowRebuilds"] = args?.allowRebuilds;
            resourceInputs["branchConfiguration"] = args?.branchConfiguration;
            resourceInputs["cancelIntermediateBuilds"] = args?.cancelIntermediateBuilds;
            resourceInputs["cancelIntermediateBuildsBranchFilter"] = args?.cancelIntermediateBuildsBranchFilter;
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["color"] = args?.color;
            resourceInputs["defaultBranch"] = args?.defaultBranch;
            resourceInputs["defaultTeamId"] = args?.defaultTeamId;
            resourceInputs["defaultTimeoutInMinutes"] = args?.defaultTimeoutInMinutes;
            resourceInputs["description"] = args?.description;
            resourceInputs["emoji"] = args?.emoji;
            resourceInputs["maximumTimeoutInMinutes"] = args?.maximumTimeoutInMinutes;
            resourceInputs["name"] = args?.name;
            resourceInputs["pipelineTemplateId"] = args?.pipelineTemplateId;
            resourceInputs["providerSettings"] = args?.providerSettings;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["skipIntermediateBuilds"] = args?.skipIntermediateBuilds;
            resourceInputs["skipIntermediateBuildsBranchFilter"] = args?.skipIntermediateBuildsBranchFilter;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["steps"] = args?.steps;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["badgeUrl"] = undefined /*out*/;
            resourceInputs["clusterName"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
            resourceInputs["webhookUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Pipeline.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Pipeline resources.
 */
export interface PipelineState {
    /**
     * Whether rebuilds are allowed for this pipeline.
     */
    allowRebuilds?: pulumi.Input<boolean>;
    /**
     * The badge URL showing build state.
     */
    badgeUrl?: pulumi.Input<string>;
    /**
     * Configure the pipeline to only build on this branch conditional.
     */
    branchConfiguration?: pulumi.Input<string>;
    /**
     * Whether to cancel builds when a new commit is pushed to a matching branch.
     */
    cancelIntermediateBuilds?: pulumi.Input<boolean>;
    /**
     * Filter the `cancelIntermediateBuilds` setting based on this branch condition.
     */
    cancelIntermediateBuildsBranchFilter?: pulumi.Input<string>;
    /**
     * Attach this pipeline to the given cluster GraphQL ID.
     */
    clusterId?: pulumi.Input<string>;
    /**
     * The name of the cluster the pipeline is (optionally) attached to.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * A color hex code to represent this pipeline.
     */
    color?: pulumi.Input<string>;
    /**
     * Default branch of the pipeline.
     */
    defaultBranch?: pulumi.Input<string>;
    /**
     * The GraphQL ID of a team to initially assign to the pipeline. This is required by the Buildkite API when creating a new pipeline. The team assigned here will be given 'Manage Build and Read' access. Further team associations can be managed with the `buildkite.Pipeline.Team` resource after the pipeline is created.
     */
    defaultTeamId?: pulumi.Input<string>;
    /**
     * Set pipeline wide timeout for command steps.
     */
    defaultTimeoutInMinutes?: pulumi.Input<number>;
    /**
     * Description for the pipeline. Can include emoji 🙌.
     */
    description?: pulumi.Input<string>;
    /**
     * An emoji that represents this pipeline.
     */
    emoji?: pulumi.Input<string>;
    /**
     * Set pipeline wide maximum timeout for command steps.
     */
    maximumTimeoutInMinutes?: pulumi.Input<number>;
    /**
     * Name to give the pipeline.
     */
    name?: pulumi.Input<string>;
    /**
     * The GraphQL ID of the pipeline template applied to this pipeline.
     */
    pipelineTemplateId?: pulumi.Input<string>;
    /**
     * Control settings depending on the VCS provider used in `repository`.
     */
    providerSettings?: pulumi.Input<inputs.Pipeline.PipelineProviderSettings>;
    /**
     * URL to the repository this pipeline is configured for.
     */
    repository?: pulumi.Input<string>;
    /**
     * Whether to skip queued builds if a new commit is pushed to a matching branch.
     */
    skipIntermediateBuilds?: pulumi.Input<boolean>;
    /**
     * Filter the `skipIntermediateBuilds` setting based on this branch condition.
     */
    skipIntermediateBuildsBranchFilter?: pulumi.Input<string>;
    /**
     * A custom identifier for the pipeline. If provided, this slug will be used as the pipeline's URL path instead of automatically converting the pipeline name. If not provided, the slug will be [derived](https://buildkite.com/docs/apis/graphql/cookbooks/pipelines#create-a-pipeline-deriving-a-pipeline-slug-from-the-pipelines-name) from the pipeline `name`.
     */
    slug?: pulumi.Input<string>;
    /**
     * The YAML steps to configure for the pipeline. Can also accept the `steps` attribute from the [`buildkite.Pipeline.getSignedSteps`](https://www.terraform.io/docs/data-sources/signed_pipeline_steps) data source to enable a signed pipeline. Defaults to `buildkite-agent pipeline upload`.
     */
    steps?: pulumi.Input<string>;
    /**
     * Tags to attribute to the pipeline. Useful for searching by in the UI.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The UUID of the pipeline.
     */
    uuid?: pulumi.Input<string>;
    /**
     * The webhook URL used to trigger builds from VCS providers.
     */
    webhookUrl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Pipeline resource.
 */
export interface PipelineArgs {
    /**
     * Whether rebuilds are allowed for this pipeline.
     */
    allowRebuilds?: pulumi.Input<boolean>;
    /**
     * Configure the pipeline to only build on this branch conditional.
     */
    branchConfiguration?: pulumi.Input<string>;
    /**
     * Whether to cancel builds when a new commit is pushed to a matching branch.
     */
    cancelIntermediateBuilds?: pulumi.Input<boolean>;
    /**
     * Filter the `cancelIntermediateBuilds` setting based on this branch condition.
     */
    cancelIntermediateBuildsBranchFilter?: pulumi.Input<string>;
    /**
     * Attach this pipeline to the given cluster GraphQL ID.
     */
    clusterId?: pulumi.Input<string>;
    /**
     * A color hex code to represent this pipeline.
     */
    color?: pulumi.Input<string>;
    /**
     * Default branch of the pipeline.
     */
    defaultBranch?: pulumi.Input<string>;
    /**
     * The GraphQL ID of a team to initially assign to the pipeline. This is required by the Buildkite API when creating a new pipeline. The team assigned here will be given 'Manage Build and Read' access. Further team associations can be managed with the `buildkite.Pipeline.Team` resource after the pipeline is created.
     */
    defaultTeamId?: pulumi.Input<string>;
    /**
     * Set pipeline wide timeout for command steps.
     */
    defaultTimeoutInMinutes?: pulumi.Input<number>;
    /**
     * Description for the pipeline. Can include emoji 🙌.
     */
    description?: pulumi.Input<string>;
    /**
     * An emoji that represents this pipeline.
     */
    emoji?: pulumi.Input<string>;
    /**
     * Set pipeline wide maximum timeout for command steps.
     */
    maximumTimeoutInMinutes?: pulumi.Input<number>;
    /**
     * Name to give the pipeline.
     */
    name?: pulumi.Input<string>;
    /**
     * The GraphQL ID of the pipeline template applied to this pipeline.
     */
    pipelineTemplateId?: pulumi.Input<string>;
    /**
     * Control settings depending on the VCS provider used in `repository`.
     */
    providerSettings?: pulumi.Input<inputs.Pipeline.PipelineProviderSettings>;
    /**
     * URL to the repository this pipeline is configured for.
     */
    repository: pulumi.Input<string>;
    /**
     * Whether to skip queued builds if a new commit is pushed to a matching branch.
     */
    skipIntermediateBuilds?: pulumi.Input<boolean>;
    /**
     * Filter the `skipIntermediateBuilds` setting based on this branch condition.
     */
    skipIntermediateBuildsBranchFilter?: pulumi.Input<string>;
    /**
     * A custom identifier for the pipeline. If provided, this slug will be used as the pipeline's URL path instead of automatically converting the pipeline name. If not provided, the slug will be [derived](https://buildkite.com/docs/apis/graphql/cookbooks/pipelines#create-a-pipeline-deriving-a-pipeline-slug-from-the-pipelines-name) from the pipeline `name`.
     */
    slug?: pulumi.Input<string>;
    /**
     * The YAML steps to configure for the pipeline. Can also accept the `steps` attribute from the [`buildkite.Pipeline.getSignedSteps`](https://www.terraform.io/docs/data-sources/signed_pipeline_steps) data source to enable a signed pipeline. Defaults to `buildkite-agent pipeline upload`.
     */
    steps?: pulumi.Input<string>;
    /**
     * Tags to attribute to the pipeline. Useful for searching by in the UI.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}
