// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Organization.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetMembersMember {
    /**
     * @return The email address of the organization member.
     * 
     */
    private String email;
    /**
     * @return The GraphQL ID of the organization member.
     * 
     */
    private String id;
    /**
     * @return The name of the organization member.
     * 
     */
    private String name;
    /**
     * @return The UUID of the organization member.
     * 
     */
    private String uuid;

    private GetMembersMember() {}
    /**
     * @return The email address of the organization member.
     * 
     */
    public String email() {
        return this.email;
    }
    /**
     * @return The GraphQL ID of the organization member.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the organization member.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The UUID of the organization member.
     * 
     */
    public String uuid() {
        return this.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMembersMember defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String email;
        private String id;
        private String name;
        private String uuid;
        public Builder() {}
        public Builder(GetMembersMember defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.email = defaults.email;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.uuid = defaults.uuid;
        }

        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("GetMembersMember", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetMembersMember", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetMembersMember", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder uuid(String uuid) {
            if (uuid == null) {
              throw new MissingRequiredPropertyException("GetMembersMember", "uuid");
            }
            this.uuid = uuid;
            return this;
        }
        public GetMembersMember build() {
            final var _resultValue = new GetMembersMember();
            _resultValue.email = email;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.uuid = uuid;
            return _resultValue;
        }
    }
}
