// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Use this data source to retrieve a specific organization member, using their email. You can find out more about organization members in the Buildkite
 * [documentation](https://buildkite.com/docs/platform/team-management).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as buildkite from "@pulumiverse/buildkite";
 *
 * const aSmith = buildkite.Organization.getMember({
 *     email: "a.smith@company.com",
 * });
 * const developers = new buildkite.team.Team("developers", {
 *     name: "Developers",
 *     privacy: "VISIBLE",
 *     defaultTeam: false,
 *     defaultMemberRole: "MEMBER",
 * });
 * const developersASmith = new buildkite.team.Member("developers_a_smith", {
 *     teamId: developers.id,
 *     userId: aSmith.then(aSmith => aSmith.id),
 *     role: "MEMBER",
 * });
 * ```
 */
export function getMember(args: GetMemberArgs, opts?: pulumi.InvokeOptions): Promise<GetMemberResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("buildkite:Organization/getMember:getMember", {
        "email": args.email,
    }, opts);
}

/**
 * A collection of arguments for invoking getMember.
 */
export interface GetMemberArgs {
    /**
     * The email address of the organization member.
     */
    email: string;
}

/**
 * A collection of values returned by getMember.
 */
export interface GetMemberResult {
    /**
     * The email address of the organization member.
     */
    readonly email: string;
    /**
     * The GraphQL ID of the organization member.
     */
    readonly id: string;
    /**
     * The name of the organization member.
     */
    readonly name: string;
    /**
     * The UUID of the organization member.
     */
    readonly uuid: string;
}
/**
 * Use this data source to retrieve a specific organization member, using their email. You can find out more about organization members in the Buildkite
 * [documentation](https://buildkite.com/docs/platform/team-management).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as buildkite from "@pulumiverse/buildkite";
 *
 * const aSmith = buildkite.Organization.getMember({
 *     email: "a.smith@company.com",
 * });
 * const developers = new buildkite.team.Team("developers", {
 *     name: "Developers",
 *     privacy: "VISIBLE",
 *     defaultTeam: false,
 *     defaultMemberRole: "MEMBER",
 * });
 * const developersASmith = new buildkite.team.Member("developers_a_smith", {
 *     teamId: developers.id,
 *     userId: aSmith.then(aSmith => aSmith.id),
 *     role: "MEMBER",
 * });
 * ```
 */
export function getMemberOutput(args: GetMemberOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMemberResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("buildkite:Organization/getMember:getMember", {
        "email": args.email,
    }, opts);
}

/**
 * A collection of arguments for invoking getMember.
 */
export interface GetMemberOutputArgs {
    /**
     * The email address of the organization member.
     */
    email: pulumi.Input<string>;
}
