// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Pipeline.Inputs
{

    public sealed class PipelineProviderSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to create builds when branches are pushed.
        /// </summary>
        [Input("buildBranches")]
        public Input<bool>? BuildBranches { get; set; }

        /// <summary>
        /// Whether to create builds for pull requests from third-party forks.
        /// </summary>
        [Input("buildPullRequestForks")]
        public Input<bool>? BuildPullRequestForks { get; set; }

        /// <summary>
        /// Whether to create builds for pull requests when labels are added or removed.
        /// </summary>
        [Input("buildPullRequestLabelsChanged")]
        public Input<bool>? BuildPullRequestLabelsChanged { get; set; }

        [Input("buildPullRequestReadyForReview")]
        public Input<bool>? BuildPullRequestReadyForReview { get; set; }

        /// <summary>
        /// Whether to create builds for commits that are part of a Pull Request.
        /// </summary>
        [Input("buildPullRequests")]
        public Input<bool>? BuildPullRequests { get; set; }

        /// <summary>
        /// Whether to create builds when tags are pushed.
        /// 
        /// Properties available for Bitbucket Cloud, GitHub, and GitHub Enterprise:
        /// </summary>
        [Input("buildTags")]
        public Input<bool>? BuildTags { get; set; }

        /// <summary>
        /// A boolean to enable automatically cancelling any running builds for a branch if the branch is deleted.
        /// 
        /// Additional properties available for GitHub:
        /// </summary>
        [Input("cancelDeletedBranchBuilds")]
        public Input<bool>? CancelDeletedBranchBuilds { get; set; }

        /// <summary>
        /// The condition to evaluate when deciding if a build should run. More details available in [the documentation](https://buildkite.com/docs/pipelines/conditionals#conditionals-in-pipelines)
        /// </summary>
        [Input("filterCondition")]
        public Input<string>? FilterCondition { get; set; }

        /// <summary>
        /// [true/false] Whether to filter builds to only run when the condition in `filter_condition` is true
        /// </summary>
        [Input("filterEnabled")]
        public Input<bool>? FilterEnabled { get; set; }

        /// <summary>
        /// Prefix branch names for third-party fork builds to ensure they don't trigger branch conditions. For example, the `master` branch from `some-user` will become `some-user:master`.
        /// </summary>
        [Input("prefixPullRequestForkBranchNames")]
        public Input<bool>? PrefixPullRequestForkBranchNames { get; set; }

        /// <summary>
        /// The status to use for blocked builds. Pending can be used with [required status checks](https://help.github.com/en/articles/enabling-required-status-checks) to prevent merging pull requests with blocked builds.
        /// </summary>
        [Input("publishBlockedAsPending")]
        public Input<bool>? PublishBlockedAsPending { get; set; }

        /// <summary>
        /// Whether to update the status of commits in Bitbucket or GitHub.
        /// </summary>
        [Input("publishCommitStatus")]
        public Input<bool>? PublishCommitStatus { get; set; }

        /// <summary>
        /// Whether to create a separate status for each job in a build, allowing you to see the status of each job directly in Bitbucket or GitHub.
        /// </summary>
        [Input("publishCommitStatusPerStep")]
        public Input<bool>? PublishCommitStatusPerStep { get; set; }

        /// <summary>
        /// The branch filtering pattern. Only pull requests on branches matching this pattern will cause builds to be created.
        /// </summary>
        [Input("pullRequestBranchFilterConfiguration")]
        public Input<string>? PullRequestBranchFilterConfiguration { get; set; }

        /// <summary>
        /// Whether to limit the creation of builds to specific branches or patterns.
        /// </summary>
        [Input("pullRequestBranchFilterEnabled")]
        public Input<bool>? PullRequestBranchFilterEnabled { get; set; }

        /// <summary>
        /// Whether to create a separate status for pull request builds, allowing you to require a passing pull request build in your [required status checks](https://help.github.com/en/articles/enabling-required-status-checks) in GitHub.
        /// </summary>
        [Input("separatePullRequestStatuses")]
        public Input<bool>? SeparatePullRequestStatuses { get; set; }

        /// <summary>
        /// Whether to skip creating a new build for a pull request if an existing build for the commit and branch already exists.
        /// </summary>
        [Input("skipPullRequestBuildsForExistingCommits")]
        public Input<bool>? SkipPullRequestBuildsForExistingCommits { get; set; }

        /// <summary>
        /// What type of event to trigger builds on. Must be one of:
        /// </summary>
        [Input("triggerMode")]
        public Input<string>? TriggerMode { get; set; }

        public PipelineProviderSettingsArgs()
        {
        }
        public static new PipelineProviderSettingsArgs Empty => new PipelineProviderSettingsArgs();
    }
}
