// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Buildkite.Organization.Outputs
{

    [OutputType]
    public sealed class GetPortalsPortalResult
    {
        /// <summary>
        /// Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal.
        /// </summary>
        public readonly string AllowedIpAddresses;
        /// <summary>
        /// The time when the portal was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Information about the user who created the portal.
        /// </summary>
        public readonly Outputs.GetPortalsPortalCreatedByResult CreatedBy;
        /// <summary>
        /// The description of the portal.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The name of the portal.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The GraphQL query that the portal executes.
        /// </summary>
        public readonly string Query;
        /// <summary>
        /// The slug of the portal.
        /// </summary>
        public readonly string Slug;
        /// <summary>
        /// Whether users can invoke the portal.
        /// </summary>
        public readonly bool UserInvokable;
        /// <summary>
        /// The UUID of the portal.
        /// </summary>
        public readonly string Uuid;

        [OutputConstructor]
        private GetPortalsPortalResult(
            string allowedIpAddresses,

            string createdAt,

            Outputs.GetPortalsPortalCreatedByResult createdBy,

            string description,

            string name,

            string query,

            string slug,

            bool userInvokable,

            string uuid)
        {
            AllowedIpAddresses = allowedIpAddresses;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Description = description;
            Name = name;
            Query = query;
            Slug = slug;
            UserInvokable = userInvokable;
            Uuid = uuid;
        }
    }
}
