// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cluster

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/internal"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/cluster"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := cluster.NewClusterSecret(ctx, "example", &cluster.ClusterSecretArgs{
//				ClusterId:   pulumi.String("01234567-89ab-cdef-0123-456789abcdef"),
//				Key:         pulumi.String("DATABASE_PASSWORD"),
//				Value:       pulumi.String("super-secret-password"),
//				Description: pulumi.String("Production database password"),
//				Policy:      pulumi.String("- pipeline_slug: my-pipeline\n  build_branch: main\n"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Using `pulumi import`, import resources using the `id`. For example:
//
// Import a cluster secret using {cluster_id}/{secret_id}
//
// You can find the cluster_id under cluster settings in the UI
//
// and find the secret_id from the secrets list using the
//
// REST API response from:
//
// GET /v2/organizations/{org_slug}/clusters/{cluster_id}/secrets
//
// ```sh
// $ pulumi import buildkite:Cluster/clusterSecret:ClusterSecret example 01234567-89ab-cdef-0123-456789abcdef/fedcba98-7654-3210-fedc-ba9876543210
// ```
type ClusterSecret struct {
	pulumi.CustomResourceState

	// The UUID of the cluster this secret belongs to.
	ClusterId pulumi.StringOutput `pulumi:"clusterId"`
	// The time when the secret was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// A description of what this secret is for.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters.
	Key pulumi.StringOutput `pulumi:"key"`
	// YAML access policy defining which pipelines and branches can access this secret.
	Policy pulumi.StringPtrOutput `pulumi:"policy"`
	// The time when the secret was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The secret value. Must be less than 8KB.
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewClusterSecret registers a new resource with the given unique name, arguments, and options.
func NewClusterSecret(ctx *pulumi.Context,
	name string, args *ClusterSecretArgs, opts ...pulumi.ResourceOption) (*ClusterSecret, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterId == nil {
		return nil, errors.New("invalid value for required argument 'ClusterId'")
	}
	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	if args.Value != nil {
		args.Value = pulumi.ToSecret(args.Value).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"value",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ClusterSecret
	err := ctx.RegisterResource("buildkite:Cluster/clusterSecret:ClusterSecret", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetClusterSecret gets an existing ClusterSecret resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetClusterSecret(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClusterSecretState, opts ...pulumi.ResourceOption) (*ClusterSecret, error) {
	var resource ClusterSecret
	err := ctx.ReadResource("buildkite:Cluster/clusterSecret:ClusterSecret", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ClusterSecret resources.
type clusterSecretState struct {
	// The UUID of the cluster this secret belongs to.
	ClusterId *string `pulumi:"clusterId"`
	// The time when the secret was created.
	CreatedAt *string `pulumi:"createdAt"`
	// A description of what this secret is for.
	Description *string `pulumi:"description"`
	// The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters.
	Key *string `pulumi:"key"`
	// YAML access policy defining which pipelines and branches can access this secret.
	Policy *string `pulumi:"policy"`
	// The time when the secret was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
	// The secret value. Must be less than 8KB.
	Value *string `pulumi:"value"`
}

type ClusterSecretState struct {
	// The UUID of the cluster this secret belongs to.
	ClusterId pulumi.StringPtrInput
	// The time when the secret was created.
	CreatedAt pulumi.StringPtrInput
	// A description of what this secret is for.
	Description pulumi.StringPtrInput
	// The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters.
	Key pulumi.StringPtrInput
	// YAML access policy defining which pipelines and branches can access this secret.
	Policy pulumi.StringPtrInput
	// The time when the secret was last updated.
	UpdatedAt pulumi.StringPtrInput
	// The secret value. Must be less than 8KB.
	Value pulumi.StringPtrInput
}

func (ClusterSecretState) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterSecretState)(nil)).Elem()
}

type clusterSecretArgs struct {
	// The UUID of the cluster this secret belongs to.
	ClusterId string `pulumi:"clusterId"`
	// A description of what this secret is for.
	Description *string `pulumi:"description"`
	// The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters.
	Key string `pulumi:"key"`
	// YAML access policy defining which pipelines and branches can access this secret.
	Policy *string `pulumi:"policy"`
	// The secret value. Must be less than 8KB.
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a ClusterSecret resource.
type ClusterSecretArgs struct {
	// The UUID of the cluster this secret belongs to.
	ClusterId pulumi.StringInput
	// A description of what this secret is for.
	Description pulumi.StringPtrInput
	// The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters.
	Key pulumi.StringInput
	// YAML access policy defining which pipelines and branches can access this secret.
	Policy pulumi.StringPtrInput
	// The secret value. Must be less than 8KB.
	Value pulumi.StringInput
}

func (ClusterSecretArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterSecretArgs)(nil)).Elem()
}

type ClusterSecretInput interface {
	pulumi.Input

	ToClusterSecretOutput() ClusterSecretOutput
	ToClusterSecretOutputWithContext(ctx context.Context) ClusterSecretOutput
}

func (*ClusterSecret) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterSecret)(nil)).Elem()
}

func (i *ClusterSecret) ToClusterSecretOutput() ClusterSecretOutput {
	return i.ToClusterSecretOutputWithContext(context.Background())
}

func (i *ClusterSecret) ToClusterSecretOutputWithContext(ctx context.Context) ClusterSecretOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterSecretOutput)
}

// ClusterSecretArrayInput is an input type that accepts ClusterSecretArray and ClusterSecretArrayOutput values.
// You can construct a concrete instance of `ClusterSecretArrayInput` via:
//
//	ClusterSecretArray{ ClusterSecretArgs{...} }
type ClusterSecretArrayInput interface {
	pulumi.Input

	ToClusterSecretArrayOutput() ClusterSecretArrayOutput
	ToClusterSecretArrayOutputWithContext(context.Context) ClusterSecretArrayOutput
}

type ClusterSecretArray []ClusterSecretInput

func (ClusterSecretArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClusterSecret)(nil)).Elem()
}

func (i ClusterSecretArray) ToClusterSecretArrayOutput() ClusterSecretArrayOutput {
	return i.ToClusterSecretArrayOutputWithContext(context.Background())
}

func (i ClusterSecretArray) ToClusterSecretArrayOutputWithContext(ctx context.Context) ClusterSecretArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterSecretArrayOutput)
}

// ClusterSecretMapInput is an input type that accepts ClusterSecretMap and ClusterSecretMapOutput values.
// You can construct a concrete instance of `ClusterSecretMapInput` via:
//
//	ClusterSecretMap{ "key": ClusterSecretArgs{...} }
type ClusterSecretMapInput interface {
	pulumi.Input

	ToClusterSecretMapOutput() ClusterSecretMapOutput
	ToClusterSecretMapOutputWithContext(context.Context) ClusterSecretMapOutput
}

type ClusterSecretMap map[string]ClusterSecretInput

func (ClusterSecretMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClusterSecret)(nil)).Elem()
}

func (i ClusterSecretMap) ToClusterSecretMapOutput() ClusterSecretMapOutput {
	return i.ToClusterSecretMapOutputWithContext(context.Background())
}

func (i ClusterSecretMap) ToClusterSecretMapOutputWithContext(ctx context.Context) ClusterSecretMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterSecretMapOutput)
}

type ClusterSecretOutput struct{ *pulumi.OutputState }

func (ClusterSecretOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterSecret)(nil)).Elem()
}

func (o ClusterSecretOutput) ToClusterSecretOutput() ClusterSecretOutput {
	return o
}

func (o ClusterSecretOutput) ToClusterSecretOutputWithContext(ctx context.Context) ClusterSecretOutput {
	return o
}

// The UUID of the cluster this secret belongs to.
func (o ClusterSecretOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterSecret) pulumi.StringOutput { return v.ClusterId }).(pulumi.StringOutput)
}

// The time when the secret was created.
func (o ClusterSecretOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterSecret) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// A description of what this secret is for.
func (o ClusterSecretOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterSecret) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The key name for the secret. Must start with a letter and only contain letters, numbers, and underscores. Maximum 255 characters.
func (o ClusterSecretOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterSecret) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

// YAML access policy defining which pipelines and branches can access this secret.
func (o ClusterSecretOutput) Policy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterSecret) pulumi.StringPtrOutput { return v.Policy }).(pulumi.StringPtrOutput)
}

// The time when the secret was last updated.
func (o ClusterSecretOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterSecret) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The secret value. Must be less than 8KB.
func (o ClusterSecretOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterSecret) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

type ClusterSecretArrayOutput struct{ *pulumi.OutputState }

func (ClusterSecretArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClusterSecret)(nil)).Elem()
}

func (o ClusterSecretArrayOutput) ToClusterSecretArrayOutput() ClusterSecretArrayOutput {
	return o
}

func (o ClusterSecretArrayOutput) ToClusterSecretArrayOutputWithContext(ctx context.Context) ClusterSecretArrayOutput {
	return o
}

func (o ClusterSecretArrayOutput) Index(i pulumi.IntInput) ClusterSecretOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ClusterSecret {
		return vs[0].([]*ClusterSecret)[vs[1].(int)]
	}).(ClusterSecretOutput)
}

type ClusterSecretMapOutput struct{ *pulumi.OutputState }

func (ClusterSecretMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClusterSecret)(nil)).Elem()
}

func (o ClusterSecretMapOutput) ToClusterSecretMapOutput() ClusterSecretMapOutput {
	return o
}

func (o ClusterSecretMapOutput) ToClusterSecretMapOutputWithContext(ctx context.Context) ClusterSecretMapOutput {
	return o
}

func (o ClusterSecretMapOutput) MapIndex(k pulumi.StringInput) ClusterSecretOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ClusterSecret {
		return vs[0].(map[string]*ClusterSecret)[vs[1].(string)]
	}).(ClusterSecretOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterSecretInput)(nil)).Elem(), &ClusterSecret{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterSecretArrayInput)(nil)).Elem(), ClusterSecretArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterSecretMapInput)(nil)).Elem(), ClusterSecretMap{})
	pulumi.RegisterOutputType(ClusterSecretOutput{})
	pulumi.RegisterOutputType(ClusterSecretArrayOutput{})
	pulumi.RegisterOutputType(ClusterSecretMapOutput{})
}
