// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cluster

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/internal"
)

var _ = internal.GetEnvOrDefault

type ClusterQueueHostedAgents struct {
	// The instance shape to use for the Hosted Agent cluster queue. This can be a MacOS instance shape or a Linux instance shape.
	// Valid values are:
	// - MACOS_ARM64_M4_6X28
	// - MACOS_ARM64_M4_12X56
	// - LINUX_AMD64_2X4
	// - LINUX_AMD64_4X16
	// - LINUX_AMD64_8X32
	// - LINUX_AMD64_16X64
	// - LINUX_ARM64_2X4
	// - LINUX_ARM64_4X16
	// - LINUX_ARM64_8X32
	// - LINUX_ARM64_16X64
	InstanceShape string                         `pulumi:"instanceShape"`
	Linux         *ClusterQueueHostedAgentsLinux `pulumi:"linux"`
	Mac           *ClusterQueueHostedAgentsMac   `pulumi:"mac"`
}

// ClusterQueueHostedAgentsInput is an input type that accepts ClusterQueueHostedAgentsArgs and ClusterQueueHostedAgentsOutput values.
// You can construct a concrete instance of `ClusterQueueHostedAgentsInput` via:
//
//	ClusterQueueHostedAgentsArgs{...}
type ClusterQueueHostedAgentsInput interface {
	pulumi.Input

	ToClusterQueueHostedAgentsOutput() ClusterQueueHostedAgentsOutput
	ToClusterQueueHostedAgentsOutputWithContext(context.Context) ClusterQueueHostedAgentsOutput
}

type ClusterQueueHostedAgentsArgs struct {
	// The instance shape to use for the Hosted Agent cluster queue. This can be a MacOS instance shape or a Linux instance shape.
	// Valid values are:
	// - MACOS_ARM64_M4_6X28
	// - MACOS_ARM64_M4_12X56
	// - LINUX_AMD64_2X4
	// - LINUX_AMD64_4X16
	// - LINUX_AMD64_8X32
	// - LINUX_AMD64_16X64
	// - LINUX_ARM64_2X4
	// - LINUX_ARM64_4X16
	// - LINUX_ARM64_8X32
	// - LINUX_ARM64_16X64
	InstanceShape pulumi.StringInput                    `pulumi:"instanceShape"`
	Linux         ClusterQueueHostedAgentsLinuxPtrInput `pulumi:"linux"`
	Mac           ClusterQueueHostedAgentsMacPtrInput   `pulumi:"mac"`
}

func (ClusterQueueHostedAgentsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterQueueHostedAgents)(nil)).Elem()
}

func (i ClusterQueueHostedAgentsArgs) ToClusterQueueHostedAgentsOutput() ClusterQueueHostedAgentsOutput {
	return i.ToClusterQueueHostedAgentsOutputWithContext(context.Background())
}

func (i ClusterQueueHostedAgentsArgs) ToClusterQueueHostedAgentsOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsOutput)
}

func (i ClusterQueueHostedAgentsArgs) ToClusterQueueHostedAgentsPtrOutput() ClusterQueueHostedAgentsPtrOutput {
	return i.ToClusterQueueHostedAgentsPtrOutputWithContext(context.Background())
}

func (i ClusterQueueHostedAgentsArgs) ToClusterQueueHostedAgentsPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsOutput).ToClusterQueueHostedAgentsPtrOutputWithContext(ctx)
}

// ClusterQueueHostedAgentsPtrInput is an input type that accepts ClusterQueueHostedAgentsArgs, ClusterQueueHostedAgentsPtr and ClusterQueueHostedAgentsPtrOutput values.
// You can construct a concrete instance of `ClusterQueueHostedAgentsPtrInput` via:
//
//	        ClusterQueueHostedAgentsArgs{...}
//
//	or:
//
//	        nil
type ClusterQueueHostedAgentsPtrInput interface {
	pulumi.Input

	ToClusterQueueHostedAgentsPtrOutput() ClusterQueueHostedAgentsPtrOutput
	ToClusterQueueHostedAgentsPtrOutputWithContext(context.Context) ClusterQueueHostedAgentsPtrOutput
}

type clusterQueueHostedAgentsPtrType ClusterQueueHostedAgentsArgs

func ClusterQueueHostedAgentsPtr(v *ClusterQueueHostedAgentsArgs) ClusterQueueHostedAgentsPtrInput {
	return (*clusterQueueHostedAgentsPtrType)(v)
}

func (*clusterQueueHostedAgentsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterQueueHostedAgents)(nil)).Elem()
}

func (i *clusterQueueHostedAgentsPtrType) ToClusterQueueHostedAgentsPtrOutput() ClusterQueueHostedAgentsPtrOutput {
	return i.ToClusterQueueHostedAgentsPtrOutputWithContext(context.Background())
}

func (i *clusterQueueHostedAgentsPtrType) ToClusterQueueHostedAgentsPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsPtrOutput)
}

type ClusterQueueHostedAgentsOutput struct{ *pulumi.OutputState }

func (ClusterQueueHostedAgentsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterQueueHostedAgents)(nil)).Elem()
}

func (o ClusterQueueHostedAgentsOutput) ToClusterQueueHostedAgentsOutput() ClusterQueueHostedAgentsOutput {
	return o
}

func (o ClusterQueueHostedAgentsOutput) ToClusterQueueHostedAgentsOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsOutput {
	return o
}

func (o ClusterQueueHostedAgentsOutput) ToClusterQueueHostedAgentsPtrOutput() ClusterQueueHostedAgentsPtrOutput {
	return o.ToClusterQueueHostedAgentsPtrOutputWithContext(context.Background())
}

func (o ClusterQueueHostedAgentsOutput) ToClusterQueueHostedAgentsPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ClusterQueueHostedAgents) *ClusterQueueHostedAgents {
		return &v
	}).(ClusterQueueHostedAgentsPtrOutput)
}

// The instance shape to use for the Hosted Agent cluster queue. This can be a MacOS instance shape or a Linux instance shape.
// Valid values are:
// - MACOS_ARM64_M4_6X28
// - MACOS_ARM64_M4_12X56
// - LINUX_AMD64_2X4
// - LINUX_AMD64_4X16
// - LINUX_AMD64_8X32
// - LINUX_AMD64_16X64
// - LINUX_ARM64_2X4
// - LINUX_ARM64_4X16
// - LINUX_ARM64_8X32
// - LINUX_ARM64_16X64
func (o ClusterQueueHostedAgentsOutput) InstanceShape() pulumi.StringOutput {
	return o.ApplyT(func(v ClusterQueueHostedAgents) string { return v.InstanceShape }).(pulumi.StringOutput)
}

func (o ClusterQueueHostedAgentsOutput) Linux() ClusterQueueHostedAgentsLinuxPtrOutput {
	return o.ApplyT(func(v ClusterQueueHostedAgents) *ClusterQueueHostedAgentsLinux { return v.Linux }).(ClusterQueueHostedAgentsLinuxPtrOutput)
}

func (o ClusterQueueHostedAgentsOutput) Mac() ClusterQueueHostedAgentsMacPtrOutput {
	return o.ApplyT(func(v ClusterQueueHostedAgents) *ClusterQueueHostedAgentsMac { return v.Mac }).(ClusterQueueHostedAgentsMacPtrOutput)
}

type ClusterQueueHostedAgentsPtrOutput struct{ *pulumi.OutputState }

func (ClusterQueueHostedAgentsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterQueueHostedAgents)(nil)).Elem()
}

func (o ClusterQueueHostedAgentsPtrOutput) ToClusterQueueHostedAgentsPtrOutput() ClusterQueueHostedAgentsPtrOutput {
	return o
}

func (o ClusterQueueHostedAgentsPtrOutput) ToClusterQueueHostedAgentsPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsPtrOutput {
	return o
}

func (o ClusterQueueHostedAgentsPtrOutput) Elem() ClusterQueueHostedAgentsOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgents) ClusterQueueHostedAgents {
		if v != nil {
			return *v
		}
		var ret ClusterQueueHostedAgents
		return ret
	}).(ClusterQueueHostedAgentsOutput)
}

// The instance shape to use for the Hosted Agent cluster queue. This can be a MacOS instance shape or a Linux instance shape.
// Valid values are:
// - MACOS_ARM64_M4_6X28
// - MACOS_ARM64_M4_12X56
// - LINUX_AMD64_2X4
// - LINUX_AMD64_4X16
// - LINUX_AMD64_8X32
// - LINUX_AMD64_16X64
// - LINUX_ARM64_2X4
// - LINUX_ARM64_4X16
// - LINUX_ARM64_8X32
// - LINUX_ARM64_16X64
func (o ClusterQueueHostedAgentsPtrOutput) InstanceShape() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgents) *string {
		if v == nil {
			return nil
		}
		return &v.InstanceShape
	}).(pulumi.StringPtrOutput)
}

func (o ClusterQueueHostedAgentsPtrOutput) Linux() ClusterQueueHostedAgentsLinuxPtrOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgents) *ClusterQueueHostedAgentsLinux {
		if v == nil {
			return nil
		}
		return v.Linux
	}).(ClusterQueueHostedAgentsLinuxPtrOutput)
}

func (o ClusterQueueHostedAgentsPtrOutput) Mac() ClusterQueueHostedAgentsMacPtrOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgents) *ClusterQueueHostedAgentsMac {
		if v == nil {
			return nil
		}
		return v.Mac
	}).(ClusterQueueHostedAgentsMacPtrOutput)
}

type ClusterQueueHostedAgentsLinux struct {
	// A URL reference to a container image that will be used for jobs running within the queue. This URL is required to be publicly available, or pushed to the internal registry available within the cluster. Please note that this value is currently experimental and in preview. Please contact support@buildkite.com to enable this functionality for your organization.
	AgentImageRef string `pulumi:"agentImageRef"`
}

// ClusterQueueHostedAgentsLinuxInput is an input type that accepts ClusterQueueHostedAgentsLinuxArgs and ClusterQueueHostedAgentsLinuxOutput values.
// You can construct a concrete instance of `ClusterQueueHostedAgentsLinuxInput` via:
//
//	ClusterQueueHostedAgentsLinuxArgs{...}
type ClusterQueueHostedAgentsLinuxInput interface {
	pulumi.Input

	ToClusterQueueHostedAgentsLinuxOutput() ClusterQueueHostedAgentsLinuxOutput
	ToClusterQueueHostedAgentsLinuxOutputWithContext(context.Context) ClusterQueueHostedAgentsLinuxOutput
}

type ClusterQueueHostedAgentsLinuxArgs struct {
	// A URL reference to a container image that will be used for jobs running within the queue. This URL is required to be publicly available, or pushed to the internal registry available within the cluster. Please note that this value is currently experimental and in preview. Please contact support@buildkite.com to enable this functionality for your organization.
	AgentImageRef pulumi.StringInput `pulumi:"agentImageRef"`
}

func (ClusterQueueHostedAgentsLinuxArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterQueueHostedAgentsLinux)(nil)).Elem()
}

func (i ClusterQueueHostedAgentsLinuxArgs) ToClusterQueueHostedAgentsLinuxOutput() ClusterQueueHostedAgentsLinuxOutput {
	return i.ToClusterQueueHostedAgentsLinuxOutputWithContext(context.Background())
}

func (i ClusterQueueHostedAgentsLinuxArgs) ToClusterQueueHostedAgentsLinuxOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsLinuxOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsLinuxOutput)
}

func (i ClusterQueueHostedAgentsLinuxArgs) ToClusterQueueHostedAgentsLinuxPtrOutput() ClusterQueueHostedAgentsLinuxPtrOutput {
	return i.ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(context.Background())
}

func (i ClusterQueueHostedAgentsLinuxArgs) ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsLinuxPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsLinuxOutput).ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(ctx)
}

// ClusterQueueHostedAgentsLinuxPtrInput is an input type that accepts ClusterQueueHostedAgentsLinuxArgs, ClusterQueueHostedAgentsLinuxPtr and ClusterQueueHostedAgentsLinuxPtrOutput values.
// You can construct a concrete instance of `ClusterQueueHostedAgentsLinuxPtrInput` via:
//
//	        ClusterQueueHostedAgentsLinuxArgs{...}
//
//	or:
//
//	        nil
type ClusterQueueHostedAgentsLinuxPtrInput interface {
	pulumi.Input

	ToClusterQueueHostedAgentsLinuxPtrOutput() ClusterQueueHostedAgentsLinuxPtrOutput
	ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(context.Context) ClusterQueueHostedAgentsLinuxPtrOutput
}

type clusterQueueHostedAgentsLinuxPtrType ClusterQueueHostedAgentsLinuxArgs

func ClusterQueueHostedAgentsLinuxPtr(v *ClusterQueueHostedAgentsLinuxArgs) ClusterQueueHostedAgentsLinuxPtrInput {
	return (*clusterQueueHostedAgentsLinuxPtrType)(v)
}

func (*clusterQueueHostedAgentsLinuxPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterQueueHostedAgentsLinux)(nil)).Elem()
}

func (i *clusterQueueHostedAgentsLinuxPtrType) ToClusterQueueHostedAgentsLinuxPtrOutput() ClusterQueueHostedAgentsLinuxPtrOutput {
	return i.ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(context.Background())
}

func (i *clusterQueueHostedAgentsLinuxPtrType) ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsLinuxPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsLinuxPtrOutput)
}

type ClusterQueueHostedAgentsLinuxOutput struct{ *pulumi.OutputState }

func (ClusterQueueHostedAgentsLinuxOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterQueueHostedAgentsLinux)(nil)).Elem()
}

func (o ClusterQueueHostedAgentsLinuxOutput) ToClusterQueueHostedAgentsLinuxOutput() ClusterQueueHostedAgentsLinuxOutput {
	return o
}

func (o ClusterQueueHostedAgentsLinuxOutput) ToClusterQueueHostedAgentsLinuxOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsLinuxOutput {
	return o
}

func (o ClusterQueueHostedAgentsLinuxOutput) ToClusterQueueHostedAgentsLinuxPtrOutput() ClusterQueueHostedAgentsLinuxPtrOutput {
	return o.ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(context.Background())
}

func (o ClusterQueueHostedAgentsLinuxOutput) ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsLinuxPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ClusterQueueHostedAgentsLinux) *ClusterQueueHostedAgentsLinux {
		return &v
	}).(ClusterQueueHostedAgentsLinuxPtrOutput)
}

// A URL reference to a container image that will be used for jobs running within the queue. This URL is required to be publicly available, or pushed to the internal registry available within the cluster. Please note that this value is currently experimental and in preview. Please contact support@buildkite.com to enable this functionality for your organization.
func (o ClusterQueueHostedAgentsLinuxOutput) AgentImageRef() pulumi.StringOutput {
	return o.ApplyT(func(v ClusterQueueHostedAgentsLinux) string { return v.AgentImageRef }).(pulumi.StringOutput)
}

type ClusterQueueHostedAgentsLinuxPtrOutput struct{ *pulumi.OutputState }

func (ClusterQueueHostedAgentsLinuxPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterQueueHostedAgentsLinux)(nil)).Elem()
}

func (o ClusterQueueHostedAgentsLinuxPtrOutput) ToClusterQueueHostedAgentsLinuxPtrOutput() ClusterQueueHostedAgentsLinuxPtrOutput {
	return o
}

func (o ClusterQueueHostedAgentsLinuxPtrOutput) ToClusterQueueHostedAgentsLinuxPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsLinuxPtrOutput {
	return o
}

func (o ClusterQueueHostedAgentsLinuxPtrOutput) Elem() ClusterQueueHostedAgentsLinuxOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgentsLinux) ClusterQueueHostedAgentsLinux {
		if v != nil {
			return *v
		}
		var ret ClusterQueueHostedAgentsLinux
		return ret
	}).(ClusterQueueHostedAgentsLinuxOutput)
}

// A URL reference to a container image that will be used for jobs running within the queue. This URL is required to be publicly available, or pushed to the internal registry available within the cluster. Please note that this value is currently experimental and in preview. Please contact support@buildkite.com to enable this functionality for your organization.
func (o ClusterQueueHostedAgentsLinuxPtrOutput) AgentImageRef() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgentsLinux) *string {
		if v == nil {
			return nil
		}
		return &v.AgentImageRef
	}).(pulumi.StringPtrOutput)
}

type ClusterQueueHostedAgentsMac struct {
	// Optional selection of a specific macOS version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
	MacosVersion *string `pulumi:"macosVersion"`
	// Required selection of a specific XCode version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
	XcodeVersion string `pulumi:"xcodeVersion"`
}

// ClusterQueueHostedAgentsMacInput is an input type that accepts ClusterQueueHostedAgentsMacArgs and ClusterQueueHostedAgentsMacOutput values.
// You can construct a concrete instance of `ClusterQueueHostedAgentsMacInput` via:
//
//	ClusterQueueHostedAgentsMacArgs{...}
type ClusterQueueHostedAgentsMacInput interface {
	pulumi.Input

	ToClusterQueueHostedAgentsMacOutput() ClusterQueueHostedAgentsMacOutput
	ToClusterQueueHostedAgentsMacOutputWithContext(context.Context) ClusterQueueHostedAgentsMacOutput
}

type ClusterQueueHostedAgentsMacArgs struct {
	// Optional selection of a specific macOS version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
	MacosVersion pulumi.StringPtrInput `pulumi:"macosVersion"`
	// Required selection of a specific XCode version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
	XcodeVersion pulumi.StringInput `pulumi:"xcodeVersion"`
}

func (ClusterQueueHostedAgentsMacArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterQueueHostedAgentsMac)(nil)).Elem()
}

func (i ClusterQueueHostedAgentsMacArgs) ToClusterQueueHostedAgentsMacOutput() ClusterQueueHostedAgentsMacOutput {
	return i.ToClusterQueueHostedAgentsMacOutputWithContext(context.Background())
}

func (i ClusterQueueHostedAgentsMacArgs) ToClusterQueueHostedAgentsMacOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsMacOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsMacOutput)
}

func (i ClusterQueueHostedAgentsMacArgs) ToClusterQueueHostedAgentsMacPtrOutput() ClusterQueueHostedAgentsMacPtrOutput {
	return i.ToClusterQueueHostedAgentsMacPtrOutputWithContext(context.Background())
}

func (i ClusterQueueHostedAgentsMacArgs) ToClusterQueueHostedAgentsMacPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsMacPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsMacOutput).ToClusterQueueHostedAgentsMacPtrOutputWithContext(ctx)
}

// ClusterQueueHostedAgentsMacPtrInput is an input type that accepts ClusterQueueHostedAgentsMacArgs, ClusterQueueHostedAgentsMacPtr and ClusterQueueHostedAgentsMacPtrOutput values.
// You can construct a concrete instance of `ClusterQueueHostedAgentsMacPtrInput` via:
//
//	        ClusterQueueHostedAgentsMacArgs{...}
//
//	or:
//
//	        nil
type ClusterQueueHostedAgentsMacPtrInput interface {
	pulumi.Input

	ToClusterQueueHostedAgentsMacPtrOutput() ClusterQueueHostedAgentsMacPtrOutput
	ToClusterQueueHostedAgentsMacPtrOutputWithContext(context.Context) ClusterQueueHostedAgentsMacPtrOutput
}

type clusterQueueHostedAgentsMacPtrType ClusterQueueHostedAgentsMacArgs

func ClusterQueueHostedAgentsMacPtr(v *ClusterQueueHostedAgentsMacArgs) ClusterQueueHostedAgentsMacPtrInput {
	return (*clusterQueueHostedAgentsMacPtrType)(v)
}

func (*clusterQueueHostedAgentsMacPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterQueueHostedAgentsMac)(nil)).Elem()
}

func (i *clusterQueueHostedAgentsMacPtrType) ToClusterQueueHostedAgentsMacPtrOutput() ClusterQueueHostedAgentsMacPtrOutput {
	return i.ToClusterQueueHostedAgentsMacPtrOutputWithContext(context.Background())
}

func (i *clusterQueueHostedAgentsMacPtrType) ToClusterQueueHostedAgentsMacPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsMacPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterQueueHostedAgentsMacPtrOutput)
}

type ClusterQueueHostedAgentsMacOutput struct{ *pulumi.OutputState }

func (ClusterQueueHostedAgentsMacOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterQueueHostedAgentsMac)(nil)).Elem()
}

func (o ClusterQueueHostedAgentsMacOutput) ToClusterQueueHostedAgentsMacOutput() ClusterQueueHostedAgentsMacOutput {
	return o
}

func (o ClusterQueueHostedAgentsMacOutput) ToClusterQueueHostedAgentsMacOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsMacOutput {
	return o
}

func (o ClusterQueueHostedAgentsMacOutput) ToClusterQueueHostedAgentsMacPtrOutput() ClusterQueueHostedAgentsMacPtrOutput {
	return o.ToClusterQueueHostedAgentsMacPtrOutputWithContext(context.Background())
}

func (o ClusterQueueHostedAgentsMacOutput) ToClusterQueueHostedAgentsMacPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsMacPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ClusterQueueHostedAgentsMac) *ClusterQueueHostedAgentsMac {
		return &v
	}).(ClusterQueueHostedAgentsMacPtrOutput)
}

// Optional selection of a specific macOS version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
func (o ClusterQueueHostedAgentsMacOutput) MacosVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterQueueHostedAgentsMac) *string { return v.MacosVersion }).(pulumi.StringPtrOutput)
}

// Required selection of a specific XCode version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
func (o ClusterQueueHostedAgentsMacOutput) XcodeVersion() pulumi.StringOutput {
	return o.ApplyT(func(v ClusterQueueHostedAgentsMac) string { return v.XcodeVersion }).(pulumi.StringOutput)
}

type ClusterQueueHostedAgentsMacPtrOutput struct{ *pulumi.OutputState }

func (ClusterQueueHostedAgentsMacPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterQueueHostedAgentsMac)(nil)).Elem()
}

func (o ClusterQueueHostedAgentsMacPtrOutput) ToClusterQueueHostedAgentsMacPtrOutput() ClusterQueueHostedAgentsMacPtrOutput {
	return o
}

func (o ClusterQueueHostedAgentsMacPtrOutput) ToClusterQueueHostedAgentsMacPtrOutputWithContext(ctx context.Context) ClusterQueueHostedAgentsMacPtrOutput {
	return o
}

func (o ClusterQueueHostedAgentsMacPtrOutput) Elem() ClusterQueueHostedAgentsMacOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgentsMac) ClusterQueueHostedAgentsMac {
		if v != nil {
			return *v
		}
		var ret ClusterQueueHostedAgentsMac
		return ret
	}).(ClusterQueueHostedAgentsMacOutput)
}

// Optional selection of a specific macOS version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
func (o ClusterQueueHostedAgentsMacPtrOutput) MacosVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgentsMac) *string {
		if v == nil {
			return nil
		}
		return v.MacosVersion
	}).(pulumi.StringPtrOutput)
}

// Required selection of a specific XCode version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
func (o ClusterQueueHostedAgentsMacPtrOutput) XcodeVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterQueueHostedAgentsMac) *string {
		if v == nil {
			return nil
		}
		return &v.XcodeVersion
	}).(pulumi.StringPtrOutput)
}

type GetClusterMaintainerType struct {
	// The email of the actor (only for users).
	ActorEmail string `pulumi:"actorEmail"`
	// The name of the actor.
	ActorName string `pulumi:"actorName"`
	// The slug of the actor (only for teams).
	ActorSlug string `pulumi:"actorSlug"`
	// The type of the actor (user or team).
	ActorType string `pulumi:"actorType"`
	// The UUID of the actor (user or team).
	ActorUuid string `pulumi:"actorUuid"`
	// The UUID of the maintainer permission.
	PermissionUuid string `pulumi:"permissionUuid"`
}

// GetClusterMaintainerTypeInput is an input type that accepts GetClusterMaintainerTypeArgs and GetClusterMaintainerTypeOutput values.
// You can construct a concrete instance of `GetClusterMaintainerTypeInput` via:
//
//	GetClusterMaintainerTypeArgs{...}
type GetClusterMaintainerTypeInput interface {
	pulumi.Input

	ToGetClusterMaintainerTypeOutput() GetClusterMaintainerTypeOutput
	ToGetClusterMaintainerTypeOutputWithContext(context.Context) GetClusterMaintainerTypeOutput
}

type GetClusterMaintainerTypeArgs struct {
	// The email of the actor (only for users).
	ActorEmail pulumi.StringInput `pulumi:"actorEmail"`
	// The name of the actor.
	ActorName pulumi.StringInput `pulumi:"actorName"`
	// The slug of the actor (only for teams).
	ActorSlug pulumi.StringInput `pulumi:"actorSlug"`
	// The type of the actor (user or team).
	ActorType pulumi.StringInput `pulumi:"actorType"`
	// The UUID of the actor (user or team).
	ActorUuid pulumi.StringInput `pulumi:"actorUuid"`
	// The UUID of the maintainer permission.
	PermissionUuid pulumi.StringInput `pulumi:"permissionUuid"`
}

func (GetClusterMaintainerTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClusterMaintainerType)(nil)).Elem()
}

func (i GetClusterMaintainerTypeArgs) ToGetClusterMaintainerTypeOutput() GetClusterMaintainerTypeOutput {
	return i.ToGetClusterMaintainerTypeOutputWithContext(context.Background())
}

func (i GetClusterMaintainerTypeArgs) ToGetClusterMaintainerTypeOutputWithContext(ctx context.Context) GetClusterMaintainerTypeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClusterMaintainerTypeOutput)
}

// GetClusterMaintainerTypeArrayInput is an input type that accepts GetClusterMaintainerTypeArray and GetClusterMaintainerTypeArrayOutput values.
// You can construct a concrete instance of `GetClusterMaintainerTypeArrayInput` via:
//
//	GetClusterMaintainerTypeArray{ GetClusterMaintainerTypeArgs{...} }
type GetClusterMaintainerTypeArrayInput interface {
	pulumi.Input

	ToGetClusterMaintainerTypeArrayOutput() GetClusterMaintainerTypeArrayOutput
	ToGetClusterMaintainerTypeArrayOutputWithContext(context.Context) GetClusterMaintainerTypeArrayOutput
}

type GetClusterMaintainerTypeArray []GetClusterMaintainerTypeInput

func (GetClusterMaintainerTypeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClusterMaintainerType)(nil)).Elem()
}

func (i GetClusterMaintainerTypeArray) ToGetClusterMaintainerTypeArrayOutput() GetClusterMaintainerTypeArrayOutput {
	return i.ToGetClusterMaintainerTypeArrayOutputWithContext(context.Background())
}

func (i GetClusterMaintainerTypeArray) ToGetClusterMaintainerTypeArrayOutputWithContext(ctx context.Context) GetClusterMaintainerTypeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClusterMaintainerTypeArrayOutput)
}

type GetClusterMaintainerTypeOutput struct{ *pulumi.OutputState }

func (GetClusterMaintainerTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClusterMaintainerType)(nil)).Elem()
}

func (o GetClusterMaintainerTypeOutput) ToGetClusterMaintainerTypeOutput() GetClusterMaintainerTypeOutput {
	return o
}

func (o GetClusterMaintainerTypeOutput) ToGetClusterMaintainerTypeOutputWithContext(ctx context.Context) GetClusterMaintainerTypeOutput {
	return o
}

// The email of the actor (only for users).
func (o GetClusterMaintainerTypeOutput) ActorEmail() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterMaintainerType) string { return v.ActorEmail }).(pulumi.StringOutput)
}

// The name of the actor.
func (o GetClusterMaintainerTypeOutput) ActorName() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterMaintainerType) string { return v.ActorName }).(pulumi.StringOutput)
}

// The slug of the actor (only for teams).
func (o GetClusterMaintainerTypeOutput) ActorSlug() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterMaintainerType) string { return v.ActorSlug }).(pulumi.StringOutput)
}

// The type of the actor (user or team).
func (o GetClusterMaintainerTypeOutput) ActorType() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterMaintainerType) string { return v.ActorType }).(pulumi.StringOutput)
}

// The UUID of the actor (user or team).
func (o GetClusterMaintainerTypeOutput) ActorUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterMaintainerType) string { return v.ActorUuid }).(pulumi.StringOutput)
}

// The UUID of the maintainer permission.
func (o GetClusterMaintainerTypeOutput) PermissionUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterMaintainerType) string { return v.PermissionUuid }).(pulumi.StringOutput)
}

type GetClusterMaintainerTypeArrayOutput struct{ *pulumi.OutputState }

func (GetClusterMaintainerTypeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClusterMaintainerType)(nil)).Elem()
}

func (o GetClusterMaintainerTypeArrayOutput) ToGetClusterMaintainerTypeArrayOutput() GetClusterMaintainerTypeArrayOutput {
	return o
}

func (o GetClusterMaintainerTypeArrayOutput) ToGetClusterMaintainerTypeArrayOutputWithContext(ctx context.Context) GetClusterMaintainerTypeArrayOutput {
	return o
}

func (o GetClusterMaintainerTypeArrayOutput) Index(i pulumi.IntInput) GetClusterMaintainerTypeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetClusterMaintainerType {
		return vs[0].([]GetClusterMaintainerType)[vs[1].(int)]
	}).(GetClusterMaintainerTypeOutput)
}

type GetClustersCluster struct {
	// The color for the cluster.
	Color string `pulumi:"color"`
	// The default queue for the cluster.
	DefaultQueue GetClustersClusterDefaultQueue `pulumi:"defaultQueue"`
	// The description of the cluster.
	Description string `pulumi:"description"`
	// The emoji for the cluster.
	Emoji string `pulumi:"emoji"`
	// The GraphQL ID of the cluster.
	Id string `pulumi:"id"`
	// List of maintainers (users and teams) for this cluster.
	Maintainers []GetClustersClusterMaintainer `pulumi:"maintainers"`
	// The name of the cluster.
	Name string `pulumi:"name"`
	// The UUID of the cluster.
	Uuid string `pulumi:"uuid"`
}

// GetClustersClusterInput is an input type that accepts GetClustersClusterArgs and GetClustersClusterOutput values.
// You can construct a concrete instance of `GetClustersClusterInput` via:
//
//	GetClustersClusterArgs{...}
type GetClustersClusterInput interface {
	pulumi.Input

	ToGetClustersClusterOutput() GetClustersClusterOutput
	ToGetClustersClusterOutputWithContext(context.Context) GetClustersClusterOutput
}

type GetClustersClusterArgs struct {
	// The color for the cluster.
	Color pulumi.StringInput `pulumi:"color"`
	// The default queue for the cluster.
	DefaultQueue GetClustersClusterDefaultQueueInput `pulumi:"defaultQueue"`
	// The description of the cluster.
	Description pulumi.StringInput `pulumi:"description"`
	// The emoji for the cluster.
	Emoji pulumi.StringInput `pulumi:"emoji"`
	// The GraphQL ID of the cluster.
	Id pulumi.StringInput `pulumi:"id"`
	// List of maintainers (users and teams) for this cluster.
	Maintainers GetClustersClusterMaintainerArrayInput `pulumi:"maintainers"`
	// The name of the cluster.
	Name pulumi.StringInput `pulumi:"name"`
	// The UUID of the cluster.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetClustersClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClustersCluster)(nil)).Elem()
}

func (i GetClustersClusterArgs) ToGetClustersClusterOutput() GetClustersClusterOutput {
	return i.ToGetClustersClusterOutputWithContext(context.Background())
}

func (i GetClustersClusterArgs) ToGetClustersClusterOutputWithContext(ctx context.Context) GetClustersClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClustersClusterOutput)
}

// GetClustersClusterArrayInput is an input type that accepts GetClustersClusterArray and GetClustersClusterArrayOutput values.
// You can construct a concrete instance of `GetClustersClusterArrayInput` via:
//
//	GetClustersClusterArray{ GetClustersClusterArgs{...} }
type GetClustersClusterArrayInput interface {
	pulumi.Input

	ToGetClustersClusterArrayOutput() GetClustersClusterArrayOutput
	ToGetClustersClusterArrayOutputWithContext(context.Context) GetClustersClusterArrayOutput
}

type GetClustersClusterArray []GetClustersClusterInput

func (GetClustersClusterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClustersCluster)(nil)).Elem()
}

func (i GetClustersClusterArray) ToGetClustersClusterArrayOutput() GetClustersClusterArrayOutput {
	return i.ToGetClustersClusterArrayOutputWithContext(context.Background())
}

func (i GetClustersClusterArray) ToGetClustersClusterArrayOutputWithContext(ctx context.Context) GetClustersClusterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClustersClusterArrayOutput)
}

type GetClustersClusterOutput struct{ *pulumi.OutputState }

func (GetClustersClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClustersCluster)(nil)).Elem()
}

func (o GetClustersClusterOutput) ToGetClustersClusterOutput() GetClustersClusterOutput {
	return o
}

func (o GetClustersClusterOutput) ToGetClustersClusterOutputWithContext(ctx context.Context) GetClustersClusterOutput {
	return o
}

// The color for the cluster.
func (o GetClustersClusterOutput) Color() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersCluster) string { return v.Color }).(pulumi.StringOutput)
}

// The default queue for the cluster.
func (o GetClustersClusterOutput) DefaultQueue() GetClustersClusterDefaultQueueOutput {
	return o.ApplyT(func(v GetClustersCluster) GetClustersClusterDefaultQueue { return v.DefaultQueue }).(GetClustersClusterDefaultQueueOutput)
}

// The description of the cluster.
func (o GetClustersClusterOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersCluster) string { return v.Description }).(pulumi.StringOutput)
}

// The emoji for the cluster.
func (o GetClustersClusterOutput) Emoji() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersCluster) string { return v.Emoji }).(pulumi.StringOutput)
}

// The GraphQL ID of the cluster.
func (o GetClustersClusterOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersCluster) string { return v.Id }).(pulumi.StringOutput)
}

// List of maintainers (users and teams) for this cluster.
func (o GetClustersClusterOutput) Maintainers() GetClustersClusterMaintainerArrayOutput {
	return o.ApplyT(func(v GetClustersCluster) []GetClustersClusterMaintainer { return v.Maintainers }).(GetClustersClusterMaintainerArrayOutput)
}

// The name of the cluster.
func (o GetClustersClusterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersCluster) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the cluster.
func (o GetClustersClusterOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersCluster) string { return v.Uuid }).(pulumi.StringOutput)
}

type GetClustersClusterArrayOutput struct{ *pulumi.OutputState }

func (GetClustersClusterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClustersCluster)(nil)).Elem()
}

func (o GetClustersClusterArrayOutput) ToGetClustersClusterArrayOutput() GetClustersClusterArrayOutput {
	return o
}

func (o GetClustersClusterArrayOutput) ToGetClustersClusterArrayOutputWithContext(ctx context.Context) GetClustersClusterArrayOutput {
	return o
}

func (o GetClustersClusterArrayOutput) Index(i pulumi.IntInput) GetClustersClusterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetClustersCluster {
		return vs[0].([]GetClustersCluster)[vs[1].(int)]
	}).(GetClustersClusterOutput)
}

type GetClustersClusterDefaultQueue struct {
	// The description of the default queue.
	Description string `pulumi:"description"`
	// The GraphQL ID of the default queue.
	Id string `pulumi:"id"`
	// The key of the default queue.
	Key string `pulumi:"key"`
	// The UUID of the default queue.
	Uuid string `pulumi:"uuid"`
}

// GetClustersClusterDefaultQueueInput is an input type that accepts GetClustersClusterDefaultQueueArgs and GetClustersClusterDefaultQueueOutput values.
// You can construct a concrete instance of `GetClustersClusterDefaultQueueInput` via:
//
//	GetClustersClusterDefaultQueueArgs{...}
type GetClustersClusterDefaultQueueInput interface {
	pulumi.Input

	ToGetClustersClusterDefaultQueueOutput() GetClustersClusterDefaultQueueOutput
	ToGetClustersClusterDefaultQueueOutputWithContext(context.Context) GetClustersClusterDefaultQueueOutput
}

type GetClustersClusterDefaultQueueArgs struct {
	// The description of the default queue.
	Description pulumi.StringInput `pulumi:"description"`
	// The GraphQL ID of the default queue.
	Id pulumi.StringInput `pulumi:"id"`
	// The key of the default queue.
	Key pulumi.StringInput `pulumi:"key"`
	// The UUID of the default queue.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetClustersClusterDefaultQueueArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClustersClusterDefaultQueue)(nil)).Elem()
}

func (i GetClustersClusterDefaultQueueArgs) ToGetClustersClusterDefaultQueueOutput() GetClustersClusterDefaultQueueOutput {
	return i.ToGetClustersClusterDefaultQueueOutputWithContext(context.Background())
}

func (i GetClustersClusterDefaultQueueArgs) ToGetClustersClusterDefaultQueueOutputWithContext(ctx context.Context) GetClustersClusterDefaultQueueOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClustersClusterDefaultQueueOutput)
}

type GetClustersClusterDefaultQueueOutput struct{ *pulumi.OutputState }

func (GetClustersClusterDefaultQueueOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClustersClusterDefaultQueue)(nil)).Elem()
}

func (o GetClustersClusterDefaultQueueOutput) ToGetClustersClusterDefaultQueueOutput() GetClustersClusterDefaultQueueOutput {
	return o
}

func (o GetClustersClusterDefaultQueueOutput) ToGetClustersClusterDefaultQueueOutputWithContext(ctx context.Context) GetClustersClusterDefaultQueueOutput {
	return o
}

// The description of the default queue.
func (o GetClustersClusterDefaultQueueOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterDefaultQueue) string { return v.Description }).(pulumi.StringOutput)
}

// The GraphQL ID of the default queue.
func (o GetClustersClusterDefaultQueueOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterDefaultQueue) string { return v.Id }).(pulumi.StringOutput)
}

// The key of the default queue.
func (o GetClustersClusterDefaultQueueOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterDefaultQueue) string { return v.Key }).(pulumi.StringOutput)
}

// The UUID of the default queue.
func (o GetClustersClusterDefaultQueueOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterDefaultQueue) string { return v.Uuid }).(pulumi.StringOutput)
}

type GetClustersClusterMaintainer struct {
	// The email of the actor (only for users).
	ActorEmail string `pulumi:"actorEmail"`
	// The name of the actor.
	ActorName string `pulumi:"actorName"`
	// The slug of the actor (only for teams).
	ActorSlug string `pulumi:"actorSlug"`
	// The type of the actor (user or team).
	ActorType string `pulumi:"actorType"`
	// The UUID of the actor (user or team).
	ActorUuid string `pulumi:"actorUuid"`
	// The UUID of the maintainer permission.
	PermissionUuid string `pulumi:"permissionUuid"`
}

// GetClustersClusterMaintainerInput is an input type that accepts GetClustersClusterMaintainerArgs and GetClustersClusterMaintainerOutput values.
// You can construct a concrete instance of `GetClustersClusterMaintainerInput` via:
//
//	GetClustersClusterMaintainerArgs{...}
type GetClustersClusterMaintainerInput interface {
	pulumi.Input

	ToGetClustersClusterMaintainerOutput() GetClustersClusterMaintainerOutput
	ToGetClustersClusterMaintainerOutputWithContext(context.Context) GetClustersClusterMaintainerOutput
}

type GetClustersClusterMaintainerArgs struct {
	// The email of the actor (only for users).
	ActorEmail pulumi.StringInput `pulumi:"actorEmail"`
	// The name of the actor.
	ActorName pulumi.StringInput `pulumi:"actorName"`
	// The slug of the actor (only for teams).
	ActorSlug pulumi.StringInput `pulumi:"actorSlug"`
	// The type of the actor (user or team).
	ActorType pulumi.StringInput `pulumi:"actorType"`
	// The UUID of the actor (user or team).
	ActorUuid pulumi.StringInput `pulumi:"actorUuid"`
	// The UUID of the maintainer permission.
	PermissionUuid pulumi.StringInput `pulumi:"permissionUuid"`
}

func (GetClustersClusterMaintainerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClustersClusterMaintainer)(nil)).Elem()
}

func (i GetClustersClusterMaintainerArgs) ToGetClustersClusterMaintainerOutput() GetClustersClusterMaintainerOutput {
	return i.ToGetClustersClusterMaintainerOutputWithContext(context.Background())
}

func (i GetClustersClusterMaintainerArgs) ToGetClustersClusterMaintainerOutputWithContext(ctx context.Context) GetClustersClusterMaintainerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClustersClusterMaintainerOutput)
}

// GetClustersClusterMaintainerArrayInput is an input type that accepts GetClustersClusterMaintainerArray and GetClustersClusterMaintainerArrayOutput values.
// You can construct a concrete instance of `GetClustersClusterMaintainerArrayInput` via:
//
//	GetClustersClusterMaintainerArray{ GetClustersClusterMaintainerArgs{...} }
type GetClustersClusterMaintainerArrayInput interface {
	pulumi.Input

	ToGetClustersClusterMaintainerArrayOutput() GetClustersClusterMaintainerArrayOutput
	ToGetClustersClusterMaintainerArrayOutputWithContext(context.Context) GetClustersClusterMaintainerArrayOutput
}

type GetClustersClusterMaintainerArray []GetClustersClusterMaintainerInput

func (GetClustersClusterMaintainerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClustersClusterMaintainer)(nil)).Elem()
}

func (i GetClustersClusterMaintainerArray) ToGetClustersClusterMaintainerArrayOutput() GetClustersClusterMaintainerArrayOutput {
	return i.ToGetClustersClusterMaintainerArrayOutputWithContext(context.Background())
}

func (i GetClustersClusterMaintainerArray) ToGetClustersClusterMaintainerArrayOutputWithContext(ctx context.Context) GetClustersClusterMaintainerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetClustersClusterMaintainerArrayOutput)
}

type GetClustersClusterMaintainerOutput struct{ *pulumi.OutputState }

func (GetClustersClusterMaintainerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClustersClusterMaintainer)(nil)).Elem()
}

func (o GetClustersClusterMaintainerOutput) ToGetClustersClusterMaintainerOutput() GetClustersClusterMaintainerOutput {
	return o
}

func (o GetClustersClusterMaintainerOutput) ToGetClustersClusterMaintainerOutputWithContext(ctx context.Context) GetClustersClusterMaintainerOutput {
	return o
}

// The email of the actor (only for users).
func (o GetClustersClusterMaintainerOutput) ActorEmail() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterMaintainer) string { return v.ActorEmail }).(pulumi.StringOutput)
}

// The name of the actor.
func (o GetClustersClusterMaintainerOutput) ActorName() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterMaintainer) string { return v.ActorName }).(pulumi.StringOutput)
}

// The slug of the actor (only for teams).
func (o GetClustersClusterMaintainerOutput) ActorSlug() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterMaintainer) string { return v.ActorSlug }).(pulumi.StringOutput)
}

// The type of the actor (user or team).
func (o GetClustersClusterMaintainerOutput) ActorType() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterMaintainer) string { return v.ActorType }).(pulumi.StringOutput)
}

// The UUID of the actor (user or team).
func (o GetClustersClusterMaintainerOutput) ActorUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterMaintainer) string { return v.ActorUuid }).(pulumi.StringOutput)
}

// The UUID of the maintainer permission.
func (o GetClustersClusterMaintainerOutput) PermissionUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetClustersClusterMaintainer) string { return v.PermissionUuid }).(pulumi.StringOutput)
}

type GetClustersClusterMaintainerArrayOutput struct{ *pulumi.OutputState }

func (GetClustersClusterMaintainerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetClustersClusterMaintainer)(nil)).Elem()
}

func (o GetClustersClusterMaintainerArrayOutput) ToGetClustersClusterMaintainerArrayOutput() GetClustersClusterMaintainerArrayOutput {
	return o
}

func (o GetClustersClusterMaintainerArrayOutput) ToGetClustersClusterMaintainerArrayOutputWithContext(ctx context.Context) GetClustersClusterMaintainerArrayOutput {
	return o
}

func (o GetClustersClusterMaintainerArrayOutput) Index(i pulumi.IntInput) GetClustersClusterMaintainerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetClustersClusterMaintainer {
		return vs[0].([]GetClustersClusterMaintainer)[vs[1].(int)]
	}).(GetClustersClusterMaintainerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterQueueHostedAgentsInput)(nil)).Elem(), ClusterQueueHostedAgentsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterQueueHostedAgentsPtrInput)(nil)).Elem(), ClusterQueueHostedAgentsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterQueueHostedAgentsLinuxInput)(nil)).Elem(), ClusterQueueHostedAgentsLinuxArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterQueueHostedAgentsLinuxPtrInput)(nil)).Elem(), ClusterQueueHostedAgentsLinuxArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterQueueHostedAgentsMacInput)(nil)).Elem(), ClusterQueueHostedAgentsMacArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterQueueHostedAgentsMacPtrInput)(nil)).Elem(), ClusterQueueHostedAgentsMacArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClusterMaintainerTypeInput)(nil)).Elem(), GetClusterMaintainerTypeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClusterMaintainerTypeArrayInput)(nil)).Elem(), GetClusterMaintainerTypeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClustersClusterInput)(nil)).Elem(), GetClustersClusterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClustersClusterArrayInput)(nil)).Elem(), GetClustersClusterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClustersClusterDefaultQueueInput)(nil)).Elem(), GetClustersClusterDefaultQueueArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClustersClusterMaintainerInput)(nil)).Elem(), GetClustersClusterMaintainerArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetClustersClusterMaintainerArrayInput)(nil)).Elem(), GetClustersClusterMaintainerArray{})
	pulumi.RegisterOutputType(ClusterQueueHostedAgentsOutput{})
	pulumi.RegisterOutputType(ClusterQueueHostedAgentsPtrOutput{})
	pulumi.RegisterOutputType(ClusterQueueHostedAgentsLinuxOutput{})
	pulumi.RegisterOutputType(ClusterQueueHostedAgentsLinuxPtrOutput{})
	pulumi.RegisterOutputType(ClusterQueueHostedAgentsMacOutput{})
	pulumi.RegisterOutputType(ClusterQueueHostedAgentsMacPtrOutput{})
	pulumi.RegisterOutputType(GetClusterMaintainerTypeOutput{})
	pulumi.RegisterOutputType(GetClusterMaintainerTypeArrayOutput{})
	pulumi.RegisterOutputType(GetClustersClusterOutput{})
	pulumi.RegisterOutputType(GetClustersClusterArrayOutput{})
	pulumi.RegisterOutputType(GetClustersClusterDefaultQueueOutput{})
	pulumi.RegisterOutputType(GetClustersClusterMaintainerOutput{})
	pulumi.RegisterOutputType(GetClustersClusterMaintainerArrayOutput{})
}
