#!/usr/bin/env bash

set -euo pipefail

readonly action="${1}"

if [ "${action}" == "get" ]; then
    echo "url=${BUILDKITE_REPO}"
    echo "username=grapl-cicd"
    echo "password=${GITHUB_TOKEN}"
fi
