#!/usr/bin/env bash

set -euo pipefail

echo "--- :nodejs: Uploading NodeJS SDK"

NPM_CONFIG_USERCONFIG=$(pwd)/buildkite-npmrc
export NPM_CONFIG_USERCONFIG

npm config set _authToken "${NPM_API_TOKEN}"

npm publish \
    --access=public \
    sdk/nodejs/bin/dist/*.tgz

rm "${NPM_CONFIG_USERCONFIG}"
