// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ProviderTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
     */
    read?: pulumi.Input<string>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: pulumi.Input<string>;
}
export namespace Cluster {
    export interface ClusterQueueHostedAgents {
        /**
         * The instance shape to use for the Hosted Agent cluster queue. This can be a MacOS instance shape or a Linux instance shape.
         * Valid values are:
         * - MACOS_ARM64_M4_6X28
         * - MACOS_ARM64_M4_12X56
         * - LINUX_AMD64_2X4
         * - LINUX_AMD64_4X16
         * - LINUX_AMD64_8X32
         * - LINUX_AMD64_16X64
         * - LINUX_ARM64_2X4
         * - LINUX_ARM64_4X16
         * - LINUX_ARM64_8X32
         * - LINUX_ARM64_16X64
         */
        instanceShape: pulumi.Input<string>;
        linux?: pulumi.Input<inputs.Cluster.ClusterQueueHostedAgentsLinux>;
        mac?: pulumi.Input<inputs.Cluster.ClusterQueueHostedAgentsMac>;
    }

    export interface ClusterQueueHostedAgentsLinux {
        /**
         * A URL reference to a container image that will be used for jobs running within the queue. This URL is required to be publicly available, or pushed to the internal registry available within the cluster. Please note that this value is currently experimental and in preview. Please contact support@buildkite.com to enable this functionality for your organization.
         */
        agentImageRef: pulumi.Input<string>;
    }

    export interface ClusterQueueHostedAgentsMac {
        /**
         * Optional selection of a specific macOS version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
         */
        macosVersion?: pulumi.Input<string>;
        /**
         * Required selection of a specific XCode version to be selected for jobs in the queue to have available. Please note that this value is currently experimental and may not function as expected.
         */
        xcodeVersion: pulumi.Input<string>;
    }

}

export namespace Organization {
    export interface PortalCreatedBy {
        /**
         * The email of the user.
         */
        email?: pulumi.Input<string>;
        /**
         * The name of the user.
         */
        name?: pulumi.Input<string>;
        /**
         * The UUID of the user.
         */
        uuid?: pulumi.Input<string>;
    }
}

export namespace Pipeline {
    export interface PipelineProviderSettings {
        /**
         * Whether to create builds when branches are pushed.
         */
        buildBranches?: pulumi.Input<boolean>;
        /**
         * Whether to create merge queue builds for a merge queue enabled GitHub repository with required status checks
         */
        buildMergeGroupChecksRequested?: pulumi.Input<boolean>;
        /**
         * Whether to create builds for pull requests when its base branch changes.
         */
        buildPullRequestBaseBranchChanged?: pulumi.Input<boolean>;
        /**
         * Whether to create builds for pull requests from third-party forks.
         */
        buildPullRequestForks?: pulumi.Input<boolean>;
        /**
         * Whether to create builds for pull requests when labels are added or removed.
         */
        buildPullRequestLabelsChanged?: pulumi.Input<boolean>;
        /**
         * Whether to create a build when a pull request changes to "Ready for review".
         */
        buildPullRequestReadyForReview?: pulumi.Input<boolean>;
        /**
         * Whether to create builds for commits that are part of a pull request.
         */
        buildPullRequests?: pulumi.Input<boolean>;
        /**
         * Whether to create builds when tags are pushed.
         */
        buildTags?: pulumi.Input<boolean>;
        /**
         * Automatically cancel running builds for a branch if the branch is deleted.
         */
        cancelDeletedBranchBuilds?: pulumi.Input<boolean>;
        /**
         * Whether to cancel any running builds belonging to a removed merge group.
         */
        cancelWhenMergeGroupDestroyed?: pulumi.Input<boolean>;
        /**
         * The condition to evaluate when deciding if a build should run. This is only valid when `triggerMode` is `code`. More details available in [the documentation](https://buildkite.com/docs/pipelines/conditionals).
         */
        filterCondition?: pulumi.Input<string>;
        /**
         * Whether to filter builds to only run when the condition in `filterCondition` is true.
         */
        filterEnabled?: pulumi.Input<boolean>;
        /**
         * Whether to prevent caching pull requests with the source branch matching the default branch.
         */
        ignoreDefaultBranchPullRequests?: pulumi.Input<boolean>;
        /**
         * Prefix branch names for third-party fork builds to ensure they don't trigger branch conditions. For example, the main branch from some-user will become some-user:main.
         */
        prefixPullRequestForkBranchNames?: pulumi.Input<boolean>;
        /**
         * The status to use for blocked builds. Pending can be used with [required status checks](https://help.github.com/en/articles/enabling-required-status-checks) to prevent merging pull requests with blocked builds.
         */
        publishBlockedAsPending?: pulumi.Input<boolean>;
        /**
         * Whether to update the status of commits in Bitbucket, GitHub, or GitLab.
         */
        publishCommitStatus?: pulumi.Input<boolean>;
        /**
         * Whether to create a separate status for each job in a build, allowing you to see the status of each job directly in Bitbucket or GitHub.
         */
        publishCommitStatusPerStep?: pulumi.Input<boolean>;
        /**
         * Filter pull requests builds by the branch filter.
         */
        pullRequestBranchFilterConfiguration?: pulumi.Input<string>;
        /**
         * Filter pull request builds.
         */
        pullRequestBranchFilterEnabled?: pulumi.Input<boolean>;
        /**
         * Whether to create a separate status for pull request builds, allowing you to require a passing pull request build in your [required status checks](https://help.github.com/en/articles/enabling-required-status-checks) in GitHub.
         */
        separatePullRequestStatuses?: pulumi.Input<boolean>;
        /**
         * Whether to skip creating a new build if an existing build for the commit and branch already exists. This option is only valid if the pipeline uses a GitHub repository.
         */
        skipBuildsForExistingCommits?: pulumi.Input<boolean>;
        /**
         * Whether to skip creating a new build for a pull request if an existing build for the commit and branch already exists.
         */
        skipPullRequestBuildsForExistingCommits?: pulumi.Input<boolean>;
        /**
         * What type of event to trigger builds on. Must be one of:
         * 	- `code` will create builds when code is pushed to GitHub.
         * 	- `deployment` will create builds when a deployment is created in GitHub.
         * 	- `fork` will create builds when the GitHub repository is forked.
         * 	- `none` will not create any builds based on GitHub activity.
         *
         * 	> `triggerMode` is only valid if the pipeline uses a GitHub repository.
         * 	> If not set, the default value is `code` and other provider settings defaults are applied.
         */
        triggerMode?: pulumi.Input<string>;
        /**
         * When enabled, agents performing a git diff to determine steps to upload based on [`ifChanged`](https://buildkite.com/docs/pipelines/configure/step-types/command-step#agent-applied-attributes)comparisons will use the base commit that points to the previous merge group rather than the base branch
         */
        useMergeGroupBaseCommitForGitDiffBase?: pulumi.Input<boolean>;
    }
}

export namespace Team {
}

export namespace config {
}
