// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package organization

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/internal"
)

// Use this data source to retrieve a specific organization member, using their email. You can find out more about organization members in the Buildkite
// [documentation](https://buildkite.com/docs/platform/team-management).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/organization"
//	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/team"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			aSmith, err := organization.GetMember(ctx, &organization.GetMemberArgs{
//				Email: "a.smith@company.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			developers, err := team.NewTeam(ctx, "developers", &team.TeamArgs{
//				Name:              pulumi.String("Developers"),
//				Privacy:           pulumi.String("VISIBLE"),
//				DefaultTeam:       pulumi.Bool(false),
//				DefaultMemberRole: pulumi.String("MEMBER"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = team.NewMember(ctx, "developers_a_smith", &team.MemberArgs{
//				TeamId: developers.ID(),
//				UserId: pulumi.String(aSmith.Id),
//				Role:   pulumi.String("MEMBER"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetMember(ctx *pulumi.Context, args *GetMemberArgs, opts ...pulumi.InvokeOption) (*GetMemberResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetMemberResult
	err := ctx.Invoke("buildkite:Organization/getMember:getMember", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMember.
type GetMemberArgs struct {
	// The email address of the organization member.
	Email string `pulumi:"email"`
}

// A collection of values returned by getMember.
type GetMemberResult struct {
	// The email address of the organization member.
	Email string `pulumi:"email"`
	// The GraphQL ID of the organization member.
	Id string `pulumi:"id"`
	// The name of the organization member.
	Name string `pulumi:"name"`
	// The UUID of the organization member.
	Uuid string `pulumi:"uuid"`
}

func GetMemberOutput(ctx *pulumi.Context, args GetMemberOutputArgs, opts ...pulumi.InvokeOption) GetMemberResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetMemberResultOutput, error) {
			args := v.(GetMemberArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("buildkite:Organization/getMember:getMember", args, GetMemberResultOutput{}, options).(GetMemberResultOutput), nil
		}).(GetMemberResultOutput)
}

// A collection of arguments for invoking getMember.
type GetMemberOutputArgs struct {
	// The email address of the organization member.
	Email pulumi.StringInput `pulumi:"email"`
}

func (GetMemberOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMemberArgs)(nil)).Elem()
}

// A collection of values returned by getMember.
type GetMemberResultOutput struct{ *pulumi.OutputState }

func (GetMemberResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMemberResult)(nil)).Elem()
}

func (o GetMemberResultOutput) ToGetMemberResultOutput() GetMemberResultOutput {
	return o
}

func (o GetMemberResultOutput) ToGetMemberResultOutputWithContext(ctx context.Context) GetMemberResultOutput {
	return o
}

// The email address of the organization member.
func (o GetMemberResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetMemberResult) string { return v.Email }).(pulumi.StringOutput)
}

// The GraphQL ID of the organization member.
func (o GetMemberResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMemberResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the organization member.
func (o GetMemberResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetMemberResult) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the organization member.
func (o GetMemberResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetMemberResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMemberResultOutput{})
}
