// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package organization

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/internal"
)

var _ = internal.GetEnvOrDefault

type PortalCreatedBy struct {
	// The email of the user.
	Email *string `pulumi:"email"`
	// The name of the user.
	Name *string `pulumi:"name"`
	// The UUID of the user.
	Uuid *string `pulumi:"uuid"`
}

// PortalCreatedByInput is an input type that accepts PortalCreatedByArgs and PortalCreatedByOutput values.
// You can construct a concrete instance of `PortalCreatedByInput` via:
//
//	PortalCreatedByArgs{...}
type PortalCreatedByInput interface {
	pulumi.Input

	ToPortalCreatedByOutput() PortalCreatedByOutput
	ToPortalCreatedByOutputWithContext(context.Context) PortalCreatedByOutput
}

type PortalCreatedByArgs struct {
	// The email of the user.
	Email pulumi.StringPtrInput `pulumi:"email"`
	// The name of the user.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The UUID of the user.
	Uuid pulumi.StringPtrInput `pulumi:"uuid"`
}

func (PortalCreatedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PortalCreatedBy)(nil)).Elem()
}

func (i PortalCreatedByArgs) ToPortalCreatedByOutput() PortalCreatedByOutput {
	return i.ToPortalCreatedByOutputWithContext(context.Background())
}

func (i PortalCreatedByArgs) ToPortalCreatedByOutputWithContext(ctx context.Context) PortalCreatedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PortalCreatedByOutput)
}

func (i PortalCreatedByArgs) ToPortalCreatedByPtrOutput() PortalCreatedByPtrOutput {
	return i.ToPortalCreatedByPtrOutputWithContext(context.Background())
}

func (i PortalCreatedByArgs) ToPortalCreatedByPtrOutputWithContext(ctx context.Context) PortalCreatedByPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PortalCreatedByOutput).ToPortalCreatedByPtrOutputWithContext(ctx)
}

// PortalCreatedByPtrInput is an input type that accepts PortalCreatedByArgs, PortalCreatedByPtr and PortalCreatedByPtrOutput values.
// You can construct a concrete instance of `PortalCreatedByPtrInput` via:
//
//	        PortalCreatedByArgs{...}
//
//	or:
//
//	        nil
type PortalCreatedByPtrInput interface {
	pulumi.Input

	ToPortalCreatedByPtrOutput() PortalCreatedByPtrOutput
	ToPortalCreatedByPtrOutputWithContext(context.Context) PortalCreatedByPtrOutput
}

type portalCreatedByPtrType PortalCreatedByArgs

func PortalCreatedByPtr(v *PortalCreatedByArgs) PortalCreatedByPtrInput {
	return (*portalCreatedByPtrType)(v)
}

func (*portalCreatedByPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**PortalCreatedBy)(nil)).Elem()
}

func (i *portalCreatedByPtrType) ToPortalCreatedByPtrOutput() PortalCreatedByPtrOutput {
	return i.ToPortalCreatedByPtrOutputWithContext(context.Background())
}

func (i *portalCreatedByPtrType) ToPortalCreatedByPtrOutputWithContext(ctx context.Context) PortalCreatedByPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PortalCreatedByPtrOutput)
}

type PortalCreatedByOutput struct{ *pulumi.OutputState }

func (PortalCreatedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PortalCreatedBy)(nil)).Elem()
}

func (o PortalCreatedByOutput) ToPortalCreatedByOutput() PortalCreatedByOutput {
	return o
}

func (o PortalCreatedByOutput) ToPortalCreatedByOutputWithContext(ctx context.Context) PortalCreatedByOutput {
	return o
}

func (o PortalCreatedByOutput) ToPortalCreatedByPtrOutput() PortalCreatedByPtrOutput {
	return o.ToPortalCreatedByPtrOutputWithContext(context.Background())
}

func (o PortalCreatedByOutput) ToPortalCreatedByPtrOutputWithContext(ctx context.Context) PortalCreatedByPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v PortalCreatedBy) *PortalCreatedBy {
		return &v
	}).(PortalCreatedByPtrOutput)
}

// The email of the user.
func (o PortalCreatedByOutput) Email() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PortalCreatedBy) *string { return v.Email }).(pulumi.StringPtrOutput)
}

// The name of the user.
func (o PortalCreatedByOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PortalCreatedBy) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The UUID of the user.
func (o PortalCreatedByOutput) Uuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PortalCreatedBy) *string { return v.Uuid }).(pulumi.StringPtrOutput)
}

type PortalCreatedByPtrOutput struct{ *pulumi.OutputState }

func (PortalCreatedByPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PortalCreatedBy)(nil)).Elem()
}

func (o PortalCreatedByPtrOutput) ToPortalCreatedByPtrOutput() PortalCreatedByPtrOutput {
	return o
}

func (o PortalCreatedByPtrOutput) ToPortalCreatedByPtrOutputWithContext(ctx context.Context) PortalCreatedByPtrOutput {
	return o
}

func (o PortalCreatedByPtrOutput) Elem() PortalCreatedByOutput {
	return o.ApplyT(func(v *PortalCreatedBy) PortalCreatedBy {
		if v != nil {
			return *v
		}
		var ret PortalCreatedBy
		return ret
	}).(PortalCreatedByOutput)
}

// The email of the user.
func (o PortalCreatedByPtrOutput) Email() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PortalCreatedBy) *string {
		if v == nil {
			return nil
		}
		return v.Email
	}).(pulumi.StringPtrOutput)
}

// The name of the user.
func (o PortalCreatedByPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PortalCreatedBy) *string {
		if v == nil {
			return nil
		}
		return v.Name
	}).(pulumi.StringPtrOutput)
}

// The UUID of the user.
func (o PortalCreatedByPtrOutput) Uuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PortalCreatedBy) *string {
		if v == nil {
			return nil
		}
		return v.Uuid
	}).(pulumi.StringPtrOutput)
}

type GetMembersMember struct {
	// The email address of the organization member.
	Email string `pulumi:"email"`
	// The GraphQL ID of the organization member.
	Id string `pulumi:"id"`
	// The name of the organization member.
	Name string `pulumi:"name"`
	// The UUID of the organization member.
	Uuid string `pulumi:"uuid"`
}

// GetMembersMemberInput is an input type that accepts GetMembersMemberArgs and GetMembersMemberOutput values.
// You can construct a concrete instance of `GetMembersMemberInput` via:
//
//	GetMembersMemberArgs{...}
type GetMembersMemberInput interface {
	pulumi.Input

	ToGetMembersMemberOutput() GetMembersMemberOutput
	ToGetMembersMemberOutputWithContext(context.Context) GetMembersMemberOutput
}

type GetMembersMemberArgs struct {
	// The email address of the organization member.
	Email pulumi.StringInput `pulumi:"email"`
	// The GraphQL ID of the organization member.
	Id pulumi.StringInput `pulumi:"id"`
	// The name of the organization member.
	Name pulumi.StringInput `pulumi:"name"`
	// The UUID of the organization member.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetMembersMemberArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMembersMember)(nil)).Elem()
}

func (i GetMembersMemberArgs) ToGetMembersMemberOutput() GetMembersMemberOutput {
	return i.ToGetMembersMemberOutputWithContext(context.Background())
}

func (i GetMembersMemberArgs) ToGetMembersMemberOutputWithContext(ctx context.Context) GetMembersMemberOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetMembersMemberOutput)
}

// GetMembersMemberArrayInput is an input type that accepts GetMembersMemberArray and GetMembersMemberArrayOutput values.
// You can construct a concrete instance of `GetMembersMemberArrayInput` via:
//
//	GetMembersMemberArray{ GetMembersMemberArgs{...} }
type GetMembersMemberArrayInput interface {
	pulumi.Input

	ToGetMembersMemberArrayOutput() GetMembersMemberArrayOutput
	ToGetMembersMemberArrayOutputWithContext(context.Context) GetMembersMemberArrayOutput
}

type GetMembersMemberArray []GetMembersMemberInput

func (GetMembersMemberArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetMembersMember)(nil)).Elem()
}

func (i GetMembersMemberArray) ToGetMembersMemberArrayOutput() GetMembersMemberArrayOutput {
	return i.ToGetMembersMemberArrayOutputWithContext(context.Background())
}

func (i GetMembersMemberArray) ToGetMembersMemberArrayOutputWithContext(ctx context.Context) GetMembersMemberArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetMembersMemberArrayOutput)
}

type GetMembersMemberOutput struct{ *pulumi.OutputState }

func (GetMembersMemberOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMembersMember)(nil)).Elem()
}

func (o GetMembersMemberOutput) ToGetMembersMemberOutput() GetMembersMemberOutput {
	return o
}

func (o GetMembersMemberOutput) ToGetMembersMemberOutputWithContext(ctx context.Context) GetMembersMemberOutput {
	return o
}

// The email address of the organization member.
func (o GetMembersMemberOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetMembersMember) string { return v.Email }).(pulumi.StringOutput)
}

// The GraphQL ID of the organization member.
func (o GetMembersMemberOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMembersMember) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the organization member.
func (o GetMembersMemberOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetMembersMember) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the organization member.
func (o GetMembersMemberOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetMembersMember) string { return v.Uuid }).(pulumi.StringOutput)
}

type GetMembersMemberArrayOutput struct{ *pulumi.OutputState }

func (GetMembersMemberArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetMembersMember)(nil)).Elem()
}

func (o GetMembersMemberArrayOutput) ToGetMembersMemberArrayOutput() GetMembersMemberArrayOutput {
	return o
}

func (o GetMembersMemberArrayOutput) ToGetMembersMemberArrayOutputWithContext(ctx context.Context) GetMembersMemberArrayOutput {
	return o
}

func (o GetMembersMemberArrayOutput) Index(i pulumi.IntInput) GetMembersMemberOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetMembersMember {
		return vs[0].([]GetMembersMember)[vs[1].(int)]
	}).(GetMembersMemberOutput)
}

type GetPortalCreatedBy struct {
	// The email of the user.
	Email string `pulumi:"email"`
	// The name of the user.
	Name string `pulumi:"name"`
	// The UUID of the user.
	Uuid string `pulumi:"uuid"`
}

// GetPortalCreatedByInput is an input type that accepts GetPortalCreatedByArgs and GetPortalCreatedByOutput values.
// You can construct a concrete instance of `GetPortalCreatedByInput` via:
//
//	GetPortalCreatedByArgs{...}
type GetPortalCreatedByInput interface {
	pulumi.Input

	ToGetPortalCreatedByOutput() GetPortalCreatedByOutput
	ToGetPortalCreatedByOutputWithContext(context.Context) GetPortalCreatedByOutput
}

type GetPortalCreatedByArgs struct {
	// The email of the user.
	Email pulumi.StringInput `pulumi:"email"`
	// The name of the user.
	Name pulumi.StringInput `pulumi:"name"`
	// The UUID of the user.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetPortalCreatedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalCreatedBy)(nil)).Elem()
}

func (i GetPortalCreatedByArgs) ToGetPortalCreatedByOutput() GetPortalCreatedByOutput {
	return i.ToGetPortalCreatedByOutputWithContext(context.Background())
}

func (i GetPortalCreatedByArgs) ToGetPortalCreatedByOutputWithContext(ctx context.Context) GetPortalCreatedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPortalCreatedByOutput)
}

type GetPortalCreatedByOutput struct{ *pulumi.OutputState }

func (GetPortalCreatedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalCreatedBy)(nil)).Elem()
}

func (o GetPortalCreatedByOutput) ToGetPortalCreatedByOutput() GetPortalCreatedByOutput {
	return o
}

func (o GetPortalCreatedByOutput) ToGetPortalCreatedByOutputWithContext(ctx context.Context) GetPortalCreatedByOutput {
	return o
}

// The email of the user.
func (o GetPortalCreatedByOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalCreatedBy) string { return v.Email }).(pulumi.StringOutput)
}

// The name of the user.
func (o GetPortalCreatedByOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalCreatedBy) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the user.
func (o GetPortalCreatedByOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalCreatedBy) string { return v.Uuid }).(pulumi.StringOutput)
}

type GetPortalsPortal struct {
	// Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal.
	AllowedIpAddresses string `pulumi:"allowedIpAddresses"`
	// The time when the portal was created.
	CreatedAt string `pulumi:"createdAt"`
	// Information about the user who created the portal.
	CreatedBy GetPortalsPortalCreatedBy `pulumi:"createdBy"`
	// The description of the portal.
	Description string `pulumi:"description"`
	// The name of the portal.
	Name string `pulumi:"name"`
	// The GraphQL query that the portal executes.
	Query string `pulumi:"query"`
	// The slug of the portal.
	Slug string `pulumi:"slug"`
	// Whether users can invoke the portal.
	UserInvokable bool `pulumi:"userInvokable"`
	// The UUID of the portal.
	Uuid string `pulumi:"uuid"`
}

// GetPortalsPortalInput is an input type that accepts GetPortalsPortalArgs and GetPortalsPortalOutput values.
// You can construct a concrete instance of `GetPortalsPortalInput` via:
//
//	GetPortalsPortalArgs{...}
type GetPortalsPortalInput interface {
	pulumi.Input

	ToGetPortalsPortalOutput() GetPortalsPortalOutput
	ToGetPortalsPortalOutputWithContext(context.Context) GetPortalsPortalOutput
}

type GetPortalsPortalArgs struct {
	// Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal.
	AllowedIpAddresses pulumi.StringInput `pulumi:"allowedIpAddresses"`
	// The time when the portal was created.
	CreatedAt pulumi.StringInput `pulumi:"createdAt"`
	// Information about the user who created the portal.
	CreatedBy GetPortalsPortalCreatedByInput `pulumi:"createdBy"`
	// The description of the portal.
	Description pulumi.StringInput `pulumi:"description"`
	// The name of the portal.
	Name pulumi.StringInput `pulumi:"name"`
	// The GraphQL query that the portal executes.
	Query pulumi.StringInput `pulumi:"query"`
	// The slug of the portal.
	Slug pulumi.StringInput `pulumi:"slug"`
	// Whether users can invoke the portal.
	UserInvokable pulumi.BoolInput `pulumi:"userInvokable"`
	// The UUID of the portal.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetPortalsPortalArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalsPortal)(nil)).Elem()
}

func (i GetPortalsPortalArgs) ToGetPortalsPortalOutput() GetPortalsPortalOutput {
	return i.ToGetPortalsPortalOutputWithContext(context.Background())
}

func (i GetPortalsPortalArgs) ToGetPortalsPortalOutputWithContext(ctx context.Context) GetPortalsPortalOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPortalsPortalOutput)
}

// GetPortalsPortalArrayInput is an input type that accepts GetPortalsPortalArray and GetPortalsPortalArrayOutput values.
// You can construct a concrete instance of `GetPortalsPortalArrayInput` via:
//
//	GetPortalsPortalArray{ GetPortalsPortalArgs{...} }
type GetPortalsPortalArrayInput interface {
	pulumi.Input

	ToGetPortalsPortalArrayOutput() GetPortalsPortalArrayOutput
	ToGetPortalsPortalArrayOutputWithContext(context.Context) GetPortalsPortalArrayOutput
}

type GetPortalsPortalArray []GetPortalsPortalInput

func (GetPortalsPortalArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPortalsPortal)(nil)).Elem()
}

func (i GetPortalsPortalArray) ToGetPortalsPortalArrayOutput() GetPortalsPortalArrayOutput {
	return i.ToGetPortalsPortalArrayOutputWithContext(context.Background())
}

func (i GetPortalsPortalArray) ToGetPortalsPortalArrayOutputWithContext(ctx context.Context) GetPortalsPortalArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPortalsPortalArrayOutput)
}

type GetPortalsPortalOutput struct{ *pulumi.OutputState }

func (GetPortalsPortalOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalsPortal)(nil)).Elem()
}

func (o GetPortalsPortalOutput) ToGetPortalsPortalOutput() GetPortalsPortalOutput {
	return o
}

func (o GetPortalsPortalOutput) ToGetPortalsPortalOutputWithContext(ctx context.Context) GetPortalsPortalOutput {
	return o
}

// Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal.
func (o GetPortalsPortalOutput) AllowedIpAddresses() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortal) string { return v.AllowedIpAddresses }).(pulumi.StringOutput)
}

// The time when the portal was created.
func (o GetPortalsPortalOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortal) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Information about the user who created the portal.
func (o GetPortalsPortalOutput) CreatedBy() GetPortalsPortalCreatedByOutput {
	return o.ApplyT(func(v GetPortalsPortal) GetPortalsPortalCreatedBy { return v.CreatedBy }).(GetPortalsPortalCreatedByOutput)
}

// The description of the portal.
func (o GetPortalsPortalOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortal) string { return v.Description }).(pulumi.StringOutput)
}

// The name of the portal.
func (o GetPortalsPortalOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortal) string { return v.Name }).(pulumi.StringOutput)
}

// The GraphQL query that the portal executes.
func (o GetPortalsPortalOutput) Query() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortal) string { return v.Query }).(pulumi.StringOutput)
}

// The slug of the portal.
func (o GetPortalsPortalOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortal) string { return v.Slug }).(pulumi.StringOutput)
}

// Whether users can invoke the portal.
func (o GetPortalsPortalOutput) UserInvokable() pulumi.BoolOutput {
	return o.ApplyT(func(v GetPortalsPortal) bool { return v.UserInvokable }).(pulumi.BoolOutput)
}

// The UUID of the portal.
func (o GetPortalsPortalOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortal) string { return v.Uuid }).(pulumi.StringOutput)
}

type GetPortalsPortalArrayOutput struct{ *pulumi.OutputState }

func (GetPortalsPortalArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPortalsPortal)(nil)).Elem()
}

func (o GetPortalsPortalArrayOutput) ToGetPortalsPortalArrayOutput() GetPortalsPortalArrayOutput {
	return o
}

func (o GetPortalsPortalArrayOutput) ToGetPortalsPortalArrayOutputWithContext(ctx context.Context) GetPortalsPortalArrayOutput {
	return o
}

func (o GetPortalsPortalArrayOutput) Index(i pulumi.IntInput) GetPortalsPortalOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPortalsPortal {
		return vs[0].([]GetPortalsPortal)[vs[1].(int)]
	}).(GetPortalsPortalOutput)
}

type GetPortalsPortalCreatedBy struct {
	// The email of the user.
	Email string `pulumi:"email"`
	// The name of the user.
	Name string `pulumi:"name"`
	// The UUID of the user.
	Uuid string `pulumi:"uuid"`
}

// GetPortalsPortalCreatedByInput is an input type that accepts GetPortalsPortalCreatedByArgs and GetPortalsPortalCreatedByOutput values.
// You can construct a concrete instance of `GetPortalsPortalCreatedByInput` via:
//
//	GetPortalsPortalCreatedByArgs{...}
type GetPortalsPortalCreatedByInput interface {
	pulumi.Input

	ToGetPortalsPortalCreatedByOutput() GetPortalsPortalCreatedByOutput
	ToGetPortalsPortalCreatedByOutputWithContext(context.Context) GetPortalsPortalCreatedByOutput
}

type GetPortalsPortalCreatedByArgs struct {
	// The email of the user.
	Email pulumi.StringInput `pulumi:"email"`
	// The name of the user.
	Name pulumi.StringInput `pulumi:"name"`
	// The UUID of the user.
	Uuid pulumi.StringInput `pulumi:"uuid"`
}

func (GetPortalsPortalCreatedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalsPortalCreatedBy)(nil)).Elem()
}

func (i GetPortalsPortalCreatedByArgs) ToGetPortalsPortalCreatedByOutput() GetPortalsPortalCreatedByOutput {
	return i.ToGetPortalsPortalCreatedByOutputWithContext(context.Background())
}

func (i GetPortalsPortalCreatedByArgs) ToGetPortalsPortalCreatedByOutputWithContext(ctx context.Context) GetPortalsPortalCreatedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPortalsPortalCreatedByOutput)
}

type GetPortalsPortalCreatedByOutput struct{ *pulumi.OutputState }

func (GetPortalsPortalCreatedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPortalsPortalCreatedBy)(nil)).Elem()
}

func (o GetPortalsPortalCreatedByOutput) ToGetPortalsPortalCreatedByOutput() GetPortalsPortalCreatedByOutput {
	return o
}

func (o GetPortalsPortalCreatedByOutput) ToGetPortalsPortalCreatedByOutputWithContext(ctx context.Context) GetPortalsPortalCreatedByOutput {
	return o
}

// The email of the user.
func (o GetPortalsPortalCreatedByOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortalCreatedBy) string { return v.Email }).(pulumi.StringOutput)
}

// The name of the user.
func (o GetPortalsPortalCreatedByOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortalCreatedBy) string { return v.Name }).(pulumi.StringOutput)
}

// The UUID of the user.
func (o GetPortalsPortalCreatedByOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetPortalsPortalCreatedBy) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PortalCreatedByInput)(nil)).Elem(), PortalCreatedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PortalCreatedByPtrInput)(nil)).Elem(), PortalCreatedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetMembersMemberInput)(nil)).Elem(), GetMembersMemberArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetMembersMemberArrayInput)(nil)).Elem(), GetMembersMemberArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPortalCreatedByInput)(nil)).Elem(), GetPortalCreatedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPortalsPortalInput)(nil)).Elem(), GetPortalsPortalArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPortalsPortalArrayInput)(nil)).Elem(), GetPortalsPortalArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPortalsPortalCreatedByInput)(nil)).Elem(), GetPortalsPortalCreatedByArgs{})
	pulumi.RegisterOutputType(PortalCreatedByOutput{})
	pulumi.RegisterOutputType(PortalCreatedByPtrOutput{})
	pulumi.RegisterOutputType(GetMembersMemberOutput{})
	pulumi.RegisterOutputType(GetMembersMemberArrayOutput{})
	pulumi.RegisterOutputType(GetPortalCreatedByOutput{})
	pulumi.RegisterOutputType(GetPortalsPortalOutput{})
	pulumi.RegisterOutputType(GetPortalsPortalArrayOutput{})
	pulumi.RegisterOutputType(GetPortalsPortalCreatedByOutput{})
}
