// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package organization

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/internal"
)

// This resource allows you to create and manage a Buildkite Registry.
// Find out more information in our [documentation](https://buildkite.com/docs/package-registries).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-buildkite/sdk/v3/go/buildkite/organization"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := organization.NewRegistry(ctx, "example", &organization.RegistryArgs{
//				Name:        pulumi.String("example"),
//				Description: pulumi.String("super cool ruby registry"),
//				Ecosystem:   pulumi.String("ruby"),
//				Emoji:       pulumi.String(":ruby:"),
//				Color:       pulumi.String("#ff0000"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Registry struct {
	pulumi.CustomResourceState

	// A color representation of the registry. Accepts hex codes, eg #BADA55.
	Color pulumi.StringPtrOutput `pulumi:"color"`
	// This is a description for the registry, this may describe the usage for it, the region, or something else
	// which would help identify the registry's purpose.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The ecosystem of the registry. **Warning:** This value cannot be changed after creation. Any attempts to update this field will result in API errors.
	Ecosystem pulumi.StringOutput `pulumi:"ecosystem"`
	// An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
	// emoji itself, such as 🚀.
	Emoji pulumi.StringPtrOutput `pulumi:"emoji"`
	// The name of the registry. Can only contain numbers and letters, no spaces or special characters.
	Name pulumi.StringOutput `pulumi:"name"`
	// The registry's OIDC policy.
	OidcPolicy pulumi.StringPtrOutput `pulumi:"oidcPolicy"`
	// The slug of the registry.
	Slug pulumi.StringOutput `pulumi:"slug"`
	// The team IDs that have access to the registry.
	TeamIds pulumi.StringArrayOutput `pulumi:"teamIds"`
	// The UUID of the registry.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
}

// NewRegistry registers a new resource with the given unique name, arguments, and options.
func NewRegistry(ctx *pulumi.Context,
	name string, args *RegistryArgs, opts ...pulumi.ResourceOption) (*Registry, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Ecosystem == nil {
		return nil, errors.New("invalid value for required argument 'Ecosystem'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Registry
	err := ctx.RegisterResource("buildkite:Organization/registry:Registry", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRegistry gets an existing Registry resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRegistry(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RegistryState, opts ...pulumi.ResourceOption) (*Registry, error) {
	var resource Registry
	err := ctx.ReadResource("buildkite:Organization/registry:Registry", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Registry resources.
type registryState struct {
	// A color representation of the registry. Accepts hex codes, eg #BADA55.
	Color *string `pulumi:"color"`
	// This is a description for the registry, this may describe the usage for it, the region, or something else
	// which would help identify the registry's purpose.
	Description *string `pulumi:"description"`
	// The ecosystem of the registry. **Warning:** This value cannot be changed after creation. Any attempts to update this field will result in API errors.
	Ecosystem *string `pulumi:"ecosystem"`
	// An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
	// emoji itself, such as 🚀.
	Emoji *string `pulumi:"emoji"`
	// The name of the registry. Can only contain numbers and letters, no spaces or special characters.
	Name *string `pulumi:"name"`
	// The registry's OIDC policy.
	OidcPolicy *string `pulumi:"oidcPolicy"`
	// The slug of the registry.
	Slug *string `pulumi:"slug"`
	// The team IDs that have access to the registry.
	TeamIds []string `pulumi:"teamIds"`
	// The UUID of the registry.
	Uuid *string `pulumi:"uuid"`
}

type RegistryState struct {
	// A color representation of the registry. Accepts hex codes, eg #BADA55.
	Color pulumi.StringPtrInput
	// This is a description for the registry, this may describe the usage for it, the region, or something else
	// which would help identify the registry's purpose.
	Description pulumi.StringPtrInput
	// The ecosystem of the registry. **Warning:** This value cannot be changed after creation. Any attempts to update this field will result in API errors.
	Ecosystem pulumi.StringPtrInput
	// An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
	// emoji itself, such as 🚀.
	Emoji pulumi.StringPtrInput
	// The name of the registry. Can only contain numbers and letters, no spaces or special characters.
	Name pulumi.StringPtrInput
	// The registry's OIDC policy.
	OidcPolicy pulumi.StringPtrInput
	// The slug of the registry.
	Slug pulumi.StringPtrInput
	// The team IDs that have access to the registry.
	TeamIds pulumi.StringArrayInput
	// The UUID of the registry.
	Uuid pulumi.StringPtrInput
}

func (RegistryState) ElementType() reflect.Type {
	return reflect.TypeOf((*registryState)(nil)).Elem()
}

type registryArgs struct {
	// A color representation of the registry. Accepts hex codes, eg #BADA55.
	Color *string `pulumi:"color"`
	// This is a description for the registry, this may describe the usage for it, the region, or something else
	// which would help identify the registry's purpose.
	Description *string `pulumi:"description"`
	// The ecosystem of the registry. **Warning:** This value cannot be changed after creation. Any attempts to update this field will result in API errors.
	Ecosystem string `pulumi:"ecosystem"`
	// An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
	// emoji itself, such as 🚀.
	Emoji *string `pulumi:"emoji"`
	// The name of the registry. Can only contain numbers and letters, no spaces or special characters.
	Name *string `pulumi:"name"`
	// The registry's OIDC policy.
	OidcPolicy *string `pulumi:"oidcPolicy"`
	// The team IDs that have access to the registry.
	TeamIds []string `pulumi:"teamIds"`
}

// The set of arguments for constructing a Registry resource.
type RegistryArgs struct {
	// A color representation of the registry. Accepts hex codes, eg #BADA55.
	Color pulumi.StringPtrInput
	// This is a description for the registry, this may describe the usage for it, the region, or something else
	// which would help identify the registry's purpose.
	Description pulumi.StringPtrInput
	// The ecosystem of the registry. **Warning:** This value cannot be changed after creation. Any attempts to update this field will result in API errors.
	Ecosystem pulumi.StringInput
	// An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
	// emoji itself, such as 🚀.
	Emoji pulumi.StringPtrInput
	// The name of the registry. Can only contain numbers and letters, no spaces or special characters.
	Name pulumi.StringPtrInput
	// The registry's OIDC policy.
	OidcPolicy pulumi.StringPtrInput
	// The team IDs that have access to the registry.
	TeamIds pulumi.StringArrayInput
}

func (RegistryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*registryArgs)(nil)).Elem()
}

type RegistryInput interface {
	pulumi.Input

	ToRegistryOutput() RegistryOutput
	ToRegistryOutputWithContext(ctx context.Context) RegistryOutput
}

func (*Registry) ElementType() reflect.Type {
	return reflect.TypeOf((**Registry)(nil)).Elem()
}

func (i *Registry) ToRegistryOutput() RegistryOutput {
	return i.ToRegistryOutputWithContext(context.Background())
}

func (i *Registry) ToRegistryOutputWithContext(ctx context.Context) RegistryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegistryOutput)
}

// RegistryArrayInput is an input type that accepts RegistryArray and RegistryArrayOutput values.
// You can construct a concrete instance of `RegistryArrayInput` via:
//
//	RegistryArray{ RegistryArgs{...} }
type RegistryArrayInput interface {
	pulumi.Input

	ToRegistryArrayOutput() RegistryArrayOutput
	ToRegistryArrayOutputWithContext(context.Context) RegistryArrayOutput
}

type RegistryArray []RegistryInput

func (RegistryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Registry)(nil)).Elem()
}

func (i RegistryArray) ToRegistryArrayOutput() RegistryArrayOutput {
	return i.ToRegistryArrayOutputWithContext(context.Background())
}

func (i RegistryArray) ToRegistryArrayOutputWithContext(ctx context.Context) RegistryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegistryArrayOutput)
}

// RegistryMapInput is an input type that accepts RegistryMap and RegistryMapOutput values.
// You can construct a concrete instance of `RegistryMapInput` via:
//
//	RegistryMap{ "key": RegistryArgs{...} }
type RegistryMapInput interface {
	pulumi.Input

	ToRegistryMapOutput() RegistryMapOutput
	ToRegistryMapOutputWithContext(context.Context) RegistryMapOutput
}

type RegistryMap map[string]RegistryInput

func (RegistryMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Registry)(nil)).Elem()
}

func (i RegistryMap) ToRegistryMapOutput() RegistryMapOutput {
	return i.ToRegistryMapOutputWithContext(context.Background())
}

func (i RegistryMap) ToRegistryMapOutputWithContext(ctx context.Context) RegistryMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegistryMapOutput)
}

type RegistryOutput struct{ *pulumi.OutputState }

func (RegistryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Registry)(nil)).Elem()
}

func (o RegistryOutput) ToRegistryOutput() RegistryOutput {
	return o
}

func (o RegistryOutput) ToRegistryOutputWithContext(ctx context.Context) RegistryOutput {
	return o
}

// A color representation of the registry. Accepts hex codes, eg #BADA55.
func (o RegistryOutput) Color() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringPtrOutput { return v.Color }).(pulumi.StringPtrOutput)
}

// This is a description for the registry, this may describe the usage for it, the region, or something else
// which would help identify the registry's purpose.
func (o RegistryOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The ecosystem of the registry. **Warning:** This value cannot be changed after creation. Any attempts to update this field will result in API errors.
func (o RegistryOutput) Ecosystem() pulumi.StringOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringOutput { return v.Ecosystem }).(pulumi.StringOutput)
}

// An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
// emoji itself, such as 🚀.
func (o RegistryOutput) Emoji() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringPtrOutput { return v.Emoji }).(pulumi.StringPtrOutput)
}

// The name of the registry. Can only contain numbers and letters, no spaces or special characters.
func (o RegistryOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The registry's OIDC policy.
func (o RegistryOutput) OidcPolicy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringPtrOutput { return v.OidcPolicy }).(pulumi.StringPtrOutput)
}

// The slug of the registry.
func (o RegistryOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringOutput { return v.Slug }).(pulumi.StringOutput)
}

// The team IDs that have access to the registry.
func (o RegistryOutput) TeamIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringArrayOutput { return v.TeamIds }).(pulumi.StringArrayOutput)
}

// The UUID of the registry.
func (o RegistryOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *Registry) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

type RegistryArrayOutput struct{ *pulumi.OutputState }

func (RegistryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Registry)(nil)).Elem()
}

func (o RegistryArrayOutput) ToRegistryArrayOutput() RegistryArrayOutput {
	return o
}

func (o RegistryArrayOutput) ToRegistryArrayOutputWithContext(ctx context.Context) RegistryArrayOutput {
	return o
}

func (o RegistryArrayOutput) Index(i pulumi.IntInput) RegistryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Registry {
		return vs[0].([]*Registry)[vs[1].(int)]
	}).(RegistryOutput)
}

type RegistryMapOutput struct{ *pulumi.OutputState }

func (RegistryMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Registry)(nil)).Elem()
}

func (o RegistryMapOutput) ToRegistryMapOutput() RegistryMapOutput {
	return o
}

func (o RegistryMapOutput) ToRegistryMapOutputWithContext(ctx context.Context) RegistryMapOutput {
	return o
}

func (o RegistryMapOutput) MapIndex(k pulumi.StringInput) RegistryOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Registry {
		return vs[0].(map[string]*Registry)[vs[1].(string)]
	}).(RegistryOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RegistryInput)(nil)).Elem(), &Registry{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegistryArrayInput)(nil)).Elem(), RegistryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegistryMapInput)(nil)).Elem(), RegistryMap{})
	pulumi.RegisterOutputType(RegistryOutput{})
	pulumi.RegisterOutputType(RegistryArrayOutput{})
	pulumi.RegisterOutputType(RegistryMapOutput{})
}
