name: Upload SDK asset
description: Upload the SDK for a specific language as an asset for the workflow.

runs:
  using: "composite"
  steps:
    - name: Capture executable permissions
      shell: bash
      run: find bin -type f -executable > bin/executables.txt

    - name: Upload prerequisites bin
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: prerequisites-bin
        path: bin/*
        retention-days: 30

    - name: Upload schema-embed.json
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: schema-embed.json
        path: provider/cmd/pulumi-resource-buildkite/schema-embed.json
        retention-days: 30
