// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.TestSuite.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TestSuiteState extends com.pulumi.resources.ResourceArgs {

    public static final TestSuiteState Empty = new TestSuiteState();

    /**
     * The API token to use to send test run data to the API.
     * 
     */
    @Import(name="apiToken")
    private @Nullable Output<String> apiToken;

    /**
     * @return The API token to use to send test run data to the API.
     * 
     */
    public Optional<Output<String>> apiToken() {
        return Optional.ofNullable(this.apiToken);
    }

    /**
     * The name of the application this test suite is for. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
     * 
     */
    @Import(name="applicationName")
    private @Nullable Output<String> applicationName;

    /**
     * @return The name of the application this test suite is for. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
     * 
     */
    public Optional<Output<String>> applicationName() {
        return Optional.ofNullable(this.applicationName);
    }

    /**
     * The hex color code for the test suite navatar, eg #BADA55. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
     * 
     */
    @Import(name="color")
    private @Nullable Output<String> color;

    /**
     * @return The hex color code for the test suite navatar, eg #BADA55. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
     * 
     */
    public Optional<Output<String>> color() {
        return Optional.ofNullable(this.color);
    }

    /**
     * The default branch for the repository this test suite is for.
     * 
     */
    @Import(name="defaultBranch")
    private @Nullable Output<String> defaultBranch;

    /**
     * @return The default branch for the repository this test suite is for.
     * 
     */
    public Optional<Output<String>> defaultBranch() {
        return Optional.ofNullable(this.defaultBranch);
    }

    /**
     * The emoji associated with this test suite, eg :buildkite:
     * 
     */
    @Import(name="emoji")
    private @Nullable Output<String> emoji;

    /**
     * @return The emoji associated with this test suite, eg :buildkite:
     * 
     */
    public Optional<Output<String>> emoji() {
        return Optional.ofNullable(this.emoji);
    }

    /**
     * The name to give the test suite.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name to give the test suite.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The [OIDC policy](https://buildkite.com/docs/pipelines/configure/tests/test-collection/oidc) for the test suite, as a YAML or JSON string. This policy defines which OIDC tokens can be exchanged for suite access, as an alternative to the suite API token. If omitted, the policy is left unmanaged by Terraform; set it to an empty string to remove an existing policy.
     * 
     */
    @Import(name="oidcPolicy")
    private @Nullable Output<String> oidcPolicy;

    /**
     * @return The [OIDC policy](https://buildkite.com/docs/pipelines/configure/tests/test-collection/oidc) for the test suite, as a YAML or JSON string. This policy defines which OIDC tokens can be exchanged for suite access, as an alternative to the suite API token. If omitted, the policy is left unmanaged by Terraform; set it to an empty string to remove an existing policy.
     * 
     */
    public Optional<Output<String>> oidcPolicy() {
        return Optional.ofNullable(this.oidcPolicy);
    }

    /**
     * The generated slug of the test suite.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return The generated slug of the test suite.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    /**
     * The GraphQL ID of the team to mark as the owner/admin of the test suite.
     * 
     */
    @Import(name="teamOwnerId")
    private @Nullable Output<String> teamOwnerId;

    /**
     * @return The GraphQL ID of the team to mark as the owner/admin of the test suite.
     * 
     */
    public Optional<Output<String>> teamOwnerId() {
        return Optional.ofNullable(this.teamOwnerId);
    }

    /**
     * The UUID of the test suite.
     * 
     */
    @Import(name="uuid")
    private @Nullable Output<String> uuid;

    /**
     * @return The UUID of the test suite.
     * 
     */
    public Optional<Output<String>> uuid() {
        return Optional.ofNullable(this.uuid);
    }

    private TestSuiteState() {}

    private TestSuiteState(TestSuiteState $) {
        this.apiToken = $.apiToken;
        this.applicationName = $.applicationName;
        this.color = $.color;
        this.defaultBranch = $.defaultBranch;
        this.emoji = $.emoji;
        this.name = $.name;
        this.oidcPolicy = $.oidcPolicy;
        this.slug = $.slug;
        this.teamOwnerId = $.teamOwnerId;
        this.uuid = $.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TestSuiteState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TestSuiteState $;

        public Builder() {
            $ = new TestSuiteState();
        }

        public Builder(TestSuiteState defaults) {
            $ = new TestSuiteState(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiToken The API token to use to send test run data to the API.
         * 
         * @return builder
         * 
         */
        public Builder apiToken(@Nullable Output<String> apiToken) {
            $.apiToken = apiToken;
            return this;
        }

        /**
         * @param apiToken The API token to use to send test run data to the API.
         * 
         * @return builder
         * 
         */
        public Builder apiToken(String apiToken) {
            return apiToken(Output.of(apiToken));
        }

        /**
         * @param applicationName The name of the application this test suite is for. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
         * 
         * @return builder
         * 
         */
        public Builder applicationName(@Nullable Output<String> applicationName) {
            $.applicationName = applicationName;
            return this;
        }

        /**
         * @param applicationName The name of the application this test suite is for. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
         * 
         * @return builder
         * 
         */
        public Builder applicationName(String applicationName) {
            return applicationName(Output.of(applicationName));
        }

        /**
         * @param color The hex color code for the test suite navatar, eg #BADA55. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
         * 
         * @return builder
         * 
         */
        public Builder color(@Nullable Output<String> color) {
            $.color = color;
            return this;
        }

        /**
         * @param color The hex color code for the test suite navatar, eg #BADA55. If omitted, the value is left unmanaged by Terraform; set it to an empty string to clear it.
         * 
         * @return builder
         * 
         */
        public Builder color(String color) {
            return color(Output.of(color));
        }

        /**
         * @param defaultBranch The default branch for the repository this test suite is for.
         * 
         * @return builder
         * 
         */
        public Builder defaultBranch(@Nullable Output<String> defaultBranch) {
            $.defaultBranch = defaultBranch;
            return this;
        }

        /**
         * @param defaultBranch The default branch for the repository this test suite is for.
         * 
         * @return builder
         * 
         */
        public Builder defaultBranch(String defaultBranch) {
            return defaultBranch(Output.of(defaultBranch));
        }

        /**
         * @param emoji The emoji associated with this test suite, eg :buildkite:
         * 
         * @return builder
         * 
         */
        public Builder emoji(@Nullable Output<String> emoji) {
            $.emoji = emoji;
            return this;
        }

        /**
         * @param emoji The emoji associated with this test suite, eg :buildkite:
         * 
         * @return builder
         * 
         */
        public Builder emoji(String emoji) {
            return emoji(Output.of(emoji));
        }

        /**
         * @param name The name to give the test suite.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name to give the test suite.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param oidcPolicy The [OIDC policy](https://buildkite.com/docs/pipelines/configure/tests/test-collection/oidc) for the test suite, as a YAML or JSON string. This policy defines which OIDC tokens can be exchanged for suite access, as an alternative to the suite API token. If omitted, the policy is left unmanaged by Terraform; set it to an empty string to remove an existing policy.
         * 
         * @return builder
         * 
         */
        public Builder oidcPolicy(@Nullable Output<String> oidcPolicy) {
            $.oidcPolicy = oidcPolicy;
            return this;
        }

        /**
         * @param oidcPolicy The [OIDC policy](https://buildkite.com/docs/pipelines/configure/tests/test-collection/oidc) for the test suite, as a YAML or JSON string. This policy defines which OIDC tokens can be exchanged for suite access, as an alternative to the suite API token. If omitted, the policy is left unmanaged by Terraform; set it to an empty string to remove an existing policy.
         * 
         * @return builder
         * 
         */
        public Builder oidcPolicy(String oidcPolicy) {
            return oidcPolicy(Output.of(oidcPolicy));
        }

        /**
         * @param slug The generated slug of the test suite.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug The generated slug of the test suite.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        /**
         * @param teamOwnerId The GraphQL ID of the team to mark as the owner/admin of the test suite.
         * 
         * @return builder
         * 
         */
        public Builder teamOwnerId(@Nullable Output<String> teamOwnerId) {
            $.teamOwnerId = teamOwnerId;
            return this;
        }

        /**
         * @param teamOwnerId The GraphQL ID of the team to mark as the owner/admin of the test suite.
         * 
         * @return builder
         * 
         */
        public Builder teamOwnerId(String teamOwnerId) {
            return teamOwnerId(Output.of(teamOwnerId));
        }

        /**
         * @param uuid The UUID of the test suite.
         * 
         * @return builder
         * 
         */
        public Builder uuid(@Nullable Output<String> uuid) {
            $.uuid = uuid;
            return this;
        }

        /**
         * @param uuid The UUID of the test suite.
         * 
         * @return builder
         * 
         */
        public Builder uuid(String uuid) {
            return uuid(Output.of(uuid));
        }

        public TestSuiteState build() {
            return $;
        }
    }

}
