// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Pipeline.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetTemplateResult {
    /**
     * @return If the pipeline template is available for assignment by non admin users.
     * 
     */
    private Boolean available;
    /**
     * @return The YAML step configuration for the pipeline template.
     * 
     */
    private String configuration;
    /**
     * @return The description for the pipeline template.
     * 
     */
    private String description;
    /**
     * @return The GraphQL ID of the pipeline template.
     * 
     */
    private String id;
    /**
     * @return The name of the pipeline template.
     * 
     */
    private String name;
    /**
     * @return The UUID of the pipeline template.
     * 
     */
    private String uuid;

    private GetTemplateResult() {}
    /**
     * @return If the pipeline template is available for assignment by non admin users.
     * 
     */
    public Boolean available() {
        return this.available;
    }
    /**
     * @return The YAML step configuration for the pipeline template.
     * 
     */
    public String configuration() {
        return this.configuration;
    }
    /**
     * @return The description for the pipeline template.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The GraphQL ID of the pipeline template.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the pipeline template.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The UUID of the pipeline template.
     * 
     */
    public String uuid() {
        return this.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTemplateResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean available;
        private String configuration;
        private String description;
        private String id;
        private String name;
        private String uuid;
        public Builder() {}
        public Builder(GetTemplateResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.available = defaults.available;
    	      this.configuration = defaults.configuration;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.uuid = defaults.uuid;
        }

        @CustomType.Setter
        public Builder available(Boolean available) {
            if (available == null) {
              throw new MissingRequiredPropertyException("GetTemplateResult", "available");
            }
            this.available = available;
            return this;
        }
        @CustomType.Setter
        public Builder configuration(String configuration) {
            if (configuration == null) {
              throw new MissingRequiredPropertyException("GetTemplateResult", "configuration");
            }
            this.configuration = configuration;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetTemplateResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTemplateResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTemplateResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder uuid(String uuid) {
            if (uuid == null) {
              throw new MissingRequiredPropertyException("GetTemplateResult", "uuid");
            }
            this.uuid = uuid;
            return this;
        }
        public GetTemplateResult build() {
            final var _resultValue = new GetTemplateResult();
            _resultValue.available = available;
            _resultValue.configuration = configuration;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.uuid = uuid;
            return _resultValue;
        }
    }
}
