// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Organization.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRegistryPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRegistryPlainArgs Empty = new GetRegistryPlainArgs();

    /**
     * The slug of the registry. This is used to identify the registry.
     * 
     */
    @Import(name="slug", required=true)
    private String slug;

    /**
     * @return The slug of the registry. This is used to identify the registry.
     * 
     */
    public String slug() {
        return this.slug;
    }

    private GetRegistryPlainArgs() {}

    private GetRegistryPlainArgs(GetRegistryPlainArgs $) {
        this.slug = $.slug;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRegistryPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRegistryPlainArgs $;

        public Builder() {
            $ = new GetRegistryPlainArgs();
        }

        public Builder(GetRegistryPlainArgs defaults) {
            $ = new GetRegistryPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param slug The slug of the registry. This is used to identify the registry.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            $.slug = slug;
            return this;
        }

        public GetRegistryPlainArgs build() {
            if ($.slug == null) {
                throw new MissingRequiredPropertyException("GetRegistryPlainArgs", "slug");
            }
            return $;
        }
    }

}
