// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.buildkite.Organization.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RegistryState extends com.pulumi.resources.ResourceArgs {

    public static final RegistryState Empty = new RegistryState();

    /**
     * A color representation of the registry. Accepts hex codes, eg #BADA55.
     * 
     */
    @Import(name="color")
    private @Nullable Output<String> color;

    /**
     * @return A color representation of the registry. Accepts hex codes, eg #BADA55.
     * 
     */
    public Optional<Output<String>> color() {
        return Optional.ofNullable(this.color);
    }

    /**
     * This is a description for the registry, this may describe the usage for it, the region, or something else
     * which would help identify the registry&#39;s purpose.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return This is a description for the registry, this may describe the usage for it, the region, or something else
     * which would help identify the registry&#39;s purpose.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The ecosystem of the registry. This value cannot be changed after creation.
     * 
     */
    @Import(name="ecosystem")
    private @Nullable Output<String> ecosystem;

    /**
     * @return The ecosystem of the registry. This value cannot be changed after creation.
     * 
     */
    public Optional<Output<String>> ecosystem() {
        return Optional.ofNullable(this.ecosystem);
    }

    /**
     * An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
     * emoji itself, such as 🚀.
     * 
     */
    @Import(name="emoji")
    private @Nullable Output<String> emoji;

    /**
     * @return An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
     * emoji itself, such as 🚀.
     * 
     */
    public Optional<Output<String>> emoji() {
        return Optional.ofNullable(this.emoji);
    }

    /**
     * The name of the registry. Can only contain numbers and letters, no spaces or special characters.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the registry. Can only contain numbers and letters, no spaces or special characters.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The registry&#39;s OIDC policy, in YAML format.
     * 
     */
    @Import(name="oidcPolicy")
    private @Nullable Output<String> oidcPolicy;

    /**
     * @return The registry&#39;s OIDC policy, in YAML format.
     * 
     */
    public Optional<Output<String>> oidcPolicy() {
        return Optional.ofNullable(this.oidcPolicy);
    }

    /**
     * Whether the registry is publicly accessible.
     * 
     */
    @Import(name="public")
    private @Nullable Output<Boolean> public_;

    /**
     * @return Whether the registry is publicly accessible.
     * 
     */
    public Optional<Output<Boolean>> public_() {
        return Optional.ofNullable(this.public_);
    }

    /**
     * The type of the registry (e.g. `source`).
     * 
     */
    @Import(name="registryType")
    private @Nullable Output<String> registryType;

    /**
     * @return The type of the registry (e.g. `source`).
     * 
     */
    public Optional<Output<String>> registryType() {
        return Optional.ofNullable(this.registryType);
    }

    /**
     * The slug of the registry.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return The slug of the registry.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    /**
     * The team UUIDs that have access to the registry. At least one team must be specified. This value cannot be changed after creation.
     * 
     */
    @Import(name="teamIds")
    private @Nullable Output<List<String>> teamIds;

    /**
     * @return The team UUIDs that have access to the registry. At least one team must be specified. This value cannot be changed after creation.
     * 
     */
    public Optional<Output<List<String>>> teamIds() {
        return Optional.ofNullable(this.teamIds);
    }

    /**
     * The UUID of the registry.
     * 
     */
    @Import(name="uuid")
    private @Nullable Output<String> uuid;

    /**
     * @return The UUID of the registry.
     * 
     */
    public Optional<Output<String>> uuid() {
        return Optional.ofNullable(this.uuid);
    }

    private RegistryState() {}

    private RegistryState(RegistryState $) {
        this.color = $.color;
        this.description = $.description;
        this.ecosystem = $.ecosystem;
        this.emoji = $.emoji;
        this.name = $.name;
        this.oidcPolicy = $.oidcPolicy;
        this.public_ = $.public_;
        this.registryType = $.registryType;
        this.slug = $.slug;
        this.teamIds = $.teamIds;
        this.uuid = $.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RegistryState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RegistryState $;

        public Builder() {
            $ = new RegistryState();
        }

        public Builder(RegistryState defaults) {
            $ = new RegistryState(Objects.requireNonNull(defaults));
        }

        /**
         * @param color A color representation of the registry. Accepts hex codes, eg #BADA55.
         * 
         * @return builder
         * 
         */
        public Builder color(@Nullable Output<String> color) {
            $.color = color;
            return this;
        }

        /**
         * @param color A color representation of the registry. Accepts hex codes, eg #BADA55.
         * 
         * @return builder
         * 
         */
        public Builder color(String color) {
            return color(Output.of(color));
        }

        /**
         * @param description This is a description for the registry, this may describe the usage for it, the region, or something else
         * which would help identify the registry&#39;s purpose.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description This is a description for the registry, this may describe the usage for it, the region, or something else
         * which would help identify the registry&#39;s purpose.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param ecosystem The ecosystem of the registry. This value cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder ecosystem(@Nullable Output<String> ecosystem) {
            $.ecosystem = ecosystem;
            return this;
        }

        /**
         * @param ecosystem The ecosystem of the registry. This value cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder ecosystem(String ecosystem) {
            return ecosystem(Output.of(ecosystem));
        }

        /**
         * @param emoji An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
         * emoji itself, such as 🚀.
         * 
         * @return builder
         * 
         */
        public Builder emoji(@Nullable Output<String> emoji) {
            $.emoji = emoji;
            return this;
        }

        /**
         * @param emoji An emoji to use with the registry, this can either be set using :buildkite: notation, or with the
         * emoji itself, such as 🚀.
         * 
         * @return builder
         * 
         */
        public Builder emoji(String emoji) {
            return emoji(Output.of(emoji));
        }

        /**
         * @param name The name of the registry. Can only contain numbers and letters, no spaces or special characters.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the registry. Can only contain numbers and letters, no spaces or special characters.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param oidcPolicy The registry&#39;s OIDC policy, in YAML format.
         * 
         * @return builder
         * 
         */
        public Builder oidcPolicy(@Nullable Output<String> oidcPolicy) {
            $.oidcPolicy = oidcPolicy;
            return this;
        }

        /**
         * @param oidcPolicy The registry&#39;s OIDC policy, in YAML format.
         * 
         * @return builder
         * 
         */
        public Builder oidcPolicy(String oidcPolicy) {
            return oidcPolicy(Output.of(oidcPolicy));
        }

        /**
         * @param public_ Whether the registry is publicly accessible.
         * 
         * @return builder
         * 
         */
        public Builder public_(@Nullable Output<Boolean> public_) {
            $.public_ = public_;
            return this;
        }

        /**
         * @param public_ Whether the registry is publicly accessible.
         * 
         * @return builder
         * 
         */
        public Builder public_(Boolean public_) {
            return public_(Output.of(public_));
        }

        /**
         * @param registryType The type of the registry (e.g. `source`).
         * 
         * @return builder
         * 
         */
        public Builder registryType(@Nullable Output<String> registryType) {
            $.registryType = registryType;
            return this;
        }

        /**
         * @param registryType The type of the registry (e.g. `source`).
         * 
         * @return builder
         * 
         */
        public Builder registryType(String registryType) {
            return registryType(Output.of(registryType));
        }

        /**
         * @param slug The slug of the registry.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug The slug of the registry.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        /**
         * @param teamIds The team UUIDs that have access to the registry. At least one team must be specified. This value cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder teamIds(@Nullable Output<List<String>> teamIds) {
            $.teamIds = teamIds;
            return this;
        }

        /**
         * @param teamIds The team UUIDs that have access to the registry. At least one team must be specified. This value cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder teamIds(List<String> teamIds) {
            return teamIds(Output.of(teamIds));
        }

        /**
         * @param teamIds The team UUIDs that have access to the registry. At least one team must be specified. This value cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder teamIds(String... teamIds) {
            return teamIds(List.of(teamIds));
        }

        /**
         * @param uuid The UUID of the registry.
         * 
         * @return builder
         * 
         */
        public Builder uuid(@Nullable Output<String> uuid) {
            $.uuid = uuid;
            return this;
        }

        /**
         * @param uuid The UUID of the registry.
         * 
         * @return builder
         * 
         */
        public Builder uuid(String uuid) {
            return uuid(Output.of(uuid));
        }

        public RegistryState build() {
            return $;
        }
    }

}
