---
name: Verify

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  PROVIDER: buildkite
  GO111MODULE: "on"

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@43d9fb6d85d5f01b391245805eefd258db160197 #v0.1.0-alpha.30
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  provider:
    runs-on: ubuntu-latest
    name: Lint Provider
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.21.x]
        golangci-lint-version: [v2.5.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/actions@d7ceb0215da5a14ec84f50b703365ddf0194a9c8 # v6.6.0

      - name: Build Provider
        run: make provider
      - name: Lint Provider
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: "${{ matrix.golangci-lint-version }}"
          working-directory: provider
          args: -c ../.golangci.yml

  sdk:
    runs-on: ubuntu-latest
    name: Build SDK
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.21.x]
        node-version: [22.x]
        dotnet-version: [3.1.301]
        python-version: [3.9]
        language:
          - go
          - nodejs
          - python
          - dotnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/actions@d7ceb0215da5a14ec84f50b703365ddf0194a9c8 # v6.6.0

      - name: Setup DotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "${{ matrix.dotnet-version }}"
        if: matrix.language == 'dotnet'
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"
        if: matrix.language == 'python'
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "${{ matrix.node-version }}"
        if: matrix.language == 'nodejs'

      - name: Build SDK
        run: make build_${{ matrix.language }}
