// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getMeta(opts?: pulumi.InvokeOptions): Promise<GetMetaResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("buildkite:index/getMeta:getMeta", {
    }, opts);
}

/**
 * A collection of values returned by getMeta.
 */
export interface GetMetaResult {
    readonly id: string;
    /**
     * A list of strings, each one an IP address (x.x.x.x) or CIDR address (x.x.x.x/32) that Buildkite may use to send webhooks and other external requests.
     */
    readonly webhookIps: string[];
}
